// =============================================================================
// Golden fixtures — extraction + composition
// 60 realistic MENA classifieds. Facts are normalized, not raw surface forms.
// Price "15 الف" => "15000". Color "اسود" => "أسود". Famous model may imply make.
// =============================================================================

export interface GoldenCase {
  readonly id: string;
  readonly input: string;
  readonly categorySlug: string;
  readonly expectedFacts: {
    readonly [key: string]: string | boolean | undefined;
  };
  readonly notes?: string;
}

export const GOLDEN_CASES: readonly GoldenCase[] = [
  {
    id: 'cars-camry-2020',
    input: 'كامري للبيع 2020 هايبرد بسعر 15 الف دينار لونها اسود ملوكي',
    categorySlug: 'motors',
    expectedFacts: { make: 'تويوتا', model: 'كامري', year: '2020', fuel: 'هايبرد', color: 'أسود', price: '15000' },
    notes: 'الأردن. كامري تدل على تويوتا. 15 الف = 15000.',
  },
  {
    id: 'cars-elantra-2019-jo',
    input: 'هيونداي النترا 2019 فل اوبشن قير اوتوماتيك ماشية 87 الف كم اللون فضي السعر 12500 دينار',
    categorySlug: 'motors',
    expectedFacts: { make: 'هيونداي', model: 'النترا', year: '2019', trans: 'أوتوماتيك', km: '87000', color: 'فضي', price: '12500' },
    notes: 'الأردن. 87 الف كم = 87000.',
  },
  {
    id: 'cars-accent-2016-lb',
    input: 'اكسنت 2016 بنزين قير عادي ماشية 140 الف كيلومتر بيضاء للبيع ب 6500 دولار',
    categorySlug: 'motors',
    expectedFacts: { make: 'هيونداي', model: 'اكسنت', year: '2016', fuel: 'بنزين', trans: 'عادي', km: '140000', color: 'أبيض', price: '6500' },
    notes: 'لبنان. اكسنت تدل على هيونداي.',
  },
  {
    id: 'cars-cerato-2021-sa',
    input: 'كيا سيراتو 2021 نص فل اوتوماتيك الديزل غير موجود بنزين واللون رمادي والسعر 48 الف ريال',
    categorySlug: 'motors',
    expectedFacts: { make: 'كيا', model: 'سيراتو', year: '2021', fuel: 'بنزين', trans: 'أوتوماتيك', color: 'رمادي', price: '48000' },
    notes: 'السعودية. نفي الديزل لا يُستخرج كوقود.',
  },
  {
    id: 'cars-corolla-2018-ps',
    input: 'تويوتا كورولا 2018 لون كحلي ماشية 62 الف كم السعر 43000 شيكل قابل للتفاوض',
    categorySlug: 'motors',
    expectedFacts: { make: 'تويوتا', model: 'كورولا', year: '2018', color: 'كحلي', km: '62000', price: '43000' },
    notes: 'فلسطين.',
  },
  {
    id: 'cars-sunny-2014-jo',
    input: 'نيسان سني 2014 ممشى 190 الف كم لون بيج السعر 5900 دينار',
    categorySlug: 'motors',
    expectedFacts: { make: 'نيسان', model: 'سني', year: '2014', km: '190000', color: 'بيج', price: '5900' },
    notes: 'الأردن.',
  },
  {
    id: 're-apartment-abdoun',
    input: 'شقة للبيع في عبدون 160 متر 3 غرف نوم و2 حمام الطابق الثالث السعر 95 الف دينار',
    categorySlug: 'real-estate',
    expectedFacts: { area: '160', rooms: '3', bathrooms: '2', floor: '3', price: '95000' },
    notes: 'الأردن. الطابق الثالث يُطبّع إلى 3.',
  },
  {
    id: 're-apartment-ground-sa',
    input: 'شقة ارضي في الرياض 140 متر مربع 4 غرف وحمامين السعر 620 الف ريال',
    categorySlug: 'real-estate',
    expectedFacts: { floor: 'أرضي', area: '140', rooms: '4', bathrooms: '2', price: '620000' },
    notes: 'السعودية. حمامين = 2.',
  },
  {
    id: 're-studio-beirut',
    input: 'ستوديو للايجار في الحمرا 45 متر غرفة واحدة وحمام ومطبخ الطابق الثاني الايجار 500 دولار',
    categorySlug: 'real-estate',
    expectedFacts: { area: '45', rooms: '1', bathrooms: '1', floor: '2', price: '500' },
    notes: 'لبنان. غرفة واحدة = 1. حمام ومطبخ = حمام واحد.',
  },
  {
    id: 're-villa-amman',
    input: 'فيلا مستقلة في دابوق مساحة 420 متر 5 غرف نوم و4 حمامات الدور الارضي مع تسوية السعر 280 الف دينار',
    categorySlug: 'real-estate',
    expectedFacts: { area: '420', rooms: '5', bathrooms: '4', floor: 'أرضي', price: '280000' },
    notes: 'الأردن. الطابق المذكور هو الأرضي.',
  },
  {
    id: 're-flat-nablus',
    input: 'شقة في نابلس 110م2 غرفتين نوم وحمام واحد الطابق الرابع السعر 78 الف دولار',
    categorySlug: 'real-estate',
    expectedFacts: { area: '110', rooms: '2', bathrooms: '1', floor: '4', price: '78000' },
    notes: 'فلسطين. غرفتين = 2.',
  },
  {
    id: 're-roof-jeddah',
    input: 'شقة روف في جدة 190 متر 3 غرف و3 حمامات السعر 850000 ريال',
    categorySlug: 'real-estate',
    expectedFacts: { floor: 'روف', area: '190', rooms: '3', bathrooms: '3', price: '850000' },
    notes: 'السعودية.',
  },
  {
    id: 'mobile-iphone-13',
    input: 'ايفون 13 برو 256 جيجا لون ازرق البطارية 89 السعر 280 دينار',
    categorySlug: 'mobiles',
    expectedFacts: { make: 'ابل', model: 'ايفون 13 برو', storage: '256', color: 'أزرق', price: '280' },
    notes: 'الأردن. ايفون تدل على ابل.',
  },
  {
    id: 'mobile-galaxy-s22-sa',
    input: 'سامسونج جالكسي اس 22 سعة 128 جيجا لون اسود السعر 1400 ريال',
    categorySlug: 'mobiles',
    expectedFacts: { make: 'سامسونج', model: 'جالكسي اس 22', storage: '128', color: 'أسود', price: '1400' },
    notes: 'السعودية.',
  },
  {
    id: 'mobile-redmi-lb',
    input: 'شاومي ريدمي نوت 11 ذاكرة 64 جيجا لون رمادي للبيع ب 120 دولار',
    categorySlug: 'mobiles',
    expectedFacts: { make: 'شاومي', model: 'ريدمي نوت 11', storage: '64', color: 'رمادي', price: '120' },
    notes: 'لبنان.',
  },
  {
    id: 'mobile-iphone-11-ps',
    input: 'ايفون 11 مستعمل 128GB لون ابيض السعر 900 شيكل',
    categorySlug: 'mobiles',
    expectedFacts: { make: 'ابل', model: 'ايفون 11', storage: '128', color: 'أبيض', condition: 'مستعمل', price: '900' },
    notes: 'فلسطين.',
  },
  {
    id: 'mobile-huawei-jo',
    input: 'هواوي نوفا 9 جديد 256 جيجابايت لون اخضر السعر 190 دينار',
    categorySlug: 'mobiles',
    expectedFacts: { make: 'هواوي', model: 'نوفا 9', storage: '256', color: 'أخضر', condition: 'جديد', price: '190' },
    notes: 'الأردن.',
  },
  {
    id: 'furniture-sofa-jo',
    input: 'كنب ثلاث مقاعد قماش لون بيج مستعمل نظيف السعر 180 دينار',
    categorySlug: 'furniture',
    expectedFacts: { seats: '3', material: 'قماش', color: 'بيج', condition: 'مستعمل', price: '180' },
    notes: 'الأردن. ثلاث مقاعد = 3.',
  },
  {
    id: 'furniture-bed-sa',
    input: 'سرير خشب نفرين لون بني جديد السعر 950 ريال',
    categorySlug: 'furniture',
    expectedFacts: { material: 'خشب', color: 'بني', condition: 'جديد', price: '950' },
    notes: 'السعودية.',
  },
  {
    id: 'furniture-dining-lb',
    input: 'طاولة سفرة مع 6 كراسي خشب لون ابيض السعر 400 دولار',
    categorySlug: 'furniture',
    expectedFacts: { seats: '6', material: 'خشب', color: 'أبيض', price: '400' },
    notes: 'لبنان.',
  },
  {
    id: 'furniture-chair-ps',
    input: 'مقعدين جلد لون اسود استعمال خفيف السعر 70 دولار',
    categorySlug: 'furniture',
    expectedFacts: { seats: '2', material: 'جلد', color: 'أسود', condition: 'استعمال خفيف', price: '70' },
    notes: 'فلسطين. مقعدين = 2.',
  },
  {
    id: 'jobs-accountant-jo',
    input: 'مطلوب محاسب بخبرة 5 سنوات للعمل في عمان دوام كامل',
    categorySlug: 'jobs',
    expectedFacts: { jobTitle: 'محاسب', exp: '5' },
    notes: 'الأردن.',
  },
  {
    id: 'jobs-nurse-sa',
    input: 'ممرضة بخبرة لا تقل عن 3 سنوات في الرياض',
    categorySlug: 'jobs',
    expectedFacts: { jobTitle: 'ممرض', exp: '3' },
    notes: 'السعودية.',
  },
  {
    id: 'jobs-driver-lb',
    input: 'سائق خصوصي خبرة 8 سنين رخصة عمومي في بيروت',
    categorySlug: 'jobs',
    expectedFacts: { jobTitle: 'سائق', exp: '8' },
    notes: 'لبنان.',
  },
  {
    id: 'jobs-teacher-ps',
    input: 'مدرس رياضيات خصوصي خبرة 4 سنوات في نابلس',
    categorySlug: 'jobs',
    expectedFacts: { jobTitle: 'مدرس', exp: '4' },
    notes: 'فلسطين.',
  },
  {
    id: 'watches-rolex-jo',
    input: 'ساعة رولكس سابمارينر مستعملة لون اسود السعر 4200 دينار',
    categorySlug: 'watches',
    expectedFacts: { brand: 'Rolex', color: 'أسود', condition: 'مستعمل', price: '4200' },
    notes: 'الأردن.',
  },
  {
    id: 'watches-casio-sa',
    input: 'كاسيو جي شوك جديد لون ازرق السعر 350 ريال',
    categorySlug: 'watches',
    expectedFacts: { brand: 'Casio', color: 'أزرق', condition: 'جديد', price: '350' },
    notes: 'السعودية.',
  },
  {
    id: 'watches-omega-lb',
    input: 'ساعة اوميغا سيماستر لون فضي استعمال خفيف السعر 1800 دولار',
    categorySlug: 'watches',
    expectedFacts: { brand: 'Omega', color: 'فضي', condition: 'استعمال خفيف', price: '1800' },
    notes: 'لبنان.',
  },
  {
    id: 'computers-hp-jo',
    input: 'لابتوب اتش بي برو بوك 2021 رام 16 وذاكرة 512 جيجا لون رمادي السعر 390 دينار',
    categorySlug: 'computers',
    expectedFacts: { make: 'HP', model: 'برو بوك', year: '2021', storage: '512', color: 'رمادي', price: '390' },
    notes: 'الأردن. الرام ليست سعة تخزين.',
  },
  {
    id: 'computers-dell-sa',
    input: 'ديل لاتيتيود مستعمل 256GB لون اسود السعر 900 ريال',
    categorySlug: 'computers',
    expectedFacts: { make: 'Dell', model: 'لاتيتيود', storage: '256', color: 'أسود', condition: 'مستعمل', price: '900' },
    notes: 'السعودية.',
  },
  {
    id: 'computers-lenovo-ps',
    input: 'لينوفو ايديا باد 2020 سعة 1 تيرا لون ازرق السعر 280 دولار',
    categorySlug: 'computers',
    expectedFacts: { make: 'Lenovo', model: 'ايديا باد', year: '2020', storage: '1', color: 'أزرق', price: '280' },
    notes: 'فلسطين.',
  },
  {
    id: 'electronics-lg-jo',
    input: 'تلفزيون ال جي 2022 سمارت لون اسود استعمال خفيف السعر 220 دينار',
    categorySlug: 'electronics',
    expectedFacts: { make: 'LG', year: '2022', color: 'أسود', condition: 'استعمال خفيف', price: '220' },
    notes: 'الأردن.',
  },
  {
    id: 'electronics-samsung-washer-sa',
    input: 'غسالة سامسونج اتوماتيك لون ابيض جديدة السعر 1600 ريال',
    categorySlug: 'electronics',
    expectedFacts: { make: 'Samsung', color: 'أبيض', condition: 'جديد', price: '1600' },
    notes: 'السعودية.',
  },
  {
    id: 'electronics-ps5-lb',
    input: 'جهاز بلايستيشن 5 مع يد لون ابيض السعر 450 دولار',
    categorySlug: 'electronics',
    expectedFacts: { make: 'Sony', model: 'بلايستيشن 5', color: 'أبيض', price: '450' },
    notes: 'لبنان.',
  },
  {
    id: 'fashion-abaya-sa',
    input: 'عباية كحلية قماش جديدة مقاس واسع السعر 180 ريال',
    categorySlug: 'fashion',
    expectedFacts: { color: 'كحلي', material: 'قماش', condition: 'جديد', price: '180' },
    notes: 'السعودية.',
  },
  {
    id: 'fashion-shoes-jo',
    input: 'حذاء نايك رجالي لون ابيض مقاس 43 مستعمل السعر 25 دينار',
    categorySlug: 'fashion',
    expectedFacts: { make: 'Nike', gender: 'رجالي', color: 'أبيض', condition: 'مستعمل', price: '25' },
    notes: 'الأردن.',
  },
  {
    id: 'fashion-dress-lb',
    input: 'فستان سهرة حرير لون خمري نسائي استعمال خفيف السعر 60 دولار',
    categorySlug: 'fashion',
    expectedFacts: { material: 'حرير', color: 'خمري', gender: 'نسائي', condition: 'استعمال خفيف', price: '60' },
    notes: 'لبنان.',
  },
  {
    id: 'beauty-lattafa-sa',
    input: 'عطر لطافة يارا جديد مغلف السعر 90 ريال',
    categorySlug: 'beauty',
    expectedFacts: { brand: 'Lattafa', condition: 'جديد', price: '90' },
    notes: 'السعودية.',
  },
  {
    id: 'beauty-flormar-jo',
    input: 'مجموعة فلورمار مكياج لون وردي مفتوحة السعر 12 دينار',
    categorySlug: 'beauty',
    expectedFacts: { brand: 'Flormar', color: 'وردي', price: '12' },
    notes: 'الأردن.',
  },
  {
    id: 'beauty-dior-lb',
    input: 'عطر ديور سوفاج رجالي استعمال خفيف السعر 70 دولار',
    categorySlug: 'beauty',
    expectedFacts: { brand: 'Dior', gender: 'رجالي', condition: 'استعمال خفيف', price: '70' },
    notes: 'لبنان.',
  },
  {
    id: 'kids-stroller-jo',
    input: 'عربية اطفال من عمر 0-6 أشهر لون بيج مستعملة السعر 45 دينار',
    categorySlug: 'kids',
    expectedFacts: { age: '0-6', color: 'بيج', condition: 'مستعمل', price: '45' },
    notes: 'الأردن.',
  },
  {
    id: 'kids-bike-sa',
    input: 'دراجة اطفال عمر 3 سنوات لون احمر جديدة السعر 150 ريال',
    categorySlug: 'kids',
    expectedFacts: { age: '3', color: 'أحمر', condition: 'جديد', price: '150' },
    notes: 'السعودية.',
  },
  {
    id: 'kids-clothes-ps',
    input: 'ملابس اطفال من 1-3 سنوات لون ازرق استعمال خفيف السعر 20 دولار',
    categorySlug: 'kids',
    expectedFacts: { age: '1-3', color: 'أزرق', condition: 'استعمال خفيف', price: '20' },
    notes: 'فلسطين.',
  },
  {
    id: 'pets-persian-jo',
    input: 'قط شيرازي ابيض عمره سنتين مطعم السعر 80 دينار',
    categorySlug: 'pets',
    expectedFacts: { breed: 'شيرازي', color: 'أبيض', price: '80' },
    notes: 'الأردن.',
  },
  {
    id: 'pets-husky-sa',
    input: 'جرو هاسكي لون رمادي عمره 4 أشهر السعر 1500 ريال',
    categorySlug: 'pets',
    expectedFacts: { breed: 'هاسكي', color: 'رمادي', age: '4', price: '1500' },
    notes: 'السعودية.',
  },
  {
    id: 'pets-saluki-ps',
    input: 'كلب سلوقي بني بالغ السعر 300 دولار',
    categorySlug: 'pets',
    expectedFacts: { breed: 'سلوقي', color: 'بني', price: '300' },
    notes: 'فلسطين.',
  },
  {
    id: 'sports-treadmill-jo',
    input: 'جهاز مشي يورك لون اسود مستعمل السعر 160 دينار',
    categorySlug: 'sports',
    expectedFacts: { make: 'يورك', color: 'أسود', condition: 'مستعمل', price: '160' },
    notes: 'الأردن.',
  },
  {
    id: 'sports-ball-sa',
    input: 'كرة اديداس جديدة لون ابيض السعر 80 ريال',
    categorySlug: 'sports',
    expectedFacts: { make: 'اديداس', color: 'أبيض', condition: 'جديد', price: '80' },
    notes: 'السعودية.',
  },
  {
    id: 'books-novel-lb',
    input: 'رواية موسم الهجرة إلى الشمال الطيب صالح نسخة مستعملة السعر 5 دولار',
    categorySlug: 'books',
    expectedFacts: { condition: 'مستعمل', price: '5' },
    notes: 'لبنان.',
  },
  {
    id: 'books-school-jo',
    input: 'كتاب رياضيات الصف الثامن جديد السعر 6 دينار',
    categorySlug: 'books',
    expectedFacts: { condition: 'جديد', price: '6' },
    notes: 'الأردن.',
  },
  {
    id: 'garden-hose-sa',
    input: 'بربيش حديقة بلاستيك لون اخضر جديد طول مناسب السعر 40 ريال',
    categorySlug: 'home-garden',
    expectedFacts: { material: 'بلاستيك', color: 'أخضر', condition: 'جديد', price: '40' },
    notes: 'السعودية.',
  },
  {
    id: 'garden-pots-jo',
    input: 'قصاري زرع سيراميك لون بني مستعملة السعر 15 دينار',
    categorySlug: 'home-garden',
    expectedFacts: { material: 'سيراميك', color: 'بني', condition: 'مستعمل', price: '15' },
    notes: 'الأردن.',
  },
  {
    id: 'krakeeb-mix-jo',
    input: 'كراكيب منزلية اغراض متفرقة لون بني استعمال خفيف السعر 20 دينار',
    categorySlug: 'krakeeb',
    expectedFacts: { color: 'بني', condition: 'استعمال خفيف', price: '20' },
    notes: 'الأردن.',
  },
  {
    id: 'services-tutor-ps',
    input: 'مدرس خصوصي لغة انجليزية خبرة 6 سنوات في رام الله',
    categorySlug: 'services',
    expectedFacts: { jobTitle: 'مدرس خصوصي', exp: '6' },
    notes: 'فلسطين.',
  },
  {
    id: 'services-designer-lb',
    input: 'مصمم جرافيك خبرة 3 سنوات تنفيذ شعارات في بيروت',
    categorySlug: 'services',
    expectedFacts: { jobTitle: 'مصمم جرافيك', exp: '3' },
    notes: 'لبنان.',
  },
  {
    id: 'cleaning-home-jo',
    input: 'خدمة تنظيف منازل في عمان بخبرة 4 سنوات السعر 25 دينار',
    categorySlug: 'cleaning',
    expectedFacts: { jobTitle: 'منظف', exp: '4', price: '25' },
    notes: 'الأردن.',
  },
  {
    id: 'handymen-electric-sa',
    input: 'كهربائي منازل في جدة خبرة 10 سنوات كشف قبل العمل',
    categorySlug: 'handymen',
    expectedFacts: { jobTitle: 'كهربائي', exp: '10' },
    notes: 'السعودية.',
  },
  {
    id: 'handymen-plumber-jo',
    input: 'سباك و مواسرجي في الزرقاء خبرة 7 سنين السعر بعد الكشف',
    categorySlug: 'handymen',
    expectedFacts: { jobTitle: 'سباك', exp: '7' },
    notes: 'الأردن.',
  },
  {
    id: 'handymen-ac-sa',
    input: 'فني تكييف في الدمام خبرة 9 سنوات صيانة مكيفات سبليت السعر بعد الكشف',
    categorySlug: 'handymen',
    expectedFacts: { jobTitle: 'فني تكييف', exp: '9' },
    notes: 'السعودية.',
  },
  {
    id: 'projects-cafe-lb',
    input: 'مقهى قائم للبيع في جونيه الموقع ظاهر والدراسة للجادين السعر 35 الف دولار',
    categorySlug: 'projects',
    expectedFacts: { jobTitle: 'مقهى', price: '35000' },
    notes: 'لبنان.',
  },
];
