import type { StructuredLayout } from '../types';

type GenericPool = Omit<
  StructuredLayout,
  'subTitleFormat' | 'subHooks' | 'subIntroParagraphs' | 'subFeaturesBullets' | 'subCtas'
>;

const DEVICE_SUBS = ['phones', 'tablets', 'smart-watches', 'accessories'] as const;
const PHONE_TABLET_SUBS = ['phones', 'tablets'] as const;
const NUMBER_SUBS = ['numbers'] as const;

export const MOBILES_GENERIC_POOLS: GenericPool = {
  titleFormat: [
    { template: '{make} {model} بسعر {price}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} متوفر بسعر {price}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} معروض بسعر {price}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} سعره {price}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} للبيع بسعر {price}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بسعر {price} جاهز', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} الآن بسعر {price}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بسعر {price} مفحوص', subcategories: [...DEVICE_SUBS] },
    { template: 'عرض {make} {model} بسعر {price}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} متاح بسعر {price}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بلون {color} بسعر {price}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بحالة {condition} بسعر {price}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بذاكرة {storage} بسعر {price}', subcategories: [...PHONE_TABLET_SUBS] },
    { template: '{make} {model} سعة {storage} بسعر {price}', subcategories: [...PHONE_TABLET_SUBS] },
    { template: '{make} {model} بحالة {condition}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بذاكرة {storage}', subcategories: [...PHONE_TABLET_SUBS] },
    { template: '{make} {model} بلون {color}', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} جاهز للاستخدام', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} مفحوص للبيع', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بحالة {condition} جاهز', subcategories: [...DEVICE_SUBS] },
    { template: 'رقم مميز بسعر {price}', subcategories: [...NUMBER_SUBS] },
    { template: 'رقم للبيع بسعر {price}', subcategories: [...NUMBER_SUBS] },
    { template: 'رقم متاح بسعر {price}', subcategories: [...NUMBER_SUBS] },
    { template: 'رقم جوال بسعر {price}', subcategories: [...NUMBER_SUBS] },
    { template: 'رقم معروض بسعر {price}', subcategories: [...NUMBER_SUBS] },
  ],
  hooks: [
    { template: '{make} {model} يفتح باب الاستخدام اليومي بلا قلق.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} جاهز ليومك من أول استخدام.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بحالة {condition} يطمئنك قبل أن تبدأ الاستخدام.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بذاكرة {storage} يسع يومك دون حذف متكرر.', subcategories: [...PHONE_TABLET_SUBS] },
    { template: '{make} {model} بلون {color} يلائم استخدامك اليومي بمظهر مرتب.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بسعر {price} يناسب من يريد جهازاً مفحوصاً.', subcategories: [...DEVICE_SUBS] },
    { template: 'بسعر {price} تحصل على {make} {model} جاهزاً للاستخدام.', subcategories: [...DEVICE_SUBS] },
    { template: 'سعر {price} يضع {make} {model} في متناول استخدام يومي مريح.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} مقابل {price} مع فحص يطمئن قبل الشراء.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بسعر {price} لمن يريد انتقالاً سلساً بلا مفاجآت.', subcategories: [...DEVICE_SUBS] },
    { template: 'امتلاك {make} {model} بسعر {price} يعني جهازاً جاهزاً من اليوم.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بسعر {price} يريح من يبحث عن وضوح قبل الدفع.', subcategories: [...DEVICE_SUBS] },
    { template: 'رقم بسعر {price} يسهّل تواصلك اليومي بهوية واضحة.', subcategories: [...NUMBER_SUBS] },
    { template: 'بسعر {price} تحصل على رقم جاهز للاستخدام الفوري.', subcategories: [...NUMBER_SUBS] },
    { template: 'رقم معروض بسعر {price} يناسب من يريد خطاً مستقراً بلا تعقيد.', subcategories: [...NUMBER_SUBS] },
  ],
  introParagraphs: [
    { template: '{make} {model} جاهز لمن يريد جهازاً يثق به في المكالمات والتصفح والتنقل اليومي.', subcategories: [...DEVICE_SUBS] },
    { template: 'بسعر {price} تجد جهازاً مفحوصاً يناسب الاستخدام اليومي دون مفاجآت بعد الاستلام.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بحالة {condition} يلائم من ينتقل إلى جهاز يعمل من أول يوم.', subcategories: [...DEVICE_SUBS] },
    { template: 'الذاكرة {storage} في {make} {model} تسع الصور والتطبيقات براحة أوضح.', subcategories: [...PHONE_TABLET_SUBS] },
    { template: 'اللون {color} في {make} {model} يحافظ على مظهر مرتب مع الاستخدام اليومي.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} خيار عملي لمن يريد أداءً مستقراً في يوم عمل طويل.', subcategories: [...DEVICE_SUBS] },
    { template: 'السعر {price} معلن بوضوح، والجهاز معروض بتفاصيل تساعدك على القرار قبل المعاينة.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} يصل إليك بفحص مسبق يطمئن على الاستخدام قبل الاستلام.', subcategories: [...DEVICE_SUBS] },
    { template: 'إذا كان هدفك جهازاً أصلياً للاستخدام الفوري، فـ {make} {model} معروض لهذا الغرض.', subcategories: [...DEVICE_SUBS] },
    { template: 'بسعر {price} يمكنك الانتقال إلى جهاز يخدم مكالماتك وصورك بلا تعقيد.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} بحالة {condition} مناسب لمن يفضّل جهازاً واضح الوصف قبل الشراء.', subcategories: [...DEVICE_SUBS] },
    { template: 'سعة {storage} تترك مساحة لتطبيقاتك اليومية دون ضغط مستمر على الذاكرة.', subcategories: [...PHONE_TABLET_SUBS] },
    { template: '{make} {model} بلون {color} يبقى أنيقاً مع الحمل المتكرر خلال اليوم.', subcategories: [...DEVICE_SUBS] },
    { template: 'هذا العرض يضع {make} {model} أمامك بتفاصيل ظاهرة قبل أي تواصل.', subcategories: [...DEVICE_SUBS] },
    { template: 'جهاز من {make} يناسب من يريد بساطة في الاستخدام ووضوحاً في الحالة قبل الشراء.', subcategories: [...DEVICE_SUBS] },
    { template: '{model} هنا معروض لمن يبحث عن تجربة مألوفة بلا إعداد معقّد بعد الاستلام.', subcategories: [...DEVICE_SUBS] },
    { template: 'السعر {price} ثابت في الإعلان، والمعاينة متاحة في وقت يناسبك.', subcategories: [...DEVICE_SUBS] },
    { template: '{make} {model} يقصر عليك المقارنة إذا كنت تريد جهازاً جاهزاً اليوم.', subcategories: [...DEVICE_SUBS] },
    { template: 'رقم معروض بسعر {price} لمن يريد خطاً جاهزاً للتفعيل دون انتظار طويل.', subcategories: [...NUMBER_SUBS] },
    { template: 'بسعر {price} تحصل على رقم واضح التفاصيل، مناسب للاستخدام الشخصي أو العمل.', subcategories: [...NUMBER_SUBS] },
  ],
  detailsGroups: [
    { fact: 'make', variants: [
      { template: 'الجهاز من شركة {make}، بهوية أصلية ظاهرة.', subcategories: [...DEVICE_SUBS] },
      { template: 'العلامة {make} موثّقة على الجهاز قبل العرض.', subcategories: [...DEVICE_SUBS] },
      { template: 'هذا الجهاز يحمل اسم {make} كما هو معلن.', subcategories: [...DEVICE_SUBS] },
      { template: 'الشركة المصنّعة هي {make}، ويمكن التحقق منها عند المعاينة.', subcategories: [...DEVICE_SUBS] },
      { template: 'العلامة المدوّنة على الجهاز المعروض هي {make}.', subcategories: [...DEVICE_SUBS] },
    ]},
    { fact: 'model', variants: [
      { template: 'الطراز المعروض هو {model} كما هو مذكور في الإعلان.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز من طراز {model} دون اختلاف عن الوصف.', subcategories: [...DEVICE_SUBS] },
      { template: 'الموديل {model} هو المتاح للمعاينة والاستلام.', subcategories: [...DEVICE_SUBS] },
      { template: 'ستجد الطراز {model} مطابقاً للتفاصيل المنشورة.', subcategories: [...DEVICE_SUBS] },
      { template: 'الطراز الذي تم فحصه قبل العرض هو {model}.', subcategories: [...DEVICE_SUBS] },
    ]},
    { fact: 'color', variants: [
      { template: 'اللون الظاهر على الجهاز هو {color}.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز معروض باللون {color} كما تراه في الصور.', subcategories: [...DEVICE_SUBS] },
      { template: 'درجة اللون المعتمدة في هذا العرض هي {color}.', subcategories: [...DEVICE_SUBS] },
      { template: 'لون الجهاز {color}، ويمكن التأكد منه عند المعاينة.', subcategories: [...DEVICE_SUBS] },
      { template: 'اللون الفعلي للجهاز المعروض هو {color}.', subcategories: [...DEVICE_SUBS] },
    ]},
    { fact: 'storage', variants: [
      { template: 'سعة التخزين في الجهاز هي {storage}.', subcategories: [...PHONE_TABLET_SUBS] },
      { template: 'الذاكرة المتاحة {storage} كما هي مدوّنة في المواصفات.', subcategories: [...PHONE_TABLET_SUBS] },
      { template: 'الجهاز مزوّد بسعة {storage} للاستخدام اليومي.', subcategories: [...PHONE_TABLET_SUBS] },
      { template: 'التخزين الفعلي المعروض هو {storage}.', subcategories: [...PHONE_TABLET_SUBS] },
      { template: 'المساحة المرافقة لهذا الجهاز هي {storage}.', subcategories: [...PHONE_TABLET_SUBS] },
    ]},
    { fact: 'condition', variants: [
      { template: 'حالة الجهاز {condition} كما تم فحصها قبل النشر.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز بحالة {condition}، ظاهرة عند المعاينة.', subcategories: [...DEVICE_SUBS] },
      { template: 'الوصف المعتمد لحالة الجهاز هو {condition}.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز مصنّف بحالة {condition} بعد الفحص.', subcategories: [...DEVICE_SUBS] },
      { template: 'ستعاين الجهاز وهو بحالة {condition} دون تجميل في الوصف.', subcategories: [...DEVICE_SUBS] },
    ]},
    { fact: 'battery', variants: [
      { template: 'حالة البطارية المسجّلة هي {battery} بعد الفحص.', subcategories: [...DEVICE_SUBS] },
      { template: 'البطارية مفحوصة ونتيجتها {battery} قبل العرض.', subcategories: [...DEVICE_SUBS] },
      { template: 'قراءة البطارية الظاهرة {battery} كما قيست.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز يحمل بطارية بنسبة {battery} وفق آخر فحص.', subcategories: [...DEVICE_SUBS] },
      { template: 'نتيجة فحص البطارية {battery}، ويمكن مراجعتها عند المعاينة.', subcategories: [...DEVICE_SUBS] },
    ]},
    { fact: 'warranty', variants: [
      { template: 'الضمان المتاح على الجهاز هو {warranty}.', subcategories: [...DEVICE_SUBS] },
      { template: 'مدة الضمان المعلنة {warranty} كما هي في العرض.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز مشمول بضمان {warranty} وفق التفاصيل المنشورة.', subcategories: [...DEVICE_SUBS] },
      { template: 'تغطية الضمان هنا {warranty}، وتُوضَّح عند التواصل.', subcategories: [...DEVICE_SUBS] },
      { template: 'الضمان المرافق للعرض هو {warranty}.', subcategories: [...DEVICE_SUBS] },
    ]},
    { fact: 'region', variants: [
      { template: 'منطقة الجهاز المسجّلة هي {region}.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز بإصدار {region} كما هو مذكور.', subcategories: [...DEVICE_SUBS] },
      { template: 'الإصدار الإقليمي المعروض هو {region}.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز يتبع منطقة {region} وفق البيانات الظاهرة.', subcategories: [...DEVICE_SUBS] },
      { template: 'التصنيف الإقليمي للجهاز هو {region}.', subcategories: [...DEVICE_SUBS] },
    ]},
    { fact: 'year', variants: [
      { template: 'سنة إصدار الجهاز هي {year}.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز من عام {year} كما هو معلن.', subcategories: [...DEVICE_SUBS] },
      { template: 'تاريخ الطرح المرتبط بهذا الجهاز {year}.', subcategories: [...DEVICE_SUBS] },
      { template: 'الإصدار يعود إلى سنة {year}.', subcategories: [...DEVICE_SUBS] },
      { template: 'سنة الجهاز المدوّنة في العرض هي {year}.', subcategories: [...DEVICE_SUBS] },
    ]},
    { fact: 'price', variants: [
      { template: 'السعر المعلن للجهاز هو {price}.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز معروض بسعر {price} كما هو منشور.', subcategories: [...DEVICE_SUBS] },
      { template: 'القيمة المطلوبة {price} دون تغيير في الإعلان.', subcategories: [...DEVICE_SUBS] },
      { template: 'سعر العرض المعتمد هو {price}.', subcategories: [...DEVICE_SUBS] },
      { template: 'السعر الظاهر قبل أي تواصل هو {price}.', subcategories: [...DEVICE_SUBS] },
    ]},
    { fact: 'box', variants: [
      { template: 'العلبة المرافقة حالتها {box}.', subcategories: [...DEVICE_SUBS] },
      { template: 'صندوق الجهاز {box} كما هو موضّح في التفاصيل.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز يُعرض مع علبة {box}.', subcategories: [...DEVICE_SUBS] },
      { template: 'حالة العلبة الأصلية {box} وفق المعاينة.', subcategories: [...DEVICE_SUBS] },
      { template: 'العلبة المتاحة مع الجهاز {box}.', subcategories: [...DEVICE_SUBS] },
    ]},
    { fact: 'charger', variants: [
      { template: 'الشاحن المرافق حالته {charger}.', subcategories: [...DEVICE_SUBS] },
      { template: 'الجهاز مع شاحن {charger} كما هو مذكور.', subcategories: [...DEVICE_SUBS] },
      { template: 'ملحق الشحن المعروض هو {charger}.', subcategories: [...DEVICE_SUBS] },
      { template: 'الشاحن المتاح مع الجهاز {charger}.', subcategories: [...DEVICE_SUBS] },
      { template: 'حالة الشاحن في هذا العرض {charger}.', subcategories: [...DEVICE_SUBS] },
    ]},
  ],
  featuresBullets: [
    { template: 'بطارية مفحوصة قبل العرض تقلل مفاجآت الاستخدام اليومي.', subcategories: ['phones', 'tablets', 'smart-watches'] },
    { template: 'شاشة واضحة تريح العين في القراءة والتصفح الطويل.', subcategories: ['phones', 'tablets', 'smart-watches'] },
    { template: 'كاميرا تلتقط تفاصيل يومك دون إعداد معقّد.', subcategories: [...PHONE_TABLET_SUBS] },
    { template: 'أداء مستقر يواكب التطبيقات والمكالمات في يوم مزدحم.', subcategories: ['phones', 'tablets', 'smart-watches'] },
    { template: 'تصميم مريح في اليد يناسب الحمل والتنقل اليومي.', subcategories: [...DEVICE_SUBS] },
    { template: 'ضمان ظاهر يطمئنك بعد الاستلام لا قبله فقط.', subcategories: [...DEVICE_SUBS] },
    { template: 'جهاز أصلي بهوية واضحة قبل إتمام الشراء.', subcategories: [...DEVICE_SUBS] },
    { template: 'فحص مسبق يشمل الوظائف الأساسية قبل العرض.', subcategories: [...DEVICE_SUBS] },
    { template: 'شحن متوافق يقصّر وقت التجهيز بعد الاستلام.', subcategories: [...DEVICE_SUBS] },
    { template: 'علبة أصلية تحفظ الملحقات وتوثّق مصدر الجهاز.', subcategories: [...DEVICE_SUBS] },
    { template: 'بطارية تحتفظ بشحن يكفي ساعات العمل المتصلة.', subcategories: ['phones', 'tablets', 'smart-watches'] },
    { template: 'سطوع الشاشة يبقى مقروءاً في الإضاءة القوية.', subcategories: ['phones', 'tablets', 'smart-watches'] },
    { template: 'صور أوضح في الإضاءة الداخلية دون فلاش مزعج.', subcategories: [...PHONE_TABLET_SUBS] },
    { template: 'تنقّل سلس بين التطبيقات دون انتظار طويل.', subcategories: ['phones', 'tablets', 'smart-watches'] },
    { template: 'هيكل نظيف يحافظ على مظهر الجهاز مع الاستخدام.', subcategories: [...DEVICE_SUBS] },
    { template: 'فترة ضمان تترك لك وقتاً للتجربة بعد الشراء.', subcategories: [...DEVICE_SUBS] },
    { template: 'قطع أصلية تعني توافقاً أفضل مع التحديثات.', subcategories: [...DEVICE_SUBS] },
    { template: 'معاينة قبل الشراء تكشف الحالة كما هي.', subcategories: [...DEVICE_SUBS] },
    { template: 'بطارية لا تفرض عليك الشحن في منتصف اليوم.', subcategories: ['phones', 'tablets', 'smart-watches'] },
    { template: 'شاشة لمس دقيقة تستجيب من أول لمسة.', subcategories: ['phones', 'tablets', 'smart-watches'] },
    { template: 'كاميرا أمامية تصلح للمكالمات المرئية بوضوح كافٍ.', subcategories: [...PHONE_TABLET_SUBS] },
    { template: 'ذاكرة تسع ملفات العمل دون حذف أسبوعي.', subcategories: [...PHONE_TABLET_SUBS] },
    { template: 'لون ثابت لا يبهت مع الحمل اليومي.', subcategories: [...DEVICE_SUBS] },
    { template: 'إصدار الجهاز موثّق لتفادي قيود الاستخدام.', subcategories: ['phones', 'tablets', 'smart-watches'] },
    { template: 'شاحن مرافق يغنيك عن شراء ملحق منفصل فوراً.', subcategories: [...DEVICE_SUBS] },
    { template: 'رقم بسعر {price} جاهز للربط دون إجراءات إضافية معقّدة.', subcategories: [...NUMBER_SUBS] },
    { template: 'السعر {price} واضح قبل أي تواصل حول الرقم.', subcategories: [...NUMBER_SUBS] },
    { template: 'بسعر {price} تحصل على رقم يمكن تفعيله في وقت قصير.', subcategories: [...NUMBER_SUBS] },
    { template: 'رقم معروض بسعر {price} يناسب الاستخدام الشخصي اليومي.', subcategories: [...NUMBER_SUBS] },
    { template: 'قيمة الرقم عند {price} معلنة دون رسوم مخفية في الإعلان.', subcategories: [...NUMBER_SUBS] },
  ],
  ctas: [
    { template: 'تواصل لترتيب معاينة الجهاز في وقت يناسبك.', subcategories: [...DEVICE_SUBS] },
    { template: 'راسلنا لتأكيد التفاصيل قبل الزيارة.', subcategories: [...DEVICE_SUBS] },
    { template: 'اتصل لتنسيق استلام الجهاز بما يلائمك.', subcategories: [...DEVICE_SUBS] },
    { template: 'احجز معاينة للجهاز في وقت يناسبك.', subcategories: [...DEVICE_SUBS] },
    { template: 'للتنسيق على المعاينة، اختر الوقت الأنسب لك.', subcategories: [...DEVICE_SUBS] },
    { template: 'تواصل اليوم لمعرفة حالة البطارية عن قرب.', subcategories: ['phones', 'tablets', 'smart-watches'] },
    { template: 'راسلنا إن رغبت بصور إضافية قبل القرار.', subcategories: [...DEVICE_SUBS] },
    { template: 'اتصل لترتيب تسليم يناسب جدولك.', subcategories: [...DEVICE_SUBS] },
    { template: 'احجز وقتاً قصيراً لمعاينة الجهاز قبل الشراء.', subcategories: [...DEVICE_SUBS] },
    { template: 'للتنسيق على السعر {price} والاستلام، تواصل معنا.', subcategories: [...DEVICE_SUBS] },
    { template: 'تواصل وسنرتب لك معاينة بلا التزام.', subcategories: [...DEVICE_SUBS] },
    { template: 'راسلنا لنؤكد توفر {model} قبل زيارتك.', subcategories: [...DEVICE_SUBS] },
    { template: 'اتصل وسنوضح لك تفاصيل الفحص بهدوء.', subcategories: [...DEVICE_SUBS] },
    { template: 'تواصل لمعرفة خطوات نقل الرقم في وقت يناسبك.', subcategories: [...NUMBER_SUBS] },
    { template: 'راسلنا لتنسيق استلام الرقم دون تعقيد.', subcategories: [...NUMBER_SUBS] },
  ],
  detailsLabel: '🔹 المواصفات:',
  featuresLabel: '🔹 أبرز المميزات:',
  featuresCount: 4,
  introCount: 2,
  minDetails: 1,
};
