import type { StructuredLayout } from '../types';

type GenericPool = Omit<
  StructuredLayout,
  'subTitleFormat' | 'subHooks' | 'subIntroParagraphs' | 'subFeaturesBullets' | 'subCtas'
>;

export const MOBILES_GENERIC_POOLS: GenericPool = {
titleFormat: [
      { template: "رقم مميز للبيع بسعر {price}", subcategories: ["numbers"] },
      { template: "رقم جوال مقابل {price} مع نقل ملكية", subcategories: ["numbers"] },
      { template: "بيع رقم بسعر {price} وتوثيق النقل", subcategories: ["numbers"] },
      { template: "رقم معروض بـ{price} بلا وسيط", subcategories: ["numbers"] },
      { template: "نقل رقم بسعر {price} بعد التوثيق", subcategories: ["numbers"] },
      { template: "{make} {model} بسعر {price}", subcategories: [] },
      { template: "{make} {model} — {price}", subcategories: [] },
      { template: "بيع {make} {model} مقابل {price}", subcategories: [] },
      { template: "{make} {model} للبيع بسعر {price}", subcategories: [] },
      { template: "جهاز {make} {model} بسعر {price}", subcategories: [] },
      { template: "{make} {model} متاح بسعر {price}", subcategories: [] },
      { template: "{make} {model} معروض بسعر {price}", subcategories: [] },
      { template: "{make} {model} جاهز بسعر {price}", subcategories: [] },
      { template: "عرض {make} {model} بسعر {price}", subcategories: [] },
      { template: "{make} {model} بسعر {price} للتسليم", subcategories: [] },
      { template: "{make} {model} بلون {color} بسعر {price}", subcategories: [] },
      { template: "{make} {model} لون {color} — {price}", subcategories: [] },
      { template: "{make} {model} بلون {color} مقابل {price}", subcategories: [] },
      { template: "{make} {model} بحالة {condition} بسعر {price}", subcategories: [] },
      { template: "{make} {model} بحالة {condition} — {price}", subcategories: [] },
      { template: "{make} {model} — {condition} بسعر {price}", subcategories: [] },
      { template: "{make} {model} ذاكرة {storage} بسعر {price}", subcategories: [] },
      { template: "{make} {model} بسعة {storage} — {price}", subcategories: [] },
      { template: "{make} {model} بذاكرة {storage} مقابل {price}", subcategories: [] },
      { template: "{make} {model} سعة {storage} بسعر {price}", subcategories: [] },
    ],
    hooks: [
      { template: "الرقم معروض بسعر {price} والنقل بعد التوثيق.", subcategories: ["numbers"] },
      { template: "سعر الرقم {price}، والإجراء يتم باسم المشتري.", subcategories: ["numbers"] },
      { template: "الرقم متاح مقابل {price} من غير وسيط.", subcategories: ["numbers"] },
      { template: "{make} {model} بسعر {price}.", subcategories: [] },
      { template: "{make} {model} بحالة {condition}.", subcategories: [] },
      { template: "{make} {model} بلون {color}.", subcategories: [] },
      { template: "{make} {model} بذاكرة {storage}.", subcategories: [] },
      { template: "{make} {model} جاهز للمعاينة.", subcategories: [] },
      { template: "جهاز مفحوص بسعر {price}.", subcategories: [] },
      { template: "{make} {model} ببطارية {battery}.", subcategories: [] },
      { template: "{make} {model} بضمان {warranty}.", subcategories: [] },
      { template: "{make} {model} من سنة {year}.", subcategories: [] },
      { template: "{make} {model} بشاشة {screen}.", subcategories: [] },
      { template: "{make} {model} بكاميرا {camera}.", subcategories: [] },
      { template: "السعر {price} بعد الفحص.", subcategories: [] },
    ],
    introParagraphs: [
      { template: "رقم جوال معروض بسعر {price}. النقل يتم بعد التوثيق وباسم المشتري.", subcategories: ["numbers"] },
      { template: "السعر المحدد للرقم {price}. الإجراء يُشرح قبل الاتفاق.", subcategories: ["numbers"] },
      { template: "{make} {model} متاح للمعاينة قبل الشراء.", subcategories: [] },
      { template: "{make} {model} بلون {color}.", subcategories: [] },
      { template: "{make} {model} بحالة {condition}.", subcategories: [] },
      { template: "{make} {model} بذاكرة {storage}.", subcategories: [] },
      { template: "{make} {model} من سنة {year}.", subcategories: [] },
      { template: "{make} {model} بضمان {warranty}.", subcategories: [] },
      { template: "الجهاز {model} معروض بسعر {price}.", subcategories: [] },
      { template: "{make} بسعر {price} للمعاينة.", subcategories: [] },
      { template: "{model} بسعر {price}.", subcategories: [] },
      { template: "{make} {model} مع {box}.", subcategories: [] },
      { template: "{make} {model} مع {charger}.", subcategories: [] },
      { template: "{make} {model} بشاشة {screen}.", subcategories: [] },
      { template: "{make} {model} بكاميرا {camera}.", subcategories: [] },
      { template: "{make} {model} ببطارية {battery}.", subcategories: [] },
      { template: "{make} {model} نسخة {region}.", subcategories: [] },
      { template: "{model} بلون {color} وجاهز للتجربة.", subcategories: [] },
      { template: "{model} بحالة {condition} وجاهز للتسليم.", subcategories: [] },
      { template: "{make} {model} مفحوص قبل العرض.", subcategories: [] },
    ],
    detailsGroups: [
      { fact: "make", variants: [
        { template: "• الشركة: {make}.", subcategories: [] },
        { template: "• الجهاز من صنع {make}.", subcategories: [] },
        { template: "• العلامة التجارية {make}.", subcategories: [] },
        { template: "• الصانع المسجّل {make}.", subcategories: [] },
        { template: "• الماركة الظاهرة على الجهاز {make}.", subcategories: [] },
      ]},
      { fact: "model", variants: [
        { template: "• الموديل: {model}.", subcategories: [] },
        { template: "• اسم الطراز {model}.", subcategories: [] },
        { template: "• الجهاز طراز {model}.", subcategories: [] },
        { template: "• الموديل المكتوب على الجهاز {model}.", subcategories: [] },
        { template: "• الطراز المعروض {model}.", subcategories: [] },
      ]},
      { fact: "color", variants: [
        { template: "• اللون: {color}.", subcategories: [] },
        { template: "• لون الهيكل {color}.", subcategories: [] },
        { template: "• اللون الظاهر في الصور {color}.", subcategories: [] },
        { template: "• الجهاز باللون {color}.", subcategories: [] },
        { template: "• تشطيب اللون {color}.", subcategories: [] },
      ]},
      { fact: "storage", variants: [
        { template: "• الذاكرة: {storage}.", subcategories: [] },
        { template: "• سعة التخزين {storage}.", subcategories: [] },
        { template: "• المساحة الداخلية {storage}.", subcategories: [] },
        { template: "• التخزين حسب المواصفة {storage}.", subcategories: [] },
        { template: "• سعة الجهاز {storage}.", subcategories: [] },
      ]},
      { fact: "condition", variants: [
        { template: "• الجهاز بحالة {condition}.", subcategories: [] },
        { template: "• وصف حالة الجهاز {condition}.", subcategories: [] },
        { template: "• حالة الجهاز عند المعاينة {condition}.", subcategories: [] },
        { template: "• الاستخدام الظاهر {condition}.", subcategories: [] },
        { template: "• الجهاز موصوف بأنه {condition}.", subcategories: [] },
      ]},
      { fact: "battery", variants: [
        { template: "• البطارية: {battery}.", subcategories: [] },
        { template: "• صحة البطارية {battery}.", subcategories: [] },
        { template: "• قراءة البطارية {battery}.", subcategories: [] },
        { template: "• نسبة البطارية المذكورة {battery}.", subcategories: [] },
        { template: "• البطارية حسب الفحص {battery}.", subcategories: [] },
      ]},
      { fact: "warranty", variants: [
        { template: "• الضمان: {warranty}.", subcategories: [] },
        { template: "• مدة الضمان {warranty}.", subcategories: [] },
        { template: "• الضمان المذكور {warranty}.", subcategories: [] },
        { template: "• تغطية الضمان {warranty}.", subcategories: [] },
        { template: "• وضع الضمان {warranty}.", subcategories: [] },
      ]},
      { fact: "region", variants: [
        { template: "• النسخة: {region}.", subcategories: [] },
        { template: "• إصدار المنطقة {region}.", subcategories: [] },
        { template: "• النسخة الإقليمية {region}.", subcategories: [] },
        { template: "• الجهاز نسخة {region}.", subcategories: [] },
        { template: "• السوق الأصلي للجهاز {region}.", subcategories: [] },
      ]},
      { fact: "year", variants: [
        { template: "• السنة: {year}.", subcategories: [] },
        { template: "• سنة الإصدار {year}.", subcategories: [] },
        { template: "• الجهاز من عام {year}.", subcategories: [] },
        { template: "• تاريخ الطرح {year}.", subcategories: [] },
        { template: "• سنة الصنع المذكورة {year}.", subcategories: [] },
      ]},
      { fact: "price", variants: [
        { template: "• السعر: {price}.", subcategories: [] },
        { template: "• السعر المطلوب {price}.", subcategories: [] },
        { template: "• القيمة المعروضة {price}.", subcategories: [] },
        { template: "• المبلغ المذكور {price}.", subcategories: [] },
        { template: "• سعر البيع {price}.", subcategories: [] },
      ]},
      { fact: "box", variants: [
        { template: "• العلبة: {box}.", subcategories: [] },
        { template: "• وضع العلبة {box}.", subcategories: [] },
        { template: "• الجهاز مع {box}.", subcategories: [] },
        { template: "• العلبة المرافقة {box}.", subcategories: [] },
        { template: "• حالة العلبة {box}.", subcategories: [] },
      ]},
      { fact: "charger", variants: [
        { template: "• الشاحن: {charger}.", subcategories: [] },
        { template: "• الشاحن المرافق {charger}.", subcategories: [] },
        { template: "• الجهاز يأتي مع {charger}.", subcategories: [] },
        { template: "• وضع الشاحن {charger}.", subcategories: [] },
        { template: "• الشاحن حسب الوصف {charger}.", subcategories: [] },
      ]},
    ],
    featuresBullets: [
      { template: "• السعر {price} محدد قبل نقل الرقم.", subcategories: ["numbers"] },
      { template: "• النقل يتم بعد التوثيق مقابل {price}.", subcategories: ["numbers"] },
      { template: "• لا وسيط في البيع والسعر {price}.", subcategories: ["numbers"] },
      { template: "• الرقم يُسجّل باسم المشتري بسعر {price}.", subcategories: ["numbers"] },
      { template: "• الإجراء يُشرح قبل الاتفاق على {price}.", subcategories: ["numbers"] },
      { template: "• البطارية مفحوصة قبل العرض.", subcategories: [] },
      { template: "• قراءة البطارية ظاهرة في الإعدادات.", subcategories: [] },
      { template: "• البطارية على {battery}.", subcategories: [] },
      { template: "• الشاشة بلا خط ظاهر عند الفحص.", subcategories: [] },
      { template: "• الشاشة بمقاس {screen}.", subcategories: [] },
      { template: "• اللمس يعمل على كامل الشاشة.", subcategories: [] },
      { template: "• الكاميرا تعمل في الوضعين.", subcategories: [] },
      { template: "• دقة الكاميرا {camera}.", subcategories: [] },
      { template: "• العدسة بلا كسر ظاهر.", subcategories: [] },
      { template: "• الأداء مستقر أثناء التجربة.", subcategories: [] },
      { template: "• الجهاز يفتح التطبيقات بلا تعليق ملحوظ.", subcategories: [] },
      { template: "• التشغيل سليم بعد الفحص.", subcategories: [] },
      { template: "• الهيكل بلا كسر ظاهر.", subcategories: [] },
      { template: "• الجهاز بلون {color} سليم في الأطراف.", subcategories: [] },
      { template: "• الأطراف والظهر سليمة.", subcategories: [] },
      { template: "• الضمان مذكور في الإعلان.", subcategories: [] },
      { template: "• مدة الضمان {warranty}.", subcategories: [] },
      { template: "• الجهاز أصلي وغير مجدّد.", subcategories: [] },
      { template: "• الفحص شمل الشاشة والبطارية.", subcategories: [] },
      { template: "• تم فحص الجهاز قبل العرض.", subcategories: [] },
      { template: "• العلبة مرافقة للجهاز.", subcategories: [] },
      { template: "• الشاحن ضمن الملحقات.", subcategories: [] },
      { template: "• الذاكرة {storage}.", subcategories: [] },
      { template: "• الجهاز بحالة {condition}.", subcategories: [] },
      { template: "• النسخة {region}.", subcategories: [] },
    ],
    ctas: [
      { template: "للتنسيق على نقل الرقم راسل صاحب الإعلان.", subcategories: ["numbers"] },
      { template: "للمعاينة والتوثيق تواصل عبر الرسائل.", subcategories: ["numbers"] },
      { template: "للمعاينة تواصل عبر رسائل الإعلان.", subcategories: [] },
      { template: "راسل البائع لتحديد موعد تجربة الجهاز.", subcategories: [] },
      { template: "اتصل بصاحب الإعلان قبل الحضور.", subcategories: [] },
      { template: "للتنسيق على السعر راسل الآن.", subcategories: [] },
      { template: "للاستفسار عن الضمان تواصل برسالة.", subcategories: [] },
      { template: "للمعاينة في مكان متفق عليه راسل المعلن.", subcategories: [] },
      { template: "اتصل لتأكيد التوفر قبل الزيارة.", subcategories: [] },
      { template: "للتنسيق على التسليم تواصل عبر الإعلان.", subcategories: [] },
      { template: "للمعاينة والفحص تواصل مع البائع.", subcategories: [] },
      { template: "اتصل للاستفسار عن النسخة {region}.", subcategories: [] },
      { template: "تواصل لتحديد موعد الاستلام.", subcategories: [] },
      { template: "راسل لتأكيد اللون {color}.", subcategories: [] },
      { template: "للتنسيق على السعة {storage} تواصل برسالة.", subcategories: [] },
    ],
    detailsLabel: "🔹 المواصفات:",
    featuresLabel: "🔹 أبرز المميزات:",
    featuresCount: 4,
    introCount: 2,
    minDetails: 1,
};
