import type { StructuredLayout } from '../types';

type SubPools = Pick<
  StructuredLayout,
  'subTitleFormat' | 'subHooks' | 'subIntroParagraphs' | 'subFeaturesBullets' | 'subCtas'
>;

export const MOBILES_SUB_POOLS: SubPools = {
subTitleFormat: {
      phones: [
        { template: "{make} {model} للاتصال بسعر {price}", subcategories: ["phones"] },
        { template: "{make} {model} للتصوير بسعر {price}", subcategories: ["phones"] },
        { template: "{make} {model} شاشة سليمة — {price}", subcategories: ["phones"] },
        { template: "{make} {model} كاميرا سليمة بسعر {price}", subcategories: ["phones"] },
        { template: "{make} {model} أصلي بسعر {price}", subcategories: ["phones"] },
        { template: "{make} {model} بضمان الوكيل — {price}", subcategories: ["phones"] },
        { template: "{make} {model} بذاكرة {storage} — {price}", subcategories: ["phones"] },
        { template: "{make} {model} لون {color} — {price}", subcategories: ["phones"] },
        { template: "{make} {model} بحالة {condition} — {price}", subcategories: ["phones"] },
        { template: "{make} {model} نسخة الوكيل بسعر {price}", subcategories: ["phones"] },
      ],
      tablets: [
        { template: "{make} {model} لوحي بسعر {price}", subcategories: ["tablets"] },
        { template: "{make} {model} بشاشة واسعة — {price}", subcategories: ["tablets"] },
        { template: "{make} {model} للدراسة بسعر {price}", subcategories: ["tablets"] },
        { template: "{make} {model} يدعم القلم — {price}", subcategories: ["tablets"] },
        { template: "{make} {model} واي فاي بسعر {price}", subcategories: ["tablets"] },
        { template: "{make} {model} للرسم بسعر {price}", subcategories: ["tablets"] },
        { template: "{make} {model} سعة {storage} — {price}", subcategories: ["tablets"] },
        { template: "{make} {model} لون {color} — {price}", subcategories: ["tablets"] },
        { template: "{make} {model} بحالة {condition} — {price}", subcategories: ["tablets"] },
        { template: "{make} {model} للتصفح بسعر {price}", subcategories: ["tablets"] },
      ],
      "smart-watches": [
        { template: "{make} {model} ساعة ذكية — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} بسوار رياضي — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} لتتبع النوم بسعر {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} لقياس النبض — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} للرياضة بسعر {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} شاشة معصم — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} لون {color} — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} بحالة {condition} — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} سوار قابل للتبديل — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} للمعصم بسعر {price}", subcategories: ["smart-watches"] },
      ],
      accessories: [
        { template: "ملحق {make} {model} بسعر {price}", subcategories: ["accessories"] },
        { template: "إكسسوار {make} {model} — {price}", subcategories: ["accessories"] },
        { template: "قطعة {make} {model} بسعر {price}", subcategories: ["accessories"] },
        { template: "{make} {model} مع التغليف — {price}", subcategories: ["accessories"] },
        { template: "{make} {model} أصلي ملحق — {price}", subcategories: ["accessories"] },
        { template: "{make} {model} لون {color} — {price}", subcategories: ["accessories"] },
        { template: "{make} {model} بحالة {condition} — {price}", subcategories: ["accessories"] },
        { template: "قطعة {make} {model} متوافقة — {price}", subcategories: ["accessories"] },
      ],
    },
    subHooks: {
      phones: [
        { template: "{make} {model} للاتصال والتصوير.", subcategories: ["phones"] },
        { template: "{make} {model} بذاكرة {storage}.", subcategories: ["phones"] },
        { template: "{make} {model} بكاميرا {camera}.", subcategories: ["phones"] },
        { template: "{make} {model} بضمان {warranty}.", subcategories: ["phones"] },
        { template: "هاتف مفحوص بسعر {price}.", subcategories: ["phones"] },
        { template: "{make} {model} نسخة {region}.", subcategories: ["phones"] },
      ],
      tablets: [
        { template: "{make} {model} للتصفح والدراسة.", subcategories: ["tablets"] },
        { template: "{make} {model} بشاشة {screen}.", subcategories: ["tablets"] },
        { template: "{make} {model} بسعة {storage}.", subcategories: ["tablets"] },
        { template: "{make} {model} يدعم القلم.", subcategories: ["tablets"] },
        { template: "جهاز لوحي بسعر {price}.", subcategories: ["tablets"] },
        { template: "{make} {model} باتصال واي فاي.", subcategories: ["tablets"] },
      ],
      "smart-watches": [
        { template: "{make} {model} للمعصم والرياضة.", subcategories: ["smart-watches"] },
        { template: "{make} {model} بسوار {color}.", subcategories: ["smart-watches"] },
        { template: "{make} {model} ببطارية {battery}.", subcategories: ["smart-watches"] },
        { template: "{make} {model} لتتبع النوم.", subcategories: ["smart-watches"] },
        { template: "ساعة مفحوصة بسعر {price}.", subcategories: ["smart-watches"] },
        { template: "{make} {model} بشاشة {screen}.", subcategories: ["smart-watches"] },
      ],
      accessories: [
        { template: "ملحق {make} {model} جاهز للتركيب.", subcategories: ["accessories"] },
        { template: "قطعة متوافقة بسعر {price}.", subcategories: ["accessories"] },
        { template: "{make} {model} مع التغليف.", subcategories: ["accessories"] },
        { template: "{make} {model} بلون {color}.", subcategories: ["accessories"] },
      ],
    },
    subIntroParagraphs: {
      phones: [
        { template: "{make} {model} مناسب للاتصال اليومي.", subcategories: ["phones"] },
        { template: "{make} {model} بذاكرة {storage}.", subcategories: ["phones"] },
        { template: "{make} {model} بكاميرا {camera}.", subcategories: ["phones"] },
        { template: "{make} {model} بضمان {warranty}.", subcategories: ["phones"] },
        { template: "{make} {model} نسخة {region}.", subcategories: ["phones"] },
        { template: "الهاتف {model} معروض بسعر {price}.", subcategories: ["phones"] },
        { template: "{make} {model} ببطارية {battery}.", subcategories: ["phones"] },
        { template: "{model} بحالة {condition} وجاهز للتجربة.", subcategories: ["phones"] },
      ],
      tablets: [
        { template: "{make} {model} مناسب للدراسة والتصفح.", subcategories: ["tablets"] },
        { template: "{make} {model} بشاشة {screen}.", subcategories: ["tablets"] },
        { template: "{make} {model} بسعة {storage}.", subcategories: ["tablets"] },
        { template: "{make} {model} يدعم القلم حسب الوصف.", subcategories: ["tablets"] },
        { template: "اللوحي {model} معروض بسعر {price}.", subcategories: ["tablets"] },
        { template: "{make} {model} باتصال واي فاي.", subcategories: ["tablets"] },
        { template: "{model} بلون {color} وجاهز للاستخدام.", subcategories: ["tablets"] },
        { template: "{make} {model} مع {charger}.", subcategories: ["tablets"] },
      ],
      "smart-watches": [
        { template: "{make} {model} مناسبة للمعصم.", subcategories: ["smart-watches"] },
        { template: "{make} {model} لتتبع النوم حسب الوصف.", subcategories: ["smart-watches"] },
        { template: "{make} {model} ببطارية {battery}.", subcategories: ["smart-watches"] },
        { template: "{make} {model} بشاشة {screen}.", subcategories: ["smart-watches"] },
        { template: "الساعة {model} معروضة بسعر {price}.", subcategories: ["smart-watches"] },
        { template: "{make} {model} بسوار {color}.", subcategories: ["smart-watches"] },
        { template: "{model} بحالة {condition} وجاهزة للتجربة.", subcategories: ["smart-watches"] },
        { template: "{make} {model} مع {box}.", subcategories: ["smart-watches"] },
      ],
      accessories: [
        { template: "ملحق {make} {model} جاهز للتركيب.", subcategories: ["accessories"] },
        { template: "القطعة {model} معروضة بسعر {price}.", subcategories: ["accessories"] },
        { template: "{make} {model} مع التغليف.", subcategories: ["accessories"] },
        { template: "{make} {model} بلون {color}.", subcategories: ["accessories"] },
        { template: "{model} بحالة {condition} وسليم للتسليم.", subcategories: ["accessories"] },
      ],
    },
    subFeaturesBullets: {
      phones: [
        { template: "• الكاميرا تعمل في الوضعين.", subcategories: ["phones"] },
        { template: "• دقة الكاميرا {camera}.", subcategories: ["phones"] },
        { template: "• البطارية مفحوصة قبل العرض.", subcategories: ["phones"] },
        { template: "• قراءة البطارية {battery}.", subcategories: ["phones"] },
        { template: "• الشاشة بلا خط ظاهر.", subcategories: ["phones"] },
        { template: "• الشاشة بمقاس {screen}.", subcategories: ["phones"] },
        { template: "• الذاكرة {storage}.", subcategories: ["phones"] },
        { template: "• النسخة {region}.", subcategories: ["phones"] },
        { template: "• الضمان {warranty}.", subcategories: ["phones"] },
        { template: "• القطع أصلية حسب الوصف.", subcategories: ["phones"] },
        { template: "• الاتصال والشبكة سليمين عند الفحص.", subcategories: ["phones"] },
        { template: "• الجهاز بحالة {condition}.", subcategories: ["phones"] },
      ],
      tablets: [
        { template: "• الشاشة واسعة للتصفح.", subcategories: ["tablets"] },
        { template: "• مقاس الشاشة {screen}.", subcategories: ["tablets"] },
        { template: "• السعة {storage}.", subcategories: ["tablets"] },
        { template: "• يدعم القلم حسب الوصف.", subcategories: ["tablets"] },
        { template: "• الاتصال عبر الواي فاي.", subcategories: ["tablets"] },
        { template: "• مناسب للدراسة والملاحظات.", subcategories: ["tablets"] },
        { template: "• الشاشة بلا خط ظاهر.", subcategories: ["tablets"] },
        { template: "• الشاحن {charger}.", subcategories: ["tablets"] },
        { template: "• الجهاز بحالة {condition}.", subcategories: ["tablets"] },
        { template: "• اللون {color}.", subcategories: ["tablets"] },
        { template: "• الهيكل بلا كسر ظاهر.", subcategories: ["tablets"] },
        { template: "• التشغيل سليم بعد الفحص.", subcategories: ["tablets"] },
      ],
      "smart-watches": [
        { template: "• السوار قابل للتبديل.", subcategories: ["smart-watches"] },
        { template: "• لون السوار {color}.", subcategories: ["smart-watches"] },
        { template: "• تتبع النبض مذكور في الوصف.", subcategories: ["smart-watches"] },
        { template: "• تتبع النوم مذكور في الوصف.", subcategories: ["smart-watches"] },
        { template: "• البطارية {battery}.", subcategories: ["smart-watches"] },
        { template: "• شاشة المعصم {screen}.", subcategories: ["smart-watches"] },
        { template: "• الساعة بحالة {condition}.", subcategories: ["smart-watches"] },
        { template: "• الشحن يتم عبر {charger}.", subcategories: ["smart-watches"] },
        { template: "• العلبة {box}.", subcategories: ["smart-watches"] },
        { template: "• المعصم يُقاس قبل الشراء.", subcategories: ["smart-watches"] },
        { template: "• الهيكل بلا خدش ظاهر.", subcategories: ["smart-watches"] },
        { template: "• الإشعارات تعمل حسب الفحص.", subcategories: ["smart-watches"] },
      ],
      accessories: [
        { template: "• القطعة متوافقة مع {make}.", subcategories: ["accessories"] },
        { template: "• التغليف {box}.", subcategories: ["accessories"] },
        { template: "• اللون {color}.", subcategories: ["accessories"] },
        { template: "• القطعة بحالة {condition}.", subcategories: ["accessories"] },
        { template: "• أصلية أو تجارية حسب الوصف.", subcategories: ["accessories"] },
        { template: "• الخامة سليمة عند المعاينة.", subcategories: ["accessories"] },
        { template: "• التركيب مباشر بلا تعديل.", subcategories: ["accessories"] },
        { template: "• السعر {price} للقطعة كما هي.", subcategories: ["accessories"] },
      ],
    },
    subCtas: {
      phones: [
        { template: "للمعاينة وتجربة الكاميرا تواصل عبر الرسائل.", subcategories: ["phones"] },
        { template: "راسل لتأكيد قراءة البطارية قبل الحضور.", subcategories: ["phones"] },
        { template: "اتصل للاستفسار عن نسخة {region}.", subcategories: ["phones"] },
        { template: "للتنسيق على سعة {storage} راسل المعلن.", subcategories: ["phones"] },
      ],
      tablets: [
        { template: "للمعاينة وتجربة الشاشة تواصل عبر الرسائل.", subcategories: ["tablets"] },
        { template: "راسل لتأكيد دعم القلم قبل الزيارة.", subcategories: ["tablets"] },
        { template: "اتصل للاستفسار عن سعة {storage}.", subcategories: ["tablets"] },
        { template: "للتنسيق على مقاس {screen} تواصل برسالة.", subcategories: ["tablets"] },
      ],
      "smart-watches": [
        { template: "للمعاينة على المعصم تواصل عبر الرسائل.", subcategories: ["smart-watches"] },
        { template: "راسل لتأكيد مقاس السوار قبل الحضور.", subcategories: ["smart-watches"] },
        { template: "اتصل للاستفسار عن بطارية {battery}.", subcategories: ["smart-watches"] },
        { template: "للتنسيق على لون {color} راسل المعلن.", subcategories: ["smart-watches"] },
      ],
      accessories: [
        { template: "للمعاينة والتوافق تواصل عبر الرسائل.", subcategories: ["accessories"] },
        { template: "راسل لتأكيد التوافق مع {make}.", subcategories: ["accessories"] },
        { template: "اتصل قبل الحضور لتأكيد توفر القطعة.", subcategories: ["accessories"] },
      ],
    },
};
