import type { StructuredLayout } from '../types';

type GenericPool = Omit<
  StructuredLayout,
  'subTitleFormat' | 'subHooks' | 'subIntroParagraphs' | 'subFeaturesBullets' | 'subCtas'
>;

export const REAL_ESTATE_GENERIC_POOLS: GenericPool = {
  titleFormat: [
    { template: 'شقة {rooms} غرف و{area} م² — سكن جاهز', subcategories: ['apartments'] },
    { template: '{rooms} غرف ضمن وحدة بمساحة {area} م²', subcategories: [] },
    { template: 'وحدة سكنية {area} م² — {rooms} غرف', subcategories: [] },
    { template: 'عقار {rooms} غرف على {area} م²', subcategories: [] },
    { template: 'مساحة {area} م² بـ{rooms} غرف', subcategories: [] },
    { template: '{rooms} غرف و{bathrooms} حمامات ضمن {area} م²', subcategories: [] },
    { template: 'وحدة بـ{rooms} غرف و{bathrooms} حمامات', subcategories: [] },
    { template: 'عقار {area} م² — {rooms} غرف و{bathrooms} حمامات', subcategories: [] },
    { template: 'سكن {rooms} غرف بمساحة {area} م²', subcategories: [] },
    { template: '{area} م² — {rooms} غرف و{bathrooms} حمامات', subcategories: [] },
    { template: 'وحدة سكنية بمساحة {area} م²', subcategories: [] },
    { template: 'عقار {rooms} غرف — {area} م²', subcategories: [] },
    { template: 'شقة {area} م² بـ{rooms} غرف', subcategories: ['apartments'] },
    { template: 'سكن عائلي {rooms} غرف — {area} م²', subcategories: [] },
    { template: 'وحدة {rooms} غرف على {area} م²', subcategories: [] },
    { template: '{rooms} غرف و{bathrooms} حمامات في {area} م²', subcategories: [] },
    { template: 'عقار عائلي {area} م² — {rooms} غرف نوم', subcategories: [] },
    { template: 'وحدة جاهزة: {rooms} غرف و{area} م²', subcategories: [] },
    { template: 'سكن مودرن {rooms} غرف بمساحة {area} م²', subcategories: [] },
    { template: 'مساحة واسعة {area} م² لـ{rooms} غرف', subcategories: [] },
    { template: 'شقة {rooms} غرف بمساحة {area} م²', subcategories: ['apartments'] },
    { template: 'وحدة {area} م² — {rooms} غرف', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'شقة {rooms} غرف للبيع بسعر {price}', subcategories: ['apartments'] },
    { template: 'منزل {rooms} غرف على {area} م²', subcategories: ['houses'] },
    { template: 'عقار {area} م² بسعر {price}', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'شقة {rooms} غرف بحالة {condition} — {price}', subcategories: ['apartments'] },
    { template: 'وحدة {rooms} غرف — السعر {price}', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'طابق {floor}: {area} م² بسعر {price}', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: '{rooms} غرف نوم ضمن {area} م²', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'سكن {rooms} غرف بسعر {price}', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'مساحة {area} م² تضم {rooms} غرف', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'شقة بحالة {condition} — {rooms} غرف و{area} م²', subcategories: ['apartments'] },
    { template: 'بيع {rooms} غرف بمساحة {area} م²', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'وحدة بسعر {price} — {rooms} غرف', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'عقار {rooms} غرف بسعر {price}', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'طابق {floor} وفيه {rooms} غرف — {price}', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'شقة {area} م² للبيع بسعر {price}', subcategories: ['apartments'] },
    { template: '{rooms} غرف بحالة {condition} — {price}', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'منزل {area} م² بسعر {price}', subcategories: ['houses'] },
    { template: 'وحدة سكنية {rooms} غرف و{area} م²', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'عرض {rooms} غرف على {area} م²', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'شقة بسعر {price} ومساحة {area} م²', subcategories: ['apartments'] },
    { template: 'طابق {floor} — {rooms} غرف بسعر {price}', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'عقار بحالة {condition} — {rooms} غرف و{area} م²', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'سكن عائلي {rooms} غرف — {price}', subcategories: ['apartments', 'houses', 'chalets'] },
  ],
  hooks: [
    { template: 'وحدة بـ{rooms} غرف و{area} م² جاهزة للسكن.', subcategories: [] },
    { template: 'عقار من {rooms} غرف و{bathrooms} حمامات ضمن {area} م².', subcategories: [] },
    { template: 'مساحة {area} م² و{rooms} غرف في موقع هادئ.', subcategories: [] },
    { template: 'سكن عائلي بـ{rooms} غرف و{area} م².', subcategories: [] },
    { template: 'وحدة {area} م² تكفي لعائلة تحتاج {rooms} غرف.', subcategories: [] },
    { template: 'عقار {rooms} غرف و{bathrooms} حمامات — جاهز للمعاينة.', subcategories: [] },
    { template: 'وحدة سكنية بـ{rooms} غرف على {area} م².', subcategories: [] },
    { template: 'وحدة بـ{rooms} غرف و{bathrooms} حمامات جاهزة للمعاينة.', subcategories: [] },
    { template: 'فرصة سكن مريح لعائلة تحتاج {rooms} غرف بتوزيع عملي.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'مساحة {area} م² تمنح اتساعاً يومياً دون هدر في الحركة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'سعر {price} يفتح باب التملك لوحدة جاهزة للاستخدام.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '{rooms} غرف تكفي لفصل النوم عن المعيشة بهدوء.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'بمساحة {area} م² تحصل على راحة حقيقية لا مجرد رقم.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'بقيمة {price} تدخل إلى سكن مرتب وجاهز للانتقال.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'توزيع {rooms} غرف يخفف الازدحام ويمنح كل فرد زاويته.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'مساحة {area} م² بإضاءة طبيعية تجعل اليوم أهدأ.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'سعر {price} مناسب لمن يريد سكناً مستقراً أو أصلاً واضحاً.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: '{rooms} غرف بحالة {condition} تختصر كلفة التجهيز.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'مساحة {area} م² على الطابق {floor} لخصوصية أهدأ.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'تملك {rooms} غرف اليوم يعني روتيناً عائلياً أريح.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: '{price} مقابل وحدة يمكن السكن فيها دون انتظار طويل.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'مساحة {area} م² تكفي لاستقبال العائلة دون شعور بالضيق.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: '{rooms} غرف بتشطيب {condition} توفر وقت التعديل بعد الشراء.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
  ],
  introParagraphs: [
    { template: 'نضع بين أيديكم وحدة من {rooms} غرف بمساحة {area} م²، بتصميم يراعي الراحة اليومية والخصوصية.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'شقة {rooms} غرف بسعر {price}، مناسبة لسكن عائلي هادئ أو لاستثمار واضح المعالم.', subcategories: ['apartments'] },
    { template: 'تأتي هذه الوحدة بمساحة {area} م² وسعر {price}، مع توزيع داخلي يخفف الحركة الزائدة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'منزل من {rooms} غرف على {area} م²، يمنح استقلالية أكبر وروتين سكن أهدأ.', subcategories: ['houses'] },
    { template: 'وحدة {rooms} غرف بحالة {condition}، جاهزة لتقليل أعمال التجهيز قبل الانتقال.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'على الطابق {floor} تقع شقة {rooms} غرف، بتهوية جيدة وإحساس أوضح بالخصوصية.', subcategories: ['apartments'] },
    { template: 'بمساحة {area} م² وسعر {price}، تناسب من يبحث عن توازن بين الاتساع وكلفة التملك.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'سكن من {rooms} غرف بحالة {condition}، يفصل النوم عن المعيشة بطريقة مريحة.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'وحدة {area} م² على الطابق {floor}، مناسبة لسكن يومي هادئ مع سهولة الحركة.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'شقة {rooms} غرف بسعر {price}، بتشطيب عملي يختصر وقت الاستلام.', subcategories: ['apartments'] },
    { template: 'عقار من {rooms} غرف ضمن {area} م²، يمنح العائلة زاوية مستقلة لكل فرد.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'بسعر {price} ومساحة {area} م²، تدخل إلى وحدة يمكن تقييمها بوضوح قبل القرار.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'منزل {rooms} غرف بحالة {condition}، يوفّر استقلالية وخصوصية أعلى من السكن المشترك.', subcategories: ['houses'] },
    { template: 'تقع الوحدة على الطابق {floor} بمساحة {area} م²، مع إضاءة نهارية مريحة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'شقة {rooms} غرف على الطابق {floor}، مناسبة لعائلة تريد هدوءاً دون عزلة.', subcategories: ['apartments'] },
    { template: 'وحدة {area} م² من {rooms} غرف، بتوزيع يساعد على استقبال الضيوف دون إزعاج النوم.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'بسعر {price} تحصل على سكن من {rooms} غرف جاهز لحياة يومية منظمة.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: 'عقار بحالة {condition} ومساحة {area} م²، يقلل الحاجة إلى تعديل واسع بعد الشراء.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'منزل بمساحة {area} م² وسعر {price}، يمنح حرية أكبر في الاستخدام اليومي.', subcategories: ['houses'] },
    { template: 'شقة {rooms} غرف بحالة {condition} — {price}، مصممة لراحة العائلة لا لمجرد زيادة العدد.', subcategories: ['apartments'] },
  ],
  detailsGroups: [
    { fact: 'rooms', variants: [
      { template: '• عدد غرف النوم: {rooms} غرف نوم واسعة ومضيئة.', subcategories: ['apartments', 'houses', 'chalets'] },
      { template: '• {rooms} غرف بتوزيع مريح وإضاءة طبيعية.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• غرف النوم: {rooms}، تفصل الراحة عن حركة المعيشة.', subcategories: ['apartments', 'houses', 'chalets'] },
      { template: '• يتضمن العقار {rooms} غرف نوم عملية للعائلات.', subcategories: ['apartments', 'houses', 'chalets'] },
      { template: '• {rooms} غرف نوم تمنح كل فرد مساحته بهدوء.', subcategories: ['apartments', 'houses', 'chalets'] },
    ]},
    { fact: 'bathrooms', variants: [
      { template: '• عدد الحمامات: {bathrooms} حمامات بتشطيبات حديثة وعملية.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• {bathrooms} حمامات تسهّل الاستخدام الصباحي للعائلة.', subcategories: ['apartments', 'houses', 'chalets'] },
      { template: '• الحمامات: {bathrooms}، بتوزيع يخفف الانتظار.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• {bathrooms} حمامات بتشطيب واضح وسهل العناية.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• تتوفر {bathrooms} حمامات لراحة أكبر في الاستخدام اليومي.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    ]},
    { fact: 'area', variants: [
      { template: '• المساحة: {area} م² تمنح شعوراً بالاتساع.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• تمتد الوحدة على {area} م² بتوزيع مريح.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• المساحة الإجمالية {area} م²، كافية لحركة عائلية هادئة.', subcategories: ['apartments', 'houses', 'chalets', 'lands'] },
      { template: '• {area} م² مستغلة بطريقة تقلل الزوايا الضائعة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• مساحة {area} م² تناسب السكن اليومي والاستقبال.', subcategories: ['apartments', 'houses', 'chalets'] },
    ]},
    { fact: 'floor', variants: [
      { template: '• الطابق: {floor}، بوصول أسهل وخصوصية أوضح.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• تقع الوحدة في الطابق {floor}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• الطابق {floor} يمنح تهوية مريحة وابتعاداً عن الضجيج الأرضي.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• الموقع داخل المبنى: الطابق {floor}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• على الطابق {floor}، مع حركة دخول عملية.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    ]},
    { fact: 'price', variants: [
      { template: '• السعر: {price}، واضح قبل المعاينة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• قيمة البيع {price}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• السعر المطلوب {price}، مناسب للمقارنة الهادئة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• يُعرض بسعر {price}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• سعر التملك {price} دون غموض في الرقم.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    ]},
    { fact: 'condition', variants: [
      { template: '• حالة العقار: {condition}، ما يقلل أعمال التجهيز.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• التشطيب بحالة {condition} وجاهز للمعاينة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• الوحدة بحالة {condition}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• حالة البناء والتشطيب: {condition}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• تُعرض بحالة {condition} لتقييم أوضح قبل القرار.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    ]},
    { fact: 'living', variants: [
      { template: '• المعيشة: {living}، مريحة لاستقبال العائلة.', subcategories: ['apartments', 'houses', 'chalets'] },
      { template: '• منطقة المعيشة {living} بتهوية جيدة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• الصالون والمعيشة: {living}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• جلسة عائلية {living} منفصلة عن غرف النوم.', subcategories: ['apartments', 'houses', 'chalets'] },
      { template: '• المعيشة {living} تمنح اتساعاً في الاستخدام اليومي.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    ]},
    { fact: 'balcony', variants: [
      { template: '• البلكونة: {balcony}، بتهوية وإطلالة مريحة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• تتوفر بلكونة {balcony}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• ملحق خارجي {balcony} يمدّ الوحدة بهواء طبيعي.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• البلكونة {balcony} مناسبة لجلسة هادئة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• مساحة خارجية {balcony} تخفف انغلاق الغرف.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    ]},
    { fact: 'parking', variants: [
      { template: '• موقف السيارات: {parking}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• يتوفر موقف {parking} لسهولة الوصول.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• وقوف السيارات: {parking}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• موقف {parking} يقلل عناء البحث اليومي.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• مرفق الوقوف {parking}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    ]},
    { fact: 'view', variants: [
      { template: '• الإطلالة: {view}، تمنح هدوءاً بصرياً.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• تطل الوحدة على {view}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• الإطلالة {view}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• مشهد {view} يرفع إحساس الاتساع.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• الواجهة نحو {view}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    ]},
    { fact: 'year', variants: [
      { template: '• سنة البناء: {year}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• أُنجز العقار عام {year}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• تاريخ الإنشاء: {year}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• البناء يعود إلى سنة {year}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
      { template: '• سنة التسليم أو البناء: {year}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    ]},
    { fact: 'furnished', variants: [
      { template: '• التأثيث: {furnished}، ما يختصر التجهيز.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• حالة الفرش: {furnished}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• الوحدة {furnished}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• التأثيث الحالي {furnished}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
      { template: '• تُعرض وهي {furnished} لتقييم أسرع.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    ]},
  ],
  featuresBullets: [
    { template: '• توزيع داخلي ذكي يمنح شعوراً بالاتساع.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• إضاءة طبيعية خلال النهار تقلل الحاجة للإضاءة الصناعية.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• تشطيبات عملية جاهزة للسكن دون انتظار طويل.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: '• فصل واضح بين النوم والمعيشة لخصوصية أفضل.', subcategories: ['apartments', 'houses', 'chalets', 'lands'] },
    { template: '• تهوية جيدة تجعل الإقامة اليومية أريح.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• مدخل منظم يسهّل الاستقبال دون إزعاج الغرف.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: '• مساحة حركة مريحة للعائلات.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• تشطيب واضح يسهّل تقييم العقار قبل الشراء.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• زاوية معيشة هادئة بعيدة عن غرف النوم.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: '• تصميم يقلل الممرات الضائعة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• مناسبة للسكن الفوري بعد الاتفاق.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: '• خصوصية أعلى داخل الوحدة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• سهولة العناية بالتشطيبات في الاستخدام اليومي.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• توازن بين الاتساع وكلفة التشغيل.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• جلسة عائلية مريحة دون ازدحام بصري.', subcategories: ['apartments', 'houses', 'chalets', 'lands'] },
    { template: '• وصول عملي من المدخل إلى الغرف.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: '• إطلالة داخلية هادئة تزيد الراحة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• مرونة في الاستخدام بين السكن والاستثمار.', subcategories: ['apartments', 'houses', 'chalets'] },
    { template: '• عزل إحساس الضجيج عن منطقة النوم.', subcategories: ['apartments', 'houses', 'chalets', 'lands'] },
    { template: '• توزيع يساعد على استقبال الضيوف بهدوء.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• تشطيب بحالة {condition} يختصر التعديل.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: '• بلكونة {balcony} تمدّ الوحدة بهواء طبيعي.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: '• موقف {parking} يخفف عناء الوقوف اليومي.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: '• إطلالة {view} تمنح هدوءاً بصرياً.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• معيشة {living} منفصلة عن غرف الراحة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: '• جاهزية {furnished} تختصر التجهيز بعد الشراء.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: '• طابق {floor} يوازن بين الوصول والخصوصية.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: '• مساحة {area} م² مستغلة دون زوايا مهملة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• سعر {price} واضح للمقارنة قبل المعاينة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: '• {rooms} غرف تكفي لفصل روتين كل فرد.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
  ],
  ctas: [
    { template: 'للاستفسار والمعاينة، تواصل معنا.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'راسلنا لتنسيق زيارة هادئة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'اتصل بنا لترتيب المعاينة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'للمعاينة، اترك بياناتك ونتواصل معك.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'احجز معاينة في وقت يناسبك.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'تواصل اليوم لمعرفة التفاصيل المتبقية.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'للتنسيق، راسلنا وحدد الموعد المناسب.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'اتصل للاستفسار عن السعر {price}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'احجز معاينة لوحدة من {rooms} غرف.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'راسلنا لمراجعة مساحة {area} م² على الطبيعة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'للمعاينة على الطابق {floor}، تواصل معنا.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'تواصل لتنسيق زيارة وتقييم حالة العقار {condition}.', subcategories: ['apartments', 'houses', 'chalets', 'commercial'] },
    { template: 'اتصل بنا إن رغبت بمعاينة هادئة.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'للتنسيق الفوري، راسلنا الآن.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
    { template: 'احجز موعد معاينة قبل اتخاذ القرار.', subcategories: ['apartments', 'houses', 'chalets', 'commercial', 'lands'] },
  ],
  detailsLabel: '🔹 تفاصيل الوحدة:',
  featuresLabel: '🔹 أبرز المميزات:',
  featuresCount: 4,
  introCount: 2,
  minDetails: 2,
};
