import type { StructuredLayout } from '../types';

type GenericPool = Omit<
  StructuredLayout,
  'subTitleFormat' | 'subHooks' | 'subIntroParagraphs' | 'subFeaturesBullets' | 'subCtas'
>;

export const REAL_ESTATE_GENERIC_POOLS: GenericPool = {
  titleFormat: [
    { template: 'شقة {rooms} غرف و{area} م²', subcategories: [] },
    { template: 'عقار {area} م² بـ{rooms} غرف', subcategories: [] },
    { template: 'سكن {rooms} غرف و{bathrooms} حمامات', subcategories: [] },
    { template: 'وحدة سكنية — {rooms} غرف و{area} م²', subcategories: [] },
    { template: 'عقار {rooms} غرف على {area} م²', subcategories: [] },
    { template: 'شقة {rooms} غرف بحالة {condition}', subcategories: [] },
    { template: 'وحدة {area} م² بـ{rooms} غرف و{bathrooms} حمامات', subcategories: [] },
    { template: 'عقار {rooms} غرف و{bathrooms} حمامات', subcategories: [] },
    { template: 'سكن {area} م² — {rooms} غرف', subcategories: [] },
    { template: 'شقة {rooms} غرف للبيع', subcategories: [] },
    { template: 'شقة {rooms} غرف بسعر {price}', subcategories: [] },
    { template: 'وحدة {rooms} غرف مقابل {price}', subcategories: [] },
    { template: 'عقار {rooms} غرف — {price}', subcategories: [] },
    { template: 'سكن {rooms} غرف بسعر {price}', subcategories: [] },
    { template: '{rooms} غرف للبيع بسعر {price}', subcategories: [] },
    { template: 'عقار بمساحة {area} م² بسعر {price}', subcategories: [] },
    { template: 'وحدة {area} م² مقابل {price}', subcategories: [] },
    { template: 'مساحة {area} م² — {price}', subcategories: [] },
    { template: 'عقار {area} م² للبيع بسعر {price}', subcategories: [] },
    { template: 'وحدة بمساحة {area} م² بسعر {price}', subcategories: [] },
    { template: 'شقة {rooms} غرف — {area} م² — {price}', subcategories: [] },
    { template: '{rooms} غرف على {area} م² بسعر {price}', subcategories: [] },
    { template: 'عقار {rooms} غرف ومساحة {area} م² — {price}', subcategories: [] },
    { template: 'وحدة {area} م² بـ{rooms} غرف بسعر {price}', subcategories: [] },
    { template: 'سكن {rooms} غرف و{area} م² مقابل {price}', subcategories: [] },
    { template: 'شقة {rooms} غرف في الطابق {floor} — {price}', subcategories: [] },
    { template: 'وحدة {rooms} غرف طابق {floor} بسعر {price}', subcategories: [] },
    { template: 'عقار {area} م² على الطابق {floor} — {price}', subcategories: [] },
    { template: 'شقة {rooms} غرف بحالة {condition} — {price}', subcategories: [] },
    { template: 'وحدة {area} م² بحالة {condition} بسعر {price}', subcategories: [] },
    { template: 'عقار {rooms} غرف جاهز بسعر {price}', subcategories: [] },
    { template: 'وحدة {area} م² جاهزة مقابل {price}', subcategories: [] },
    { template: 'بيع {rooms} غرف بسعر {price}', subcategories: [] },
    { template: 'عرض مساحة {area} م² بسعر {price}', subcategories: [] },
    { template: 'عقار {rooms} غرف للمعاينة — {price}', subcategories: [] },
  ],
  hooks: [
    { template: 'وحدة بـ{rooms} غرف و{area} م².', subcategories: [] },
    { template: 'عقار بـ{rooms} غرف و{bathrooms} حمامات.', subcategories: [] },
    { template: 'مساحة {area} م² بـ{rooms} غرف.', subcategories: [] },
    { template: 'سكن {rooms} غرف بحالة {condition}.', subcategories: [] },
    { template: 'عقار {area} م² جاهز للمعاينة.', subcategories: [] },
    { template: 'وحدة {rooms} غرف و{bathrooms} حمامات.', subcategories: [] },
    { template: 'الوحدة معروضة بسعر {price}.', subcategories: [] },
    { template: 'السعر المطلوب {price}.', subcategories: [] },
    { template: 'عقار بـ{rooms} غرف جاهز للمعاينة.', subcategories: [] },
    { template: 'المساحة {area} م².', subcategories: [] },
    { template: 'وحدة بمساحة {area} م² بسعر {price}.', subcategories: [] },
    { template: '{rooms} غرف في عقار بحالة {condition}.', subcategories: [] },
    { template: 'عقار على الطابق {floor} بسعر {price}.', subcategories: [] },
    { template: 'المساحة {area} م² والطابق {floor}.', subcategories: [] },
    { template: 'سكن بـ{rooms} غرف.', subcategories: [] },
    { template: 'السعر {price} بعد المعاينة.', subcategories: [] },
    { template: 'وحدة {area} م² جاهزة للزيارة.', subcategories: [] },
    { template: '{rooms} غرف بسعر {price}.', subcategories: [] },
    { template: 'عقار بمساحة {area} م².', subcategories: [] },
    { template: 'الوحدة بحالة {condition} والسعر {price}.', subcategories: [] },
    { template: 'عقار بـ{rooms} غرف على الطابق {floor}.', subcategories: [] },
  ],
  introParagraphs: [
    { template: 'الوحدة فيها {rooms} غرف. السعر {price}.', subcategories: [] },
    { template: 'المساحة {area} م² والسعر {price}.', subcategories: [] },
    { template: 'عقار بـ{rooms} غرف و{bathrooms} حمامات.', subcategories: [] },
    { template: 'المساحة {area} م² وفيها {rooms} غرف.', subcategories: [] },
    { template: 'الوحدة على الطابق {floor} بسعر {price}.', subcategories: [] },
    { template: 'عقار بمساحة {area} م² على الطابق {floor}.', subcategories: [] },
    { template: 'الوحدة بحالة {condition} وبـ{rooms} غرف.', subcategories: [] },
    { template: 'المساحة {area} م² والعقار بحالة {condition}.', subcategories: [] },
    { template: 'السعر {price} لعقار فيه {bathrooms} حمامات.', subcategories: [] },
    { template: '{rooms} غرف والحمامات {bathrooms}.', subcategories: [] },
    { template: 'عقار بمساحة {area} م² جاهز للمعاينة.', subcategories: [] },
    { template: 'وحدة بـ{rooms} غرف جاهزة للزيارة.', subcategories: [] },
    { template: 'السعر المطلوب {price}.', subcategories: [] },
    { template: 'المساحة المذكورة {area} م².', subcategories: [] },
    { template: 'التوزيع على {rooms} غرف.', subcategories: [] },
    { template: 'الوحدة فيها مجلس {living}.', subcategories: [] },
    { template: 'العقار مع إطلالة {view}.', subcategories: [] },
    { template: 'موقف السيارات {parking}.', subcategories: [] },
    { template: 'البلكونة {balcony}.', subcategories: [] },
    { template: 'سنة البناء {year}.', subcategories: [] },
  ],
  detailsGroups: [
    { fact: 'rooms', variants: [
      { template: '• عدد الغرف: {rooms}.', subcategories: [] },
      { template: '• الغرف في الوحدة {rooms}.', subcategories: [] },
      { template: '• التوزيع يشمل {rooms} غرف.', subcategories: [] },
      { template: '• غرف النوم المذكورة {rooms}.', subcategories: [] },
      { template: '• الوحدة فيها {rooms} غرف.', subcategories: [] },
    ]},
    { fact: 'bathrooms', variants: [
      { template: '• عدد الحمامات: {bathrooms}.', subcategories: [] },
      { template: '• الحمامات في الوحدة {bathrooms}.', subcategories: [] },
      { template: '• دورات المياه {bathrooms}.', subcategories: [] },
      { template: '• الوحدة فيها {bathrooms} حمامات.', subcategories: [] },
      { template: '• الحمامات المذكورة {bathrooms}.', subcategories: [] },
    ]},
    { fact: 'area', variants: [
      { template: '• المساحة: {area} م².', subcategories: [] },
      { template: '• المساحة المذكورة {area} م².', subcategories: [] },
      { template: '• العقار بمساحة {area} م².', subcategories: [] },
      { template: '• المساحة الإجمالية {area} م².', subcategories: [] },
      { template: '• المساحة حسب الوصف {area} م².', subcategories: [] },
    ]},
    { fact: 'floor', variants: [
      { template: '• الطابق: {floor}.', subcategories: [] },
      { template: '• الوحدة في الطابق {floor}.', subcategories: [] },
      { template: '• الدور المذكور {floor}.', subcategories: [] },
      { template: '• موقع الوحدة على الطابق {floor}.', subcategories: [] },
      { template: '• الطابق حسب الوصف {floor}.', subcategories: [] },
    ]},
    { fact: 'price', variants: [
      { template: '• السعر: {price}.', subcategories: [] },
      { template: '• السعر المطلوب {price}.', subcategories: [] },
      { template: '• القيمة المعروضة {price}.', subcategories: [] },
      { template: '• المبلغ المذكور {price}.', subcategories: [] },
      { template: '• سعر البيع {price}.', subcategories: [] },
    ]},
    { fact: 'condition', variants: [
      { template: '• العقار بحالة {condition}.', subcategories: [] },
      { template: '• حالة العقار {condition}.', subcategories: [] },
      { template: '• التشطيب الموصوف {condition}.', subcategories: [] },
      { template: '• الوحدة بحالة {condition}.', subcategories: [] },
      { template: '• وصف حالة العقار {condition}.', subcategories: [] },
    ]},
    { fact: 'living', variants: [
      { template: '• المجلس: {living}.', subcategories: [] },
      { template: '• الصالة {living}.', subcategories: [] },
      { template: '• غرفة المعيشة {living}.', subcategories: [] },
      { template: '• المجلس حسب الوصف {living}.', subcategories: [] },
      { template: '• وضع المجلس {living}.', subcategories: [] },
    ]},
    { fact: 'balcony', variants: [
      { template: '• البلكونة: {balcony}.', subcategories: [] },
      { template: '• الشرفة {balcony}.', subcategories: [] },
      { template: '• وضع البلكونة {balcony}.', subcategories: [] },
      { template: '• البلكونة حسب الوصف {balcony}.', subcategories: [] },
      { template: '• الشرفة المذكورة {balcony}.', subcategories: [] },
    ]},
    { fact: 'parking', variants: [
      { template: '• الموقف: {parking}.', subcategories: [] },
      { template: '• مواقف السيارات {parking}.', subcategories: [] },
      { template: '• الوضع الخاص بالموقف {parking}.', subcategories: [] },
      { template: '• الموقف حسب الوصف {parking}.', subcategories: [] },
      { template: '• مواقف الوحدة {parking}.', subcategories: [] },
    ]},
    { fact: 'view', variants: [
      { template: '• الإطلالة: {view}.', subcategories: [] },
      { template: '• الإطلالة المذكورة {view}.', subcategories: [] },
      { template: '• الواجهة على {view}.', subcategories: [] },
      { template: '• المشهد من الوحدة {view}.', subcategories: [] },
      { template: '• الإطلالة حسب الوصف {view}.', subcategories: [] },
    ]},
    { fact: 'year', variants: [
      { template: '• سنة البناء: {year}.', subcategories: [] },
      { template: '• عام الإنشاء {year}.', subcategories: [] },
      { template: '• العقار من سنة {year}.', subcategories: [] },
      { template: '• تاريخ البناء {year}.', subcategories: [] },
      { template: '• السنة المذكورة {year}.', subcategories: [] },
    ]},
    { fact: 'furnished', variants: [
      { template: '• الفرش: {furnished}.', subcategories: [] },
      { template: '• وضع الأثاث {furnished}.', subcategories: [] },
      { template: '• الوحدة من جهة الفرش {furnished}.', subcategories: [] },
      { template: '• التأثيث حسب الوصف {furnished}.', subcategories: [] },
      { template: '• حالة الفرش {furnished}.', subcategories: [] },
    ]},
  ],
  featuresBullets: [
    { template: '• التوزيع عملي بين الغرف.', subcategories: [] },
    { template: '• الغرف {rooms}.', subcategories: [] },
    { template: '• الحمامات {bathrooms}.', subcategories: [] },
    { template: '• المساحة {area} م².', subcategories: [] },
    { template: '• الوحدة على الطابق {floor}.', subcategories: [] },
    { template: '• العقار بحالة {condition}.', subcategories: [] },
    { template: '• الإضاءة طبيعية خلال النهار.', subcategories: [] },
    { template: '• التهوية جيدة في الغرف.', subcategories: [] },
    { template: '• المدخل يستقبل سيارة.', subcategories: [] },
    { template: '• الموقف {parking}.', subcategories: [] },
    { template: '• المجلس {living}.', subcategories: [] },
    { template: '• البلكونة {balcony}.', subcategories: [] },
    { template: '• الإطلالة {view}.', subcategories: [] },
    { template: '• سنة البناء {year}.', subcategories: [] },
    { template: '• الفرش {furnished}.', subcategories: [] },
    { template: '• التشطيب ظاهر في الصور.', subcategories: [] },
    { template: '• النوافذ واسعة على الواجهة.', subcategories: [] },
    { template: '• الكهرباء والماء موصولان.', subcategories: [] },
    { template: '• لا شقوق ظاهرة في الجدران.', subcategories: [] },
    { template: '• الباب الرئيسي سليم.', subcategories: [] },
    { template: '• الأرضيات حسب الصور.', subcategories: [] },
    { template: '• المطبخ مستقل عن المجلس.', subcategories: [] },
    { template: '• السعر {price}.', subcategories: [] },
    { template: '• المعاينة متاحة هذا الأسبوع.', subcategories: [] },
    { template: '• الأوراق تُراجع قبل الاتفاق.', subcategories: [] },
    { template: '• الهدوء ظاهر في الموقع.', subcategories: [] },
    { template: '• الخدمات قريبة من الوحدة.', subcategories: [] },
    { template: '• السلم والمصعد حسب المبنى.', subcategories: [] },
    { template: '• التخزين متاح داخل الوحدة.', subcategories: [] },
    { template: '• الواجهة على الشارع.', subcategories: [] },
  ],
  ctas: [
    { template: 'للمعاينة تواصل عبر رسائل الإعلان.', subcategories: [] },
    { template: 'راسل لتحديد موعد زيارة الوحدة.', subcategories: [] },
    { template: 'اتصل قبل الحضور لتأكيد التوفر.', subcategories: [] },
    { template: 'للتنسيق على السعر راسل المعلن.', subcategories: [] },
    { template: 'للاستفسار عن المساحة تواصل برسالة.', subcategories: [] },
    { template: 'للمعاينة هذا الأسبوع اتصل بالمعلن.', subcategories: [] },
    { template: 'راسل لمعرفة الطابق {floor}.', subcategories: [] },
    { template: 'تواصل لتحديد موعد مشاهدة العقار.', subcategories: [] },
    { template: 'اتصل للاستفسار عن السعر {price}.', subcategories: [] },
    { template: 'للتنسيق على الأوراق راسل صاحب الإعلان.', subcategories: [] },
    { template: 'للمعاينة والفحص تواصل مع البائع.', subcategories: [] },
    { template: 'راسل لتأكيد عدد الغرف {rooms}.', subcategories: [] },
    { template: 'اتصل قبل الزيارة لترتيب الدخول.', subcategories: [] },
    { template: 'للتنسيق على المساحة {area} تواصل برسالة.', subcategories: [] },
    { template: 'تواصل لترتيب المعاينة قبل الاتفاق.', subcategories: [] },
  ],
  detailsLabel: '🔹 تفاصيل الوحدة:',
  featuresLabel: '🔹 أبرز المميزات:',
  featuresCount: 4,
  introCount: 2,
  minDetails: 2,
};
