import type { StructuredLayout } from '../types';

type SubPools = Pick<
  StructuredLayout,
  'subTitleFormat' | 'subHooks' | 'subIntroParagraphs' | 'subFeaturesBullets' | 'subCtas'
>;

export const REAL_ESTATE_SUB_POOLS: SubPools = {
  subTitleFormat: {
    apartments: [
      { template: 'شقة {rooms} غرف بسعر {price}', subcategories: ['apartments'] },
      { template: 'شقة {area} م² مقابل {price}', subcategories: ['apartments'] },
      { template: 'شقة {rooms} غرف و{area} م² — {price}', subcategories: ['apartments'] },
      { template: 'شقة {rooms} غرف طابق {floor} — {price}', subcategories: ['apartments'] },
      { template: 'شقة {area} م² في الطابق {floor} بسعر {price}', subcategories: ['apartments'] },
      { template: 'شقة {rooms} غرف بحالة {condition} — {price}', subcategories: ['apartments'] },
      { template: 'شقة بمساحة {area} م² بسعر {price}', subcategories: ['apartments'] },
      { template: 'شقة {rooms} غرف جاهزة بسعر {price}', subcategories: ['apartments'] },
      { template: 'شقة {area} م² للمعاينة — {price}', subcategories: ['apartments'] },
      { template: 'شقة سكنية {rooms} غرف بسعر {price}', subcategories: ['apartments'] },
      { template: 'شقة {rooms} غرف مع بلكونة — {price}', subcategories: ['apartments'] },
      { template: 'شقة {area} م² مفروشة بسعر {price}', subcategories: ['apartments'] },
    ],
    houses: [
      { template: 'فيلا {rooms} غرف بسعر {price}', subcategories: ['houses'] },
      { template: 'بيت {area} م² مقابل {price}', subcategories: ['houses'] },
      { template: 'فيلا {rooms} غرف و{area} م² — {price}', subcategories: ['houses'] },
      { template: 'بيت مستقل {rooms} غرف بسعر {price}', subcategories: ['houses'] },
      { template: 'منزل {area} م² للبيع بسعر {price}', subcategories: ['houses'] },
      { template: 'فيلا {rooms} غرف بحالة {condition} — {price}', subcategories: ['houses'] },
      { template: 'بيت {area} م² على الطابق {floor} — {price}', subcategories: ['houses'] },
      { template: 'منزل {rooms} غرف مع حديقة — {price}', subcategories: ['houses'] },
      { template: 'فيلا {area} م² جاهزة بسعر {price}', subcategories: ['houses'] },
      { template: 'بيت {rooms} غرف وموقف — {price}', subcategories: ['houses'] },
      { template: 'منزل {area} م² مستقل بسعر {price}', subcategories: ['houses'] },
      { template: 'فيلا {rooms} غرف للمعاينة — {price}', subcategories: ['houses'] },
    ],
    lands: [
      { template: 'أرض بمساحة {area} م² بسعر {price}', subcategories: ['lands'] },
      { template: 'أرض {area} م² مقابل {price}', subcategories: ['lands'] },
      { template: 'أرض {area} م² للبناء بسعر {price}', subcategories: ['lands'] },
      { template: 'قطعة أرض {area} م² — {price}', subcategories: ['lands'] },
      { template: 'أرض سكنية {area} م² بسعر {price}', subcategories: ['lands'] },
      { template: 'أرض على شارع {area} م² — {price}', subcategories: ['lands'] },
      { template: 'أرض زاوية {area} م² بسعر {price}', subcategories: ['lands'] },
      { template: 'أرض {area} م² بصك بسعر {price}', subcategories: ['lands'] },
      { template: 'أرض جاهزة للبناء {area} م² — {price}', subcategories: ['lands'] },
      { template: 'بيع أرض {area} م² مقابل {price}', subcategories: ['lands'] },
      { template: 'أرض {area} م² للمعاينة بسعر {price}', subcategories: ['lands'] },
      { template: 'مساحة أرض {area} م² — {price}', subcategories: ['lands'] },
    ],
    chalets: [
      { template: 'شاليه {rooms} غرف بسعر {price}', subcategories: ['chalets'] },
      { template: 'شاليه {area} م² مقابل {price}', subcategories: ['chalets'] },
      { template: 'شاليه {rooms} غرف و{area} م² — {price}', subcategories: ['chalets'] },
      { template: 'استراحة {rooms} غرف بسعر {price}', subcategories: ['chalets'] },
      { template: 'شاليه {area} م² مع مسبح — {price}', subcategories: ['chalets'] },
      { template: 'شاليه {rooms} غرف بحالة {condition} — {price}', subcategories: ['chalets'] },
      { template: 'استراحة {area} م² للخصوصية بسعر {price}', subcategories: ['chalets'] },
      { template: 'شاليه {rooms} غرف وإطلالة — {price}', subcategories: ['chalets'] },
      { template: 'شاليه {area} م² جاهز بسعر {price}', subcategories: ['chalets'] },
      { template: 'استراحة {rooms} غرف للمعاينة — {price}', subcategories: ['chalets'] },
    ],
    commercial: [
      { template: 'محل بمساحة {area} م² بسعر {price}', subcategories: ['commercial'] },
      { template: 'معرض {area} م² مقابل {price}', subcategories: ['commercial'] },
      { template: 'مكتب {area} م² للبيع بسعر {price}', subcategories: ['commercial'] },
      { template: 'وحدة تجارية {area} م² — {price}', subcategories: ['commercial'] },
      { template: 'محل {area} م² على الطابق {floor} — {price}', subcategories: ['commercial'] },
      { template: 'مكتب {area} م² طابق {floor} بسعر {price}', subcategories: ['commercial'] },
      { template: 'معرض {area} م² على شارع — {price}', subcategories: ['commercial'] },
      { template: 'محل {area} م² بحالة {condition} — {price}', subcategories: ['commercial'] },
      { template: 'وحدة {area} م² للنشاط بسعر {price}', subcategories: ['commercial'] },
      { template: 'مكتب {area} م² للمعاينة — {price}', subcategories: ['commercial'] },
    ],
  },
  subHooks: {
    apartments: [
      { template: 'شقة بـ{rooms} غرف جاهزة للسكن.', subcategories: ['apartments'] },
      { template: 'شقة بمساحة {area} م².', subcategories: ['apartments'] },
      { template: 'السعر {price} للشقة.', subcategories: ['apartments'] },
      { template: 'شقة على الطابق {floor} بسعر {price}.', subcategories: ['apartments'] },
      { template: 'شقة بـ{rooms} غرف وبحالة {condition}.', subcategories: ['apartments'] },
      { template: 'المساحة {area} م² في شقة سكنية.', subcategories: ['apartments'] },
    ],
    houses: [
      { template: 'بيت مستقل بـ{rooms} غرف.', subcategories: ['houses'] },
      { template: 'فيلا بمساحة {area} م².', subcategories: ['houses'] },
      { template: 'السعر {price} للبيت.', subcategories: ['houses'] },
      { template: 'منزل بـ{rooms} غرف وبحالة {condition}.', subcategories: ['houses'] },
      { template: 'بيت على أكثر من دور، والمساحة {area} م².', subcategories: ['houses'] },
      { template: 'فيلا جاهزة للمعاينة بسعر {price}.', subcategories: ['houses'] },
    ],
    lands: [
      { template: 'أرض بمساحة {area} م².', subcategories: ['lands'] },
      { template: 'السعر {price} للأرض.', subcategories: ['lands'] },
      { template: 'أرض {area} م² جاهزة للبناء.', subcategories: ['lands'] },
      { template: 'الواجهة على الشارع والمساحة {area} م².', subcategories: ['lands'] },
      { template: 'أرض بمساحة {area} م² وإطلالة {view}.', subcategories: ['lands'] },
      { template: 'أرض بسعر {price} وسنة {year}.', subcategories: ['lands'] },
    ],
    chalets: [
      { template: 'شاليه بـ{rooms} غرف.', subcategories: ['chalets'] },
      { template: 'شاليه بمساحة {area} م².', subcategories: ['chalets'] },
      { template: 'السعر {price} للشاليه.', subcategories: ['chalets'] },
      { template: 'استراحة بـ{rooms} غرف وبحالة {condition}.', subcategories: ['chalets'] },
      { template: 'شاليه للمناسبات بمساحة {area} م².', subcategories: ['chalets'] },
    ],
    commercial: [
      { template: 'وحدة تجارية بمساحة {area} م².', subcategories: ['commercial'] },
      { template: 'السعر {price} للمحل.', subcategories: ['commercial'] },
      { template: 'المعرض على الطابق {floor} بمساحة {area} م².', subcategories: ['commercial'] },
      { template: 'مكتب بمساحة {area} م² وبحالة {condition}.', subcategories: ['commercial'] },
      { template: 'الواجهة على الشارع والسعر {price}.', subcategories: ['commercial'] },
    ],
  },
  subIntroParagraphs: {
    apartments: [
      { template: 'الشقة فيها {rooms} غرف. السعر {price}.', subcategories: ['apartments'] },
      { template: 'مساحة الشقة {area} م² وعلى الطابق {floor}.', subcategories: ['apartments'] },
      { template: 'الشقة بـ{rooms} غرف و{bathrooms} حمامات.', subcategories: ['apartments'] },
      { template: 'الشقة بحالة {condition} وبمساحة {area} م².', subcategories: ['apartments'] },
      { template: 'البلكونة {balcony} ضمن الشقة.', subcategories: ['apartments'] },
      { template: 'الفرش {furnished} والسعر {price}.', subcategories: ['apartments'] },
    ],
    houses: [
      { template: 'البيت فيه {rooms} غرف. السعر {price}.', subcategories: ['houses'] },
      { template: 'مساحة البيت {area} م² وهو مستقل.', subcategories: ['houses'] },
      { template: 'البيت بـ{rooms} غرف و{bathrooms} حمامات.', subcategories: ['houses'] },
      { template: 'المنزل بحالة {condition} وبمساحة {area} م².', subcategories: ['houses'] },
      { template: 'الموقف {parking} ضمن البيت.', subcategories: ['houses'] },
      { template: 'الحديقة مرافقة والمساحة {area} م².', subcategories: ['houses'] },
    ],
    lands: [
      { template: 'الأرض بمساحة {area} م². السعر {price}.', subcategories: ['lands'] },
      { template: 'المساحة {area} م² والواجهة على شارع.', subcategories: ['lands'] },
      { template: 'الأرض بإطلالة {view}.', subcategories: ['lands'] },
      { template: 'الوصف يذكر سنة {year}.', subcategories: ['lands'] },
      { template: 'السعر {price} لأرض قابلة للبناء.', subcategories: ['lands'] },
      { template: 'المساحة المذكورة {area} م² والصك يُراجع.', subcategories: ['lands'] },
    ],
    chalets: [
      { template: 'الشاليه فيه {rooms} غرف. السعر {price}.', subcategories: ['chalets'] },
      { template: 'مساحة الشاليه {area} م² والخصوصية واضحة.', subcategories: ['chalets'] },
      { template: 'الشاليه بـ{rooms} غرف و{bathrooms} حمامات.', subcategories: ['chalets'] },
      { template: 'الاستراحة بحالة {condition} وبمساحة {area} م².', subcategories: ['chalets'] },
      { template: 'الإطلالة {view} من الجلسة.', subcategories: ['chalets'] },
    ],
    commercial: [
      { template: 'المساحة التجارية {area} م². السعر {price}.', subcategories: ['commercial'] },
      { template: 'الوحدة على الطابق {floor} وبمساحة {area} م².', subcategories: ['commercial'] },
      { template: 'المحل بحالة {condition} والسعر {price}.', subcategories: ['commercial'] },
      { template: 'الواجهة على الشارع والمساحة {area} م².', subcategories: ['commercial'] },
      { template: 'السعر {price} لوحدة تناسب النشاط.', subcategories: ['commercial'] },
    ],
  },
  subFeaturesBullets: {
    apartments: [
      { template: '• الشقة على الطابق {floor}.', subcategories: ['apartments'] },
      { template: '• الغرف {rooms}.', subcategories: ['apartments'] },
      { template: '• الحمامات {bathrooms}.', subcategories: ['apartments'] },
      { template: '• البلكونة {balcony}.', subcategories: ['apartments'] },
      { template: '• المجلس {living}.', subcategories: ['apartments'] },
      { template: '• الفرش {furnished}.', subcategories: ['apartments'] },
      { template: '• الموقف {parking}.', subcategories: ['apartments'] },
      { template: '• المصعد يخدم الطابق.', subcategories: ['apartments'] },
      { template: '• الشقة بحالة {condition}.', subcategories: ['apartments'] },
      { template: '• الإضاءة طبيعية في الصالة.', subcategories: ['apartments'] },
    ],
    houses: [
      { template: '• البيت مستقل بمدخله.', subcategories: ['houses'] },
      { template: '• المساحة {area} م².', subcategories: ['houses'] },
      { template: '• الغرف {rooms}.', subcategories: ['houses'] },
      { template: '• الحمامات {bathrooms}.', subcategories: ['houses'] },
      { template: '• حديقة مرافقة للبيت.', subcategories: ['houses'] },
      { template: '• الموقف {parking}.', subcategories: ['houses'] },
      { template: '• أكثر من دور حسب البناء.', subcategories: ['houses'] },
      { template: '• المجلس {living}.', subcategories: ['houses'] },
      { template: '• البيت بحالة {condition}.', subcategories: ['houses'] },
      { template: '• السور والبوابة ظاهران.', subcategories: ['houses'] },
    ],
    lands: [
      { template: '• المساحة {area} م².', subcategories: ['lands'] },
      { template: '• السعر {price}.', subcategories: ['lands'] },
      { template: '• الإطلالة {view}.', subcategories: ['lands'] },
      { template: '• السنة المذكورة {year}.', subcategories: ['lands'] },
      { template: '• الواجهة على شارع.', subcategories: ['lands'] },
      { template: '• الأرض زاوية حسب الوصف.', subcategories: ['lands'] },
      { template: '• الصك يُراجع قبل الاتفاق.', subcategories: ['lands'] },
      { template: '• الأرض مستوية للبناء.', subcategories: ['lands'] },
      { template: '• المدخل يستقبل سيارة.', subcategories: ['lands'] },
      { template: '• حدود الأرض ظاهرة في المعاينة.', subcategories: ['lands'] },
    ],
    chalets: [
      { template: '• الجلسة خارجية.', subcategories: ['chalets'] },
      { template: '• مسبح حسب الوصف.', subcategories: ['chalets'] },
      { template: '• الخصوصية ظاهرة في الموقع.', subcategories: ['chalets'] },
      { template: '• الغرف {rooms}.', subcategories: ['chalets'] },
      { template: '• الحمامات {bathrooms}.', subcategories: ['chalets'] },
      { template: '• الإطلالة {view}.', subcategories: ['chalets'] },
      { template: '• المساحة {area} م².', subcategories: ['chalets'] },
      { template: '• مناسب للمناسبات القصيرة.', subcategories: ['chalets'] },
    ],
    commercial: [
      { template: '• المساحة {area} م².', subcategories: ['commercial'] },
      { template: '• الوحدة على الطابق {floor}.', subcategories: ['commercial'] },
      { template: '• واجهة على الشارع.', subcategories: ['commercial'] },
      { template: '• حركة المحل ظاهرة من الواجهة.', subcategories: ['commercial'] },
      { template: '• مستودع أو تخزين داخل الوحدة.', subcategories: ['commercial'] },
      { template: '• مناسبة لمكتب.', subcategories: ['commercial'] },
      { template: '• السعر {price}.', subcategories: ['commercial'] },
      { template: '• الوحدة بحالة {condition}.', subcategories: ['commercial'] },
    ],
  },
  subCtas: {
    apartments: [
      { template: 'للمعاينة داخل الشقة تواصل عبر الرسائل.', subcategories: ['apartments'] },
      { template: 'راسل لتأكيد الطابق {floor} قبل الحضور.', subcategories: ['apartments'] },
      { template: 'اتصل لترتيب زيارة الشقة.', subcategories: ['apartments'] },
    ],
    houses: [
      { template: 'للمعاينة داخل البيت تواصل عبر الرسائل.', subcategories: ['houses'] },
      { template: 'راسل لتأكيد المساحة {area} قبل الزيارة.', subcategories: ['houses'] },
      { template: 'اتصل لترتيب دخول المنزل.', subcategories: ['houses'] },
    ],
    lands: [
      { template: 'للمعاينة على الأرض تواصل عبر الرسائل.', subcategories: ['lands'] },
      { template: 'راسل لمراجعة الصك قبل الاتفاق.', subcategories: ['lands'] },
      { template: 'اتصل لتحديد موقع الأرض قبل الحضور.', subcategories: ['lands'] },
    ],
    chalets: [
      { template: 'للمعاينة في الشاليه تواصل عبر الرسائل.', subcategories: ['chalets'] },
      { template: 'راسل لتأكيد عدد الغرف {rooms}.', subcategories: ['chalets'] },
      { template: 'اتصل لترتيب زيارة الاستراحة.', subcategories: ['chalets'] },
    ],
    commercial: [
      { template: 'للمعاينة في الوحدة تواصل عبر الرسائل.', subcategories: ['commercial'] },
      { template: 'راسل لتأكيد المساحة {area} قبل الزيارة.', subcategories: ['commercial'] },
      { template: 'اتصل لترتيب دخول المحل.', subcategories: ['commercial'] },
    ],
  },
};
