import type { StructuredLayout } from '../types';

type SubPools = Pick<
  StructuredLayout,
  'subTitleFormat' | 'subHooks' | 'subIntroParagraphs' | 'subFeaturesBullets' | 'subCtas'
>;

export const REAL_ESTATE_SUB_POOLS: SubPools = {
  subTitleFormat: {
    apartments: [
      { template: 'شقة {rooms} غرف و{area} م² — سكن جاهز', subcategories: ['apartments'] },
      { template: 'شقة {rooms} غرف بمساحة {area} م²', subcategories: ['apartments'] },
      { template: 'شقة للبيع: {rooms} غرف بسعر {price}', subcategories: ['apartments'] },
      { template: 'وحدة شققية {area} م² — {rooms} غرف', subcategories: ['apartments'] },
      { template: 'شقة الطابق {floor} — {rooms} غرف و{price}', subcategories: ['apartments'] },
      { template: 'شقة {rooms} غرف بحالة {condition} — {price}', subcategories: ['apartments'] },
      { template: 'شقة {area} م² بسعر {price}', subcategories: ['apartments'] },
      { template: 'سكن شقق {rooms} غرف ضمن {area} م²', subcategories: ['apartments'] },
      { template: 'شقة {rooms} غرف على الطابق {floor} — {area} م²', subcategories: ['apartments'] },
      { template: 'شقة عائلية {rooms} غرف بسعر {price}', subcategories: ['apartments'] },
      { template: 'شقة بحالة {condition} — {area} م² و{price}', subcategories: ['apartments'] },
      { template: 'بيع شقة {rooms} غرف على {area} م²', subcategories: ['apartments'] },
    ],
    houses: [
      { template: 'منزل {rooms} غرف على {area} م² — خصوصية أوضح', subcategories: ['houses'] },
      { template: 'بيت مستقل {rooms} غرف بسعر {price}', subcategories: ['houses'] },
      { template: 'فيلا {area} م² للبيع بسعر {price}', subcategories: ['houses'] },
      { template: 'منزل عائلي {rooms} غرف ضمن {area} م²', subcategories: ['houses'] },
      { template: 'بيت {rooms} غرف بحالة {condition} — {price}', subcategories: ['houses'] },
      { template: 'فيلا {rooms} غرف بمساحة {area} م²', subcategories: ['houses'] },
      { template: 'منزل {area} م² بسعر {price}', subcategories: ['houses'] },
      { template: 'سكن مستقل {rooms} غرف — {price}', subcategories: ['houses'] },
      { template: 'بيت {area} م² بحالة {condition} — {price}', subcategories: ['houses'] },
      { template: 'منزل {rooms} غرف على الطابق {floor} — {price}', subcategories: ['houses'] },
      { template: 'فيلا {rooms} غرف بسعر {price}', subcategories: ['houses'] },
      { template: 'بيت عائلي {area} م² — {rooms} غرف', subcategories: ['houses'] },
    ],
    lands: [
      { template: 'أرض بمساحة {area} م² بسعر {price}', subcategories: ['lands'] },
      { template: 'قطعة {area} م² للبيع بسعر {price}', subcategories: ['lands'] },
      { template: 'أرض بسعر {price} على {area} م²', subcategories: ['lands'] },
      { template: 'بيع أرض {area} م² — {price}', subcategories: ['lands'] },
      { template: 'قطعة أرض {area} م² بقيمة {price}', subcategories: ['lands'] },
      { template: 'أرض فضاء {area} م² بسعر {price}', subcategories: ['lands'] },
      { template: 'مساحة أرض {area} م² للتملك — {price}', subcategories: ['lands'] },
      { template: 'أرض استثمار {area} م² بسعر {price}', subcategories: ['lands'] },
      { template: 'قطعة بسعر {price} ومساحة {area} م²', subcategories: ['lands'] },
      { template: 'أرض سكنية {area} م² بسعر {price}', subcategories: ['lands'] },
      { template: 'أرض {area} م² جاهزة للتقييم — {price}', subcategories: ['lands'] },
      { template: 'بيع قطعة {area} م² بقيمة {price}', subcategories: ['lands'] },
    ],
    chalets: [
      { template: 'شاليه {rooms} غرف بمساحة {area} م²', subcategories: ['chalets'] },
      { template: 'شاليه {rooms} غرف بسعر {price}', subcategories: ['chalets'] },
      { template: 'استراحة {area} م² للبيع بسعر {price}', subcategories: ['chalets'] },
      { template: 'شاليه {area} م² — {rooms} غرف', subcategories: ['chalets'] },
      { template: 'شاليه بحالة {condition} — {rooms} غرف بسعر {price}', subcategories: ['chalets'] },
      { template: 'استراحة {rooms} غرف على {area} م²', subcategories: ['chalets'] },
      { template: 'شاليه بسعر {price} ومساحة {area} م²', subcategories: ['chalets'] },
      { template: 'وحدة ضيافة {rooms} غرف — {price}', subcategories: ['chalets'] },
      { template: 'شاليه عائلي {rooms} غرف ضمن {area} م²', subcategories: ['chalets'] },
      { template: 'استراحة {area} م² بحالة {condition} — {price}', subcategories: ['chalets'] },
    ],
    commercial: [
      { template: 'محل {area} م² بسعر {price}', subcategories: ['commercial'] },
      { template: 'مكتب {rooms} فراغات على {area} م²', subcategories: ['commercial'] },
      { template: 'وحدة تجارية {area} م² — {price}', subcategories: ['commercial'] },
      { template: 'معرض {area} م² للبيع بسعر {price}', subcategories: ['commercial'] },
      { template: 'مكتب الطابق {floor} بمساحة {area} م² — {price}', subcategories: ['commercial'] },
      { template: 'محل بحالة {condition} — {area} م² بسعر {price}', subcategories: ['commercial'] },
      { template: 'مساحة تجارية من {rooms} فراغات بسعر {price}', subcategories: ['commercial'] },
      { template: 'مكتب {area} م² بقيمة {price}', subcategories: ['commercial'] },
      { template: 'واجهة تجارية {area} م² بسعر {price}', subcategories: ['commercial'] },
      { template: 'معرض {rooms} فراغات ضمن {area} م²', subcategories: ['commercial'] },
    ],
  },
  subHooks: {
    apartments: [
      { template: 'شقة من {rooms} غرف تتيح للعائلة خصوصية أوضح في كل يوم.', subcategories: ['apartments'] },
      { template: 'مساحة {area} م² داخل الشقة تكفي للمعيشة دون شعور بالضيق.', subcategories: ['apartments'] },
      { template: 'سعر {price} يفتح باب التملك لشقة يمكن الانتقال إليها بهدوء.', subcategories: ['apartments'] },
      { template: '{rooms} غرف على الطابق {floor} تجعل الروتين اليومي أهدأ.', subcategories: ['apartments'] },
      { template: 'بـ{area} م² تحصل على توزيع عملي يسهّل الحركة داخل الشقة.', subcategories: ['apartments'] },
      { template: 'قيمة {price} مقابل سكن شقق جاهز للاستخدام بعد الاتفاق.', subcategories: ['apartments'] },
    ],
    houses: [
      { template: 'منزل من {rooms} غرف يتيح استقلالية لا تجدها في السكن المشترك.', subcategories: ['houses'] },
      { template: 'مساحة {area} م² تسع حديقة واستخداماً أوسع للعائلة.', subcategories: ['houses'] },
      { template: 'سعر {price} لبيت مستقل يناسب من يريد خصوصية يومية.', subcategories: ['houses'] },
      { template: '{rooms} غرف بحالة {condition} تقلل أعمال التجهيز قبل السكن.', subcategories: ['houses'] },
      { template: 'على {area} م² تعيش العائلة بمسافة أريح بين الغرف والحديقة.', subcategories: ['houses'] },
      { template: 'تملك بيت بـ{price} يعني قراراً أوضح للاستقرار.', subcategories: ['houses'] },
    ],
    lands: [
      { template: 'أرض بمساحة {area} م² تتيح حرية التخطيط قبل البناء.', subcategories: ['lands'] },
      { template: 'سعر {price} لقطعة يمكن تقييمها بهدوء قبل الشراء.', subcategories: ['lands'] },
      { template: 'مساحة {area} م² تكفي لمشروع سكني أو استثمار مدروس.', subcategories: ['lands'] },
      { template: 'بقيمة {price} تدخل إلى أصل واضح الحدود.', subcategories: ['lands'] },
      { template: 'قطعة {area} م² بإطلالة {view} ترفع مرونة التوجيه.', subcategories: ['lands'] },
      { template: 'أرض بسعر {price} ومن سنة {year}، رقمها جاهز للمقارنة.', subcategories: ['lands'] },
    ],
    chalets: [
      { template: 'شاليه من {rooms} غرف يتيح خصوصية للإقامات القصيرة.', subcategories: ['chalets'] },
      { template: 'مساحة {area} م² تكفي لاستضافة هادئة بعيداً عن الزحام.', subcategories: ['chalets'] },
      { template: 'سعر {price} لوحدة ضيافة جاهزة لقضاء عطلة مريحة.', subcategories: ['chalets'] },
      { template: '{rooms} غرف بحالة {condition} تقلل تجهيز الإقامة.', subcategories: ['chalets'] },
      { template: 'مساحة {area} م² تتيح جلسة خارجية بخصوصية أعلى.', subcategories: ['chalets'] },
    ],
    commercial: [
      { template: 'مساحة {area} م² تتيح واجهة أوضح لحركة الزبائن.', subcategories: ['commercial'] },
      { template: 'سعر {price} لوحدة يمكن تشغيلها دون تعديل واسع.', subcategories: ['commercial'] },
      { template: '{rooms} فراغات عملية تفصل الاستقبال عن العمل.', subcategories: ['commercial'] },
      { template: 'على الطابق {floor} تحصل على {area} م² بحركة أهدى.', subcategories: ['commercial'] },
      { template: 'بقيمة {price} تدخل إلى موقع تجاري قابل للتقييم فوراً.', subcategories: ['commercial'] },
    ],
  },
  subIntroParagraphs: {
    apartments: [
      { template: 'شقة من {rooms} غرف بمساحة {area} م²، بتوزيع يفصل النوم عن المعيشة ويمنح العائلة هدوءاً يومياً.', subcategories: ['apartments'] },
      { template: 'تقع هذه الشقة على الطابق {floor} وتضم {rooms} غرف، مع تهوية مريحة وخصوصية أوضح.', subcategories: ['apartments'] },
      { template: 'وحدة شققية بسعر {price} ومساحة {area} م²، مناسبة لسكن فوري أو استثمار واضح المعالم.', subcategories: ['apartments'] },
      { template: 'شقة بحالة {condition} من {rooms} غرف، جاهزة لتقليل التجهيز قبل الانتقال.', subcategories: ['apartments'] },
      { template: 'على {area} م² تتوزع الشقة بطريقة عملية، بسعر {price} يمكن مراجعته قبل المعاينة.', subcategories: ['apartments'] },
      { template: 'شقة الطابق {floor} بمساحة {area} م²، توازن بين سهولة الوصول والابتعاد عن الضجيج.', subcategories: ['apartments'] },
    ],
    houses: [
      { template: 'منزل مستقل من {rooms} غرف على {area} م²، يتيح للعائلة خصوصية واستقلالية في الاستخدام.', subcategories: ['houses'] },
      { template: 'بيت بمساحة {area} م² وسعر {price}، مناسب لمن يريد حديقة وحركة أوسع خارج الغرف.', subcategories: ['houses'] },
      { template: 'فيلا من {rooms} غرف بحالة {condition}، تقلل أعمال التعديل قبل السكن.', subcategories: ['houses'] },
      { template: 'سكن مستقل بسعر {price} وفيه {rooms} غرف، يفصل حياة العائلة عن الجيران.', subcategories: ['houses'] },
      { template: 'منزل على {area} م² بحالة {condition}، يتيح توزيعاً أريح بين النوم والمعيشة.', subcategories: ['houses'] },
      { template: 'بيت عائلي من {rooms} غرف ضمن {area} م²، مع مساحة خارجية تزيد حرية الحركة.', subcategories: ['houses'] },
    ],
    lands: [
      { template: 'أرض بمساحة {area} م² وسعر {price}، تتيح التخطيط قبل البناء دون التزام بتقسيم جاهز.', subcategories: ['lands'] },
      { template: 'قطعة {area} م² بإطلالة {view}، مناسبة لمن يريد أصلاً واضحاً قبل تحديد الاستخدام.', subcategories: ['lands'] },
      { template: 'تُعرض الأرض بسعر {price} وعلى مساحة {area} م²، لتقييم هادئ قبل القرار.', subcategories: ['lands'] },
      { template: 'قطعة من سنة {year} بمساحة {area} م²، جاهزة للمراجعة الميدانية.', subcategories: ['lands'] },
      { template: 'أرض فضاء مساحتها {area} م² بقيمة {price}، تتيح مرونة في المشروع القادم.', subcategories: ['lands'] },
      { template: 'بسعر {price} وإطلالة {view}، يمكن مقارنة هذه الأرض بهدوء قبل الشراء.', subcategories: ['lands'] },
    ],
    chalets: [
      { template: 'شاليه من {rooms} غرف بمساحة {area} م²، مناسب لإقامة قصيرة بخصوصية أعلى.', subcategories: ['chalets'] },
      { template: 'استراحة بسعر {price} وفيها {rooms} غرف، جاهزة لاستضافة هادئة.', subcategories: ['chalets'] },
      { template: 'وحدة ضيافة على {area} م² بحالة {condition}، تقلل تجهيز العطلة.', subcategories: ['chalets'] },
      { template: 'شاليه بمساحة {area} م² وسعر {price}، يتيح جلسة خارجية بعيداً عن الزحام.', subcategories: ['chalets'] },
      { template: 'منتجع خاص من {rooms} غرف بحالة {condition}، مناسب للسكن الموسمي أو الاستثمار الهادئ.', subcategories: ['chalets'] },
    ],
    commercial: [
      { template: 'وحدة تجارية بمساحة {area} م² وسعر {price}، مناسبة لنشاط يحتاج واجهة وحركة واضحة.', subcategories: ['commercial'] },
      { template: 'مكتب من {rooms} فراغات على {area} م²، يفصل الاستقبال عن مساحة العمل.', subcategories: ['commercial'] },
      { template: 'محل على الطابق {floor} بمساحة {area} م²، بوصول عملي للزبائن.', subcategories: ['commercial'] },
      { template: 'معرض بسعر {price} وحالة تشطيب {condition}، يقلل التعديل قبل التشغيل.', subcategories: ['commercial'] },
      { template: 'مساحة تجارية {area} م² على الطابق {floor}، قابلة للتقييم قبل التجهيز.', subcategories: ['commercial'] },
    ],
  },
  subFeaturesBullets: {
    apartments: [
      { template: '• بلكونة تمدّ الشقة بهواء طبيعي دون الخروج من المبنى.', subcategories: ['apartments'] },
      { template: '• طابق يوازن بين سهولة الوصول وخصوصية أعلى.', subcategories: ['apartments'] },
      { template: '• معيشة منفصلة عن غرف النوم لراحة العائلة.', subcategories: ['apartments'] },
      { template: '• حمامات بتوزيع يخفف الازدحام الصباحي.', subcategories: ['apartments'] },
      { template: '• تأثيث جاهز يقلل زمن الانتقال.', subcategories: ['apartments'] },
      { template: '• إضاءة نهارية تصل إلى جلسة المعيشة.', subcategories: ['apartments'] },
      { template: '• مدخل هادئ بعيد عن حركة الدرج المباشرة.', subcategories: ['apartments'] },
      { template: '• توزيع {rooms} غرف يناسب سكناً عائلياً منظماً.', subcategories: ['apartments'] },
      { template: '• بلكونة {balcony} لجلسة مسائية خفيفة.', subcategories: ['apartments'] },
      { template: '• موقف {parking} يخفف عناء البحث اليومي.', subcategories: ['apartments'] },
    ],
    houses: [
      { template: '• استقلالية كاملة عن الجيران في الدخول والخروج.', subcategories: ['houses'] },
      { template: '• مساحة خارجية تتيح حديقة أو جلسة عائلية.', subcategories: ['houses'] },
      { template: '• موقف خاص يخفف عناء الشارع.', subcategories: ['houses'] },
      { template: '• أكثر من مستوى يفصل النوم عن المعيشة.', subcategories: ['houses'] },
      { template: '• خصوصية أعلى للأطفال داخل الحد.', subcategories: ['houses'] },
      { template: '• حرية تعديل التوزيع دون قيود الشقة.', subcategories: ['houses'] },
      { template: '• مدخل مستقل يزيد الشعور بالسكن الخاص.', subcategories: ['houses'] },
      { template: '• مساحة {area} م² تسع الاستخدام العائلي والحديقة.', subcategories: ['houses'] },
      { template: '• موقف {parking} ملاصق للبيت.', subcategories: ['houses'] },
      { template: '• طابق {floor} يفصل الضيوف عن غرف النوم.', subcategories: ['houses'] },
    ],
    lands: [
      { template: '• مساحة واضحة تسهّل التخطيط قبل البناء.', subcategories: ['lands'] },
      { template: '• حرية اختيار التقسيم حسب الحاجة.', subcategories: ['lands'] },
      { template: '• أصل يمكن تقييمه على الطبيعة قبل القرار.', subcategories: ['lands'] },
      { template: '• مرونة بين الاستخدام السكني والاستثماري.', subcategories: ['lands'] },
      { template: '• حدود يمكن مراجعتها بهدوء أثناء المعاينة.', subcategories: ['lands'] },
      { template: '• إطلالة {view} ترفع خيارات التوجيه.', subcategories: ['lands'] },
      { template: '• مساحة {area} م² كافية لمشروع مدروس.', subcategories: ['lands'] },
      { template: '• سعر {price} ظاهر للمقارنة.', subcategories: ['lands'] },
      { template: '• قطعة من سنة {year} ببيانات أوضح.', subcategories: ['lands'] },
      { template: '• أرض فضاء بلا تقسيم مفروض.', subcategories: ['lands'] },
    ],
    chalets: [
      { template: '• خصوصية أعلى للإقامات القصيرة.', subcategories: ['chalets'] },
      { template: '• جلسة خارجية مناسبة للضيافة الهادئة.', subcategories: ['chalets'] },
      { template: '• مساحة تستوعب تجمع العائلة في العطلة.', subcategories: ['chalets'] },
      { template: '• جاهزية للإقامة دون تجهيز طويل.', subcategories: ['chalets'] },
      { template: '• إطلالة تهدئ الجلسة المسائية.', subcategories: ['chalets'] },
      { template: '• مناسبة للسكن الموسمي أو الإيجار القصير.', subcategories: ['chalets'] },
      { template: '• إطلالة {view} تزيد راحة الإقامة.', subcategories: ['chalets'] },
      { template: '• {rooms} غرف تكفي لفصل الضيوف عن العائلة.', subcategories: ['chalets'] },
    ],
    commercial: [
      { template: '• واجهة أوضح تساعد على ظهور النشاط.', subcategories: ['commercial'] },
      { template: '• مساحة حركة تناسب الزبائن والموظفين.', subcategories: ['commercial'] },
      { template: '• وصول عملي من الشارع إلى الداخل.', subcategories: ['commercial'] },
      { template: '• فراغ قابل للتقسيم حسب طبيعة العمل.', subcategories: ['commercial'] },
      { template: '• تشطيب يقلل زمن التشغيل.', subcategories: ['commercial'] },
      { template: '• طابق يوازن بين الهدوء وسهولة الوصول.', subcategories: ['commercial'] },
      { template: '• مساحة {area} م² تناسب العرض أو المكتب.', subcategories: ['commercial'] },
      { template: '• طابق {floor} بحركة يمكن قياسها أثناء الزيارة.', subcategories: ['commercial'] },
    ],
  },
  subCtas: {
    apartments: [
      { template: 'تواصل لحجز معاينة الشقة.', subcategories: ['apartments'] },
      { template: 'راسلنا لتنسيق زيارة على الطابق {floor}.', subcategories: ['apartments'] },
      { template: 'اتصل للاستفسار عن شقة من {rooms} غرف.', subcategories: ['apartments'] },
    ],
    houses: [
      { template: 'احجز معاينة للمنزل المستقل.', subcategories: ['houses'] },
      { template: 'تواصل لمراجعة البيت ومساحته {area} م².', subcategories: ['houses'] },
      { template: 'راسلنا لتنسيق زيارة عائلية هادئة.', subcategories: ['houses'] },
    ],
    lands: [
      { template: 'اتصل لتنسيق معاينة الأرض على الطبيعة.', subcategories: ['lands'] },
      { template: 'راسلنا لمراجعة قطعة بمساحة {area} م².', subcategories: ['lands'] },
      { template: 'تواصل للاستفسار عن السعر {price}.', subcategories: ['lands'] },
    ],
    chalets: [
      { template: 'احجز معاينة للشاليه قبل الموسم.', subcategories: ['chalets'] },
      { template: 'تواصل لتنسيق زيارة وحدة من {rooms} غرف.', subcategories: ['chalets'] },
      { template: 'راسلنا لترتيب مشاهدة الاستراحة.', subcategories: ['chalets'] },
    ],
    commercial: [
      { template: 'اتصل لتنسيق معاينة الوحدة التجارية.', subcategories: ['commercial'] },
      { template: 'راسلنا لمراجعة مساحة {area} م² أثناء الدوام.', subcategories: ['commercial'] },
      { template: 'تواصل لحجز زيارة على الطابق {floor}.', subcategories: ['commercial'] },
    ],
  },
};
