// RULE-14-EXCEPTION: Static taxonomy
// V2 templates — higher-volume variety for the 20 FOX Marketplace categories.
// Merged as a third layer (after BASE + EXTRA). Duplicates are removed
// automatically by categoryTemplates.ts.
//
// Design notes:
//  - Slots used MUST resolve from the fact set; unresolved templates are
//    skipped by the engine, so bad templates cost nothing at runtime.
//  - No emojis, no numbers, no hardcoded brand names.

export const CATEGORY_TEMPLATES_V2: Record<string, {
  readonly titleTemplates: readonly string[];
  readonly paragraph1: readonly string[];
  readonly paragraph2: readonly string[];
  readonly paragraph3: readonly string[];
}> = {
  // ═══════════════════════════════════════════════
  // MOTORS
  // ═══════════════════════════════════════════════
  'motors': {
    titleTemplates: [
      '{make} {model} {year} {fuel} — {hook}',
      '{year} {make} {model} {color} — {hook}',
      '{make} {model} — {hook}',
      '{make} {model} {year} {condTone}',
      'فرصة {make} {model} {year} — {hook}',
      '{color} {make} {model} موديل {year}',
      '{make} {model} {trans} {year} — {hook}',
      '{hook} في {make} {model} {year}',
      '{make} {model} {fuel} بلون {color}',
      '{yearTone} {make} {model} — {close}',
      '{make} {model} بمسافة {km}',
      '{fuelTone} {make} {model} {year}',
    ],
    paragraph1: [
      '{open} {make} {model} {year} بمحرك {fuel}، {hook}.',
      'سيارة {make} {model} موديل {year} بلون {color}، {fuelTone}.',
      '{yearTone}، و{make} {model} بنظام {fuel} — {hook}.',
      'تُعرض {make} {model} {year} بحالة {condTone}، {hook}.',
      'يجمع {make} {model} بين لون {color} وأداء {fuelTone}.',
      '{hook}، وهذه {make} {model} موديل {year} تثبت ذلك.',
      'تبدأ الحكاية مع {make} {model} بلون {color}، {hook}.',
      '{hook}، و{make} {model} {year} تجسّد هذا المعنى.',
      'ناقل {trans} في {make} {model} {year} يكمّل أداء {fuelTone}.',
      'سيارة {make} {model} {year}، {hook}، بمحرك {fuel}.',
      '{make} {model} {year} بلون {color}، {hook}.',
      '{open} {make} {model} {year}، {hook}.',
    ],
    paragraph2: [
      'السيارة بلون {color}، {colorTone}. نظام {fuel} يبقى {fuelTone}.',
      '{colorTone}، ومحرك {fuel} {fuelTone}. {yearTone}.',
      'بلغت المسافة {km}، مع ناقل {trans} وحالة {condTone}.',
      '{yearTone} يظهر في التفاصيل، والوقود {fuel} يبقى {fuelTone}.',
      'المسافة المقطوعة {km}، والهيكل بلون {color} يعكس {condTone}.',
      'يعمل المحرك بنظام {fuel}، {fuelTone}، بينما الناقل {trans} يضبط الإيقاع.',
      '{colorTone} يرافق الطلاء {color}، و{yearTone} يؤكّد العناية.',
      'ناقل الحركة {trans} يناسب محرك {fuel} الذي يبقى {fuelTone}.',
      'سجّلت السيارة مسافة {km}، وهي موديل {year} بحالة {condTone}.',
      'اللون {color} ليس تفصيلاً عابراً، إذ {colorTone}، والوقود {fuel}.',
      'موديل {year} يحافظ على {yearTone}، والمسافة {km} موثّقة بوضوح.',
      'طلاء {color} بحالة {condTone}، والمحرك {fuel} يبقى {fuelTone}.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      '{price} دينار، مع تفاوض معقول. {close}.',
      'يُطلب مقابلها {price} دينار. {close}.',
      'القيمة المعروضة {price} دينار لمن يقدّر حالة {condTone}. {close}.',
      'السعر {price} دينار، وهو يعكس {yearTone}. {close}.',
      'يمكن إتمام الاتفاق عند {price} دينار. {hook}، و{close}.',
      '{close}، والسعر المحدد {price} دينار.',
      'مبلغ {price} دينار يفتح باب التفاوض الهادئ. {close}.',
      'العرض قائم على {price} دينار بحالة {condTone}. {close}.',
      'السعر {price} دينار، والتفاوض يبقى ضمن المعقول. {close}.',
      'تُعرض السيارة بمبلغ {price} دينار. {close}.',
      'السعر المعلن {price} دينار لمن يبحث عن {hook}. {close}.',
    ],
  },

  // ═══════════════════════════════════════════════
  // REAL ESTATE
  // ═══════════════════════════════════════════════
  'real-estate': {
    titleTemplates: [
      '{rooms} غرف في {area} — {hook}',
      'عقار {year} في {area} — {hook}',
      'طابق {floor} بموقع {area} بحالة {condTone}',
      'فرصة سكن {rooms} غرف — {hook}',
      '{area} على الطابق {floor} — {close}',
      '{yearTone} عقار {area} بعدد غرف {rooms}',
      '{hook} — وحدة في {area} طابق {floor}',
      '{condTone} سكن في {area} من عام {year}',
      'طابق {floor} في {area} — {hook}',
      '{rooms} غرف طابق {floor} عام {year}',
      'عرض {area} بحالة {condTone}',
      '{year} في {area} بعدد غرف {rooms} — {hook}',
    ],
    paragraph1: [
      '{open} وحدة في {area} بعدد غرف {rooms}، {hook}.',
      'يقع العقار في {area} على الطابق {floor}، {hook}.',
      '{yearTone}، والسكن في {area} يجسّد {hook}.',
      'تُعرض وحدة عام {year} في {area} بحالة {condTone}.',
      'يجمع العقار بين موقع {area} وتشطيب {colorTone}.',
      '{hook}، وهذه الوحدة في {area} بعدد غرف {rooms} تثبت ذلك.',
      'من يزور الطابق {floor} في {area} يلحظ حالة {condTone}.',
      'تبدأ الجولة من {area}، حيث الغرف بعدد {rooms}، {hook}.',
      '{colorTone} في التشطيب، والوحدة ضمن {area} تلائم {hook}.',
      'يضع عقار {area} معياراً واضحاً بعدد غرف {rooms}، {hook}.',
      '{yearTone} تظهر في وحدة {year} الكائنة في {area}.',
      '{open} وحدة {area} عام {year}، {hook}.',
    ],
    paragraph2: [
      'الموقع في {area}، وعدد الغرف {rooms}، والطابق {floor}.',
      '{colorTone} في التشطيب، وحالة العقار {condTone}. {yearTone}.',
      'بُني عام {year}، ويقع على الطابق {floor} ضمن {area}.',
      'الغرف بعدد {rooms}، والتشطيب بلون {color} يمنح {colorTone}.',
      '{yearTone} يظهر في التفاصيل، والحالة العامة {condTone}.',
      'الطابق {floor} يطل على محيط {area}، والغرف بعدد {rooms}.',
      'التشطيب يوصف بأنه {colorTone}، بينما الحالة تبقى {condTone}.',
      'عام البناء {year}، والموقع {area}، وعدد الغرف {rooms}.',
      '{colorTone} يرافق اللون {color}، و{yearTone} تؤكّد العناية.',
      'الوحدة من عام {year}، وهي في {area} بحالة {condTone}.',
      '{condTone} في الفراغات، مع غرف بعدد {rooms} ولمسة {colorTone}.',
      'عام {year} يحافظ على {yearTone}، والطابق {floor} واضح في الوصف.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      '{price} دينار، مع تفاوض معقول. {close}.',
      'يُطلب مقابل العقار {price} دينار. {close}.',
      'القيمة المعروضة {price} دينار لمن يقدّر حالة {condTone}. {close}.',
      'السعر {price} دينار، وهو يعكس {yearTone}. {close}.',
      '{close}، والسعر المحدد {price} دينار.',
      'العرض قائم على {price} دينار بحالة {condTone}. {close}.',
      'من يجد في {hook} ما يناسبه فالسعر {price} دينار. {close}.',
      'السعر {price} دينار، والتفاوض يبقى ضمن المعقول. {close}.',
      'تُعرض الوحدة بمبلغ {price} دينار. {close}.',
      '{price} دينار هو المبلغ المطلوب الآن. {close}.',
      'السعر المعلن {price} دينار لمن يبحث عن {hook} في {area}. {close}.',
    ],
  },

  // ═══════════════════════════════════════════════
  // MOBILES
  // ═══════════════════════════════════════════════
  'mobiles': {
    titleTemplates: [
      '{make} {model} {year} سعة {storage} — {hook}',
      '{year} {make} {model} {color} — {hook}',
      '{make} {model} — {hook}',
      '{make} {model} {year} بحالة {condTone}',
      'فرصة {make} {model} {storage} — {hook}',
      '{color} {make} {model} موديل {year}',
      '{make} {model} {storage} {year} — {hook}',
      '{hook} في {make} {model} {year}',
      '{make} {model} بلون {color} وسعة {storage}',
      '{yearTone} {make} {model} — {close}',
      '{make} {model} {condTone} سعة {storage}',
      'عرض {make} {model} {storage} — {hook}',
    ],
    paragraph1: [
      '{open} {make} {model} {year} بسعة {storage}، {hook}.',
      'هاتف {make} {model} موديل {year} بلون {color}، {yearTone}.',
      '{yearTone}، و{make} {model} بسعة {storage} يجسّد {hook}.',
      'يُعرض {make} {model} {year} بحالة {condTone}، {hook}.',
      'يجمع {make} {model} بين لون {color} وسعة {storage}.',
      '{hook}، وهذا {make} {model} موديل {year} يثبت ذلك.',
      'من يمسك {make} {model} {year} يلحظ حالة {condTone} في البدن.',
      'تبدأ التجربة مع {make} {model} بلون {color}، {hook}.',
      '{colorTone}، ويأتي {make} {model} موديل {year} بما يناسب الوصف.',
      'يضع {make} {model} {year} استخداماً واضحاً، {hook}.',
      '{yearTone} تتجلى في {make} {model} ذي السعة {storage}.',
      'هاتف {make} {model} بلون {color}، {hook}.',
    ],
    paragraph2: [
      'الجهاز بلون {color}، {colorTone}. السعة {storage} والحالة {condTone}.',
      '{colorTone}، وسعة {storage} تناسب الاستخدام. {yearTone}.',
      'موديل {year}، بلون {color} وحالة {condTone}.',
      'السعة {storage}، واللون {color} يمنح {colorTone}.',
      '{yearTone} يظهر في التفاصيل، والحالة العامة {condTone}.',
      'الهيكل بلون {color} يعكس {condTone}، والسعة {storage}.',
      'يعمل الجهاز بسعة {storage}، بينما اللون {color} يبقى {colorTone}.',
      'السعة {storage}، والموديل {year}، والحالة العامة {condTone}.',
      '{colorTone} يرافق اللون {color}، و{yearTone} تؤكّد العناية.',
      'الجهاز موديل {year}، وهو بلون {color} بحالة {condTone}.',
      '{condTone} في البدن، مع سعة {storage} ولمسة {colorTone}.',
      'موديل {year} يحافظ على {yearTone}، والسعة {storage} موثّقة.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      '{price} دينار، مع تفاوض معقول. {close}.',
      'يُطلب مقابل الجهاز {price} دينار. {close}.',
      'القيمة المعروضة {price} دينار لمن يقدّر حالة {condTone}. {close}.',
      'السعر {price} دينار، وهو يعكس {yearTone}. {close}.',
      '{close}، والسعر المحدد {price} دينار.',
      'العرض قائم على {price} دينار بحالة {condTone}. {close}.',
      'من يجد في {hook} ما يناسبه فالسعر {price} دينار. {close}.',
      'السعر {price} دينار، والتفاوض يبقى ضمن المعقول. {close}.',
      'يُعرض الجهاز بمبلغ {price} دينار. {close}.',
      '{price} دينار هو المبلغ المطلوب الآن. {close}.',
      'السعر المعلن {price} دينار لمن يبحث عن {hook}. {close}.',
    ],
  },
  // ═══════════════════════════════════════════════
  // FURNITURE
  // ═══════════════════════════════════════════════
  'furniture': {
    titleTemplates: [
      '{make} {model} {year} بلون {color} — {hook}',
      '{year} {make} {model} {color} — {hook}',
      '{make} {model} — {hook}',
      '{make} {model} {year} بحالة {condTone}',
      'فرصة {make} {model} {color} — {hook}',
      '{color} {make} {model} من عام {year}',
      '{make} {model} {condTone} {year} — {hook}',
      '{hook} في {make} {model} {year}',
      '{make} {model} بلون {color} وحالة {condTone}',
      '{colorTone} {make} {model} {color}',
      '{condTone} أثاث {make} {model}',
      '{make} {model} {year} {hook}',
    ],
    paragraph1: [
      '{open} {make} {model} {year} بلون {color}، {hook}.',
      'قطعة {make} {model} من عام {year} بلون {color}، {yearTone}.',
      '{yearTone}، و{make} {model} بلون {color} يجسّد {hook}.',
      'تُعرض {make} {model} {year} بحالة {condTone}، {hook}.',
      'يجمع {make} {model} بين لون {color} وحالة {condTone}.',
      '{hook}، وهذه القطعة {make} {model} من عام {year} تثبت ذلك.',
      'من يرى {make} {model} {year} يلحظ حالة {condTone} في الخامة.',
      'تبدأ الجلسة مع {make} {model} بلون {color}، {hook}.',
      '{colorTone}، وتأتي {make} {model} من عام {year} بما يناسب الوصف.',
      'تضع {make} {model} {year} حضوراً واضحاً في المكان، {hook}.',
      '{yearTone} تتجلى في {make} {model} ذات اللون {color}.',
      'أثاث {make} {model} بلون {color}، {hook}.',
    ],
    paragraph2: [
      'القطعة بلون {color}، {colorTone}. الحالة العامة {condTone}.',
      '{colorTone}، وعام الصنع {year} يبقى {yearTone}.',
      'من عام {year}، بلون {color} وحالة {condTone}.',
      'اللون {color} يمنح {colorTone}، والحالة {condTone}.',
      '{yearTone} يظهر في التفاصيل، والحالة العامة {condTone}.',
      'السطح بلون {color} يعكس {condTone}، والموديل {model}.',
      'صُنعت القطعة عام {year}، بينما اللون {color} يبقى {colorTone}.',
      'الموديل {model}، والعام {year}، والحالة العامة {condTone}.',
      '{colorTone} يرافق اللون {color}، و{yearTone} تؤكّد العناية.',
      'خامة {make} {model} تناسب من يقدّر حالة {condTone}.',
      'القطعة من عام {year}، وهي بلون {color} بحالة {condTone}.',
      'هيكل {color} بحالة {condTone}، والصنع {make} واضح.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      '{price} دينار، مع تفاوض معقول. {close}.',
      'يُطلب مقابل القطعة {price} دينار. {close}.',
      'القيمة المعروضة {price} دينار لمن يقدّر حالة {condTone}. {close}.',
      'السعر {price} دينار، وهو يعكس {yearTone}. {close}.',
      '{close}، والسعر المحدد {price} دينار.',
      'العرض قائم على {price} دينار بحالة {condTone}. {close}.',
      'من يجد في {hook} ما يناسبه فالسعر {price} دينار. {close}.',
      'السعر {price} دينار، والتفاوض يبقى ضمن المعقول. {close}.',
      'تُعرض القطعة بمبلغ {price} دينار. {close}.',
      '{price} دينار هو المبلغ المطلوب الآن. {close}.',
      'السعر المعلن {price} دينار لمن يبحث عن {hook}. {close}.',
    ],
  },

  // ═══════════════════════════════════════════════
  // JOBS
  // ═══════════════════════════════════════════════
  'jobs': {
    titleTemplates: [
      '{jobTitle} بخبرة {exp} — {hook}',
      '{jobTitle} في {area} — {hook}',
      '{jobTitle} — {hook}',
      '{jobTitle} خبرة {exp} بحالة {condTone}',
      'فرصة {jobTitle} في {area} — {hook}',
      '{area} {jobTitle} خبرة {exp}',
      '{jobTitle} {exp} {area} — {hook}',
      '{hook} لوظيفة {jobTitle} في {area}',
      '{jobTitle} بخبرة {exp} وبيئة {condTone}',
      '{jobTitle} ضمن {area} خبرة {exp}',
      '{condTone} فرصة {jobTitle} {exp}',
      '{jobTitle} {area} — {hook}',
    ],
    paragraph1: [
      '{open} وظيفة {jobTitle} بخبرة {exp} في {area}، {hook}.',
      'تُعلن جهة العمل عن {jobTitle} في {area}، {hook}.',
      'خبرة {exp} مطلوبة لدور {jobTitle}، {hook}.',
      'يُطرح دور {jobTitle} في {area} بوصف {condTone}، {hook}.',
      'يجمع الإعلان بين مسمى {jobTitle} وموقع {area}.',
      '{hook}، ووظيفة {jobTitle} بخبرة {exp} تثبت جدية العرض.',
      'من يقرأ وصف {jobTitle} يلحظ خبرة {exp} ضمن {area}.',
      'تبدأ الفرصة من {jobTitle} في {area}، {hook}.',
      'بيئة العمل توصف بأنها {condTone}، ودور {jobTitle} يناسب {hook}.',
      'يضع إعلان {jobTitle} مساراً واضحاً بخبرة {exp}، {hook}.',
      'الخبرة {exp} تتجلى في متطلبات {jobTitle} داخل {area}.',
      'دور {jobTitle} في {area}، {hook}.',
    ],
    paragraph2: [
      'المسمى {jobTitle}، والموقع {area}، والخبرة المطلوبة {exp}.',
      'بيئة العمل {condTone}، والخبرة {exp} مذكورة بوضوح.',
      'يُمارس الدور في {area}، تحت مسمى {jobTitle} بخبرة {exp}.',
      'الخبرة {exp} تناسب {jobTitle}، والموقع يبقى {area}.',
      'الوصف العام {condTone}، والمسمى {jobTitle} محدد.',
      'موقع العمل {area} يعكس احتياجاً لخبرة {exp} في {jobTitle}.',
      'يتطلب الدور خبرة {exp}، بينما البيئة تبقى {condTone}.',
      'المسمى {jobTitle}، والمنطقة {area}، والخبرة {exp}.',
      'حالة العرض {condTone} ترافق خبرة {exp} في {jobTitle}.',
      'خبرة {exp} تناسب من يستهدف {jobTitle} داخل {area}.',
      'الدور مسمى {jobTitle}، وهو في {area} بخبرة {exp}.',
      'مسمى {jobTitle} بخبرة {exp}، والبيئة {condTone}.',
    ],
    paragraph3: [
      'الأجر {price} دينار قابل للنقاش المعقول. {close}.',
      '{price} دينار، مع نقاش معقول حول الأجر. {close}.',
      'يُعرض مقابل الدور {price} دينار. {close}.',
      'القيمة المعروضة {price} دينار لمن يملك خبرة {exp}. {close}.',
      'الأجر {price} دينار، وهو يعكس دور {jobTitle}. {close}.',
      '{close}، والأجر المحدد {price} دينار.',
      'العرض قائم على {price} دينار في بيئة {condTone}. {close}.',
      'من يجد في {hook} ما يناسبه فالأجر {price} دينار. {close}.',
      'الأجر {price} دينار، والنقاش يبقى ضمن المعقول. {close}.',
      'يُعلن الدور بأجر {price} دينار. {close}.',
      'الأجر المعلن {price} دينار لمن يبحث عن {hook}. {close}.',
      '{price} دينار هو الأجر المذكور الآن. {close}.',
    ],
  },

  // ═══════════════════════════════════════════════
  // SERVICES
  // ═══════════════════════════════════════════════
  'services': {
    titleTemplates: [
      '{jobTitle} في {area} — {hook}',
      '{jobTitle} بخبرة {exp} — {hook}',
      '{jobTitle} — {hook}',
      '{jobTitle} ضمن {area} بحالة {condTone}',
      'فرصة خدمة {jobTitle} — {hook}',
      '{area} خدمة {jobTitle} خبرة {exp}',
      '{jobTitle} {exp} {area} — {hook}',
      '{hook} مع خدمة {jobTitle} في {area}',
      '{jobTitle} بخبرة {exp} وأداء {condTone}',
      '{jobTitle} تغطي {area} بخبرة {exp}',
      '{condTone} خدمة {jobTitle} في {area}',
      '{jobTitle} {area} — {close}',
    ],
    paragraph1: [
      '{open} خدمة {jobTitle} بخبرة {exp} في {area}، {hook}.',
      'تُقدَّم خدمة {jobTitle} داخل {area}، {hook}.',
      'خبرة {exp} تسند خدمة {jobTitle}، {hook}.',
      'تُطرح خدمة {jobTitle} في {area} بوصف {condTone}، {hook}.',
      'يجمع العرض بين خدمة {jobTitle} ونطاق {area}.',
      '{hook}، وخدمة {jobTitle} بخبرة {exp} تثبت جدية التنفيذ.',
      'من يراجع خدمة {jobTitle} يلحظ خبرة {exp} ضمن {area}.',
      'تبدأ الخدمة من {jobTitle} في {area}، {hook}.',
      'أسلوب التنفيذ يوصف بأنه {condTone}، وخدمة {jobTitle} تناسب {hook}.',
      'تضع خدمة {jobTitle} مساراً واضحاً بخبرة {exp}، {hook}.',
      'الخبرة {exp} تتجلى في تنفيذ {jobTitle} داخل {area}.',
      'خدمة {jobTitle} في {area}، {hook}.',
    ],
    paragraph2: [
      'الخدمة {jobTitle}، والنطاق {area}، والخبرة {exp}.',
      'أسلوب العمل {condTone}، والخبرة {exp} مذكورة بوضوح.',
      'يُنفَّذ العمل في {area}، تحت عنوان {jobTitle} بخبرة {exp}.',
      'الخبرة {exp} تناسب {jobTitle}، والنطاق يبقى {area}.',
      'الوصف العام {condTone}، والخدمة {jobTitle} محددة.',
      'نطاق {area} يعكس احتياجاً لخبرة {exp} في {jobTitle}.',
      'تتطلب الخدمة خبرة {exp}، بينما الأسلوب يبقى {condTone}.',
      'العنوان {jobTitle}، والمنطقة {area}، والخبرة {exp}.',
      'حالة التنفيذ {condTone} ترافق خبرة {exp} في {jobTitle}.',
      'خبرة {exp} تناسب من يطلب {jobTitle} داخل {area}.',
      'العمل بعنوان {jobTitle}، وهو في {area} بخبرة {exp}.',
      'خدمة {jobTitle} بخبرة {exp}، والأسلوب {condTone}.',
    ],
    paragraph3: [
      'الأجر {price} دينار قابل للتفاوض المعقول. {close}.',
      '{price} دينار، مع تفاوض معقول. {close}.',
      'يُطلب مقابل الخدمة {price} دينار. {close}.',
      'القيمة المعروضة {price} دينار لمن يقدّر خبرة {exp}. {close}.',
      'السعر {price} دينار، وهو يعكس خدمة {jobTitle}. {close}.',
      '{close}، والسعر المحدد {price} دينار.',
      'العرض قائم على {price} دينار بأسلوب {condTone}. {close}.',
      'من يجد في {hook} ما يناسبه فالسعر {price} دينار. {close}.',
      'السعر {price} دينار، والتفاوض يبقى ضمن المعقول. {close}.',
      'تُقدَّم الخدمة بمبلغ {price} دينار. {close}.',
      'السعر المعلن {price} دينار لمن يبحث عن {hook}. {close}.',
      '{price} دينار هو المبلغ المطلوب الآن. {close}.',
    ],
  },

  // ═══════════════════════════════════════════════
  // CLEANING
  // ═══════════════════════════════════════════════
  'cleaning': {
    titleTemplates: [
      'تنظيف {area} — {hook}',
      '{jobTitle} بخبرة {exp} — {hook}',
      'خدمة تنظيف {area} — {hook}',
      '{jobTitle} ضمن {area} بحالة {condTone}',
      'فرصة تنظيف {area} — {hook}',
      '{area} تنظيف {jobTitle} خبرة {exp}',
      '{jobTitle} {exp} لتنظيف {area} — {hook}',
      '{hook} مع تنظيف {area} عبر {jobTitle}',
      '{jobTitle} بخبرة {exp} ونتيجة {condTone}',
      'تنظيف {area} — {close}',
      '{jobTitle} تغطي {area} بخبرة {exp}',
      '{condTone} تنظيف في {area}',
    ],
    paragraph1: [
      '{open} تنظيف بعنوان {jobTitle} بخبرة {exp} في {area}، {hook}.',
      'تُقدَّم أعمال التنظيف في {area} عبر {jobTitle}، {hook}.',
      'خبرة {exp} تسند تنظيف {area}، {hook}.',
      'يُطرح تنظيف {jobTitle} في {area} بوصف {condTone}، {hook}.',
      'يجمع العرض بين خدمة {jobTitle} ونطاق تنظيف {area}.',
      '{hook}، وتنظيف {area} بخبرة {exp} يثبت جدية التنفيذ.',
      'من يراجع خدمة {jobTitle} يلحظ خبرة {exp} ضمن {area}.',
      'تبدأ أعمال النظافة من {area} عبر {jobTitle}، {hook}.',
      'النتيجة توصف بأنها {condTone}، وخدمة {jobTitle} تناسب {hook}.',
      'تضع خدمة {jobTitle} مساراً واضحاً لتنظيف {area}، {hook}.',
      'الخبرة {exp} تتجلى في تنظيف {jobTitle} داخل {area}.',
      'تنظيف {area} عبر {jobTitle}، {hook}.',
    ],
    paragraph2: [
      'الخدمة {jobTitle}، والنطاق {area}، والخبرة {exp}.',
      'نتيجة العمل {condTone}، والخبرة {exp} مذكورة بوضوح.',
      'يُنفَّذ التنظيف في {area}، تحت عنوان {jobTitle} بخبرة {exp}.',
      'الخبرة {exp} تناسب {jobTitle}، والنطاق يبقى {area}.',
      'الوصف العام {condTone}، وخدمة التنظيف {jobTitle} محددة.',
      'نطاق {area} يعكس احتياجاً لخبرة {exp} في {jobTitle}.',
      'تتطلب الخدمة خبرة {exp}، بينما النتيجة تبقى {condTone}.',
      'العنوان {jobTitle}، والمنطقة {area}، والخبرة {exp}.',
      'حالة التنفيذ {condTone} ترافق خبرة {exp} في تنظيف {area}.',
      'خبرة {exp} تناسب من يطلب {jobTitle} داخل {area}.',
      'العمل بعنوان {jobTitle}، وهو تنظيف في {area} بخبرة {exp}.',
      'تنظيف {jobTitle} بخبرة {exp}، والنتيجة {condTone}.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      '{price} دينار، مع تفاوض معقول. {close}.',
      'يُطلب مقابل التنظيف {price} دينار. {close}.',
      'القيمة المعروضة {price} دينار لمن يقدّر خبرة {exp}. {close}.',
      'السعر {price} دينار، وهو يعكس تنظيف {area}. {close}.',
      '{close}، والسعر المحدد {price} دينار.',
      'العرض قائم على {price} دينار بنتيجة {condTone}. {close}.',
      'من يجد في {hook} ما يناسبه فالسعر {price} دينار. {close}.',
      'السعر {price} دينار، والتفاوض يبقى ضمن المعقول. {close}.',
      'تُقدَّم الخدمة بمبلغ {price} دينار. {close}.',
      'السعر المعلن {price} دينار لمن يبحث عن {hook}. {close}.',
      '{price} دينار هو المبلغ المطلوب الآن. {close}.',
    ],
  },

  // ═══════════════════════════════════════════════
  // HANDYMEN
  // ═══════════════════════════════════════════════
  'handymen': {
    titleTemplates: [
      '{jobTitle} في {area} — {hook}',
      '{jobTitle} بخبرة {exp} — {hook}',
      'فني {jobTitle} — {hook}',
      '{jobTitle} ضمن {area} بحالة {condTone}',
      'فرصة صيانة {jobTitle} — {hook}',
      '{area} أعمال {jobTitle} خبرة {exp}',
      '{jobTitle} {exp} في {area} — {hook}',
      '{hook} مع فني {jobTitle} داخل {area}',
      '{jobTitle} بخبرة {exp} وتنفيذ {condTone}',
      '{jobTitle} تغطي {area} بخبرة {exp}',
      '{condTone} {jobTitle} خبرة {exp}',
      '{jobTitle} {exp} {hook}',
    ],
    paragraph1: [
      '{open} أعمال {jobTitle} بخبرة {exp} في {area}، {hook}.',
      'يتولى فني {jobTitle} المهام داخل {area}، {hook}.',
      'خبرة {exp} تسند تنفيذ {jobTitle}، {hook}.',
      'تُطرح خدمة {jobTitle} في {area} بوصف {condTone}، {hook}.',
      'يجمع العرض بين مهارة {jobTitle} ونطاق {area}.',
      '{hook}، وأعمال {jobTitle} بخبرة {exp} تثبت جدية التنفيذ.',
      'من يراجع خدمة {jobTitle} يلحظ خبرة {exp} ضمن {area}.',
      'تبدأ الصيانة من {jobTitle} في {area}، {hook}.',
      'التنفيذ يوصف بأنه {condTone}، وخدمة {jobTitle} تناسب {hook}.',
      'تضع خدمة {jobTitle} مساراً واضحاً بخبرة {exp}، {hook}.',
      'الخبرة {exp} تتجلى في تنفيذ {jobTitle} داخل {area}.',
      'أعمال {jobTitle} في {area}، {hook}.',
    ],
    paragraph2: [
      'المهنة {jobTitle}، والنطاق {area}، والخبرة {exp}.',
      'أسلوب التنفيذ {condTone}، والخبرة {exp} مذكورة بوضوح.',
      'تُنجز الأعمال في {area}، تحت عنوان {jobTitle} بخبرة {exp}.',
      'الخبرة {exp} تناسب {jobTitle}، والنطاق يبقى {area}.',
      'الوصف العام {condTone}، والخدمة {jobTitle} محددة.',
      'نطاق {area} يعكس احتياجاً لخبرة {exp} في {jobTitle}.',
      'تتطلب الأعمال خبرة {exp}، بينما التنفيذ يبقى {condTone}.',
      'العنوان {jobTitle}، والمنطقة {area}، والخبرة {exp}.',
      'حالة التنفيذ {condTone} ترافق خبرة {exp} في {jobTitle}.',
      'خبرة {exp} تناسب من يطلب فنياً في {jobTitle} داخل {area}.',
      'العمل بعنوان {jobTitle}، وهو في {area} بخبرة {exp}.',
      'أعمال {jobTitle} بخبرة {exp}، والتنفيذ {condTone}.',
    ],
    paragraph3: [
      'الأجر {price} دينار قابل للتفاوض المعقول. {close}.',
      '{price} دينار، مع تفاوض معقول. {close}.',
      'يُطلب مقابل العمل {price} دينار. {close}.',
      'القيمة المعروضة {price} دينار لمن يقدّر خبرة {exp}. {close}.',
      'السعر {price} دينار، وهو يعكس أعمال {jobTitle}. {close}.',
      '{close}، والسعر المحدد {price} دينار.',
      'العرض قائم على {price} دينار بتنفيذ {condTone}. {close}.',
      'من يجد في {hook} ما يناسبه فالسعر {price} دينار. {close}.',
      'السعر {price} دينار، والتفاوض يبقى ضمن المعقول. {close}.',
      'تُقدَّم الأعمال بمبلغ {price} دينار. {close}.',
      'السعر المعلن {price} دينار لمن يبحث عن {hook}. {close}.',
      '{price} دينار هو المبلغ المطلوب الآن. {close}.',
    ],
  },

  // ═══════════════════════════════════════════════
  // PROJECTS
  // ═══════════════════════════════════════════════
  'projects': {
    titleTemplates: [
      'مشروع {jobTitle} في {area} — {hook}',
      '{jobTitle} بخبرة {exp} — {hook}',
      'مشروع {jobTitle} — {hook}',
      '{jobTitle} ضمن {area} بحالة {condTone}',
      'فرصة مشروع {area} — {hook}',
      '{area} مشروع {jobTitle} خبرة {exp}',
      '{jobTitle} {exp} لمشروع {area} — {hook}',
      '{hook} في مشروع {jobTitle} داخل {area}',
      '{jobTitle} بخبرة {exp} ومرحلة {condTone}',
      'مشروع {area} — {close}',
      '{jobTitle} يغطي {area} بخبرة {exp}',
      '{condTone} مشروع {jobTitle} في {area}',
    ],
    paragraph1: [
      '{open} مشروع {jobTitle} بخبرة {exp} في {area}، {hook}.',
      'يُطرح مشروع {jobTitle} داخل {area}، {hook}.',
      'خبرة {exp} تسند مشروع {jobTitle}، {hook}.',
      'يُعرض مشروع {jobTitle} في {area} بوصف {condTone}، {hook}.',
      'يجمع الطرح بين عنوان {jobTitle} ونطاق {area}.',
      '{hook}، ومشروع {jobTitle} بخبرة {exp} يثبت جدية الفكرة.',
      'من يراجع مشروع {jobTitle} يلحظ خبرة {exp} ضمن {area}.',
      'تبدأ الفرصة من مشروع {jobTitle} في {area}، {hook}.',
      'مرحلة العمل توصف بأنها {condTone}، ومشروع {jobTitle} يناسب {hook}.',
      'يضع مشروع {jobTitle} مساراً واضحاً بخبرة {exp}، {hook}.',
      'الخبرة {exp} تتجلى في مشروع {jobTitle} داخل {area}.',
      'مشروع {jobTitle} في {area}، {hook}.',
    ],
    paragraph2: [
      'المشروع {jobTitle}، والنطاق {area}، والخبرة {exp}.',
      'مرحلة العمل {condTone}، والخبرة {exp} مذكورة بوضوح.',
      'يُقام المشروع في {area}، تحت عنوان {jobTitle} بخبرة {exp}.',
      'الخبرة {exp} تناسب {jobTitle}، والنطاق يبقى {area}.',
      'الوصف العام {condTone}، والمشروع {jobTitle} محدد.',
      'نطاق {area} يعكس احتياجاً لخبرة {exp} في {jobTitle}.',
      'يتطلب المشروع خبرة {exp}، بينما المرحلة تبقى {condTone}.',
      'العنوان {jobTitle}، والمنطقة {area}، والخبرة {exp}.',
      'حالة المشروع {condTone} ترافق خبرة {exp} في {jobTitle}.',
      'خبرة {exp} تناسب من يدخل مشروع {jobTitle} داخل {area}.',
      'العمل بعنوان {jobTitle}، وهو في {area} بخبرة {exp}.',
      'مشروع {jobTitle} بخبرة {exp}، والمرحلة {condTone}.',
    ],
    paragraph3: [
      'القيمة {price} دينار قابلة للتفاوض المعقول. {close}.',
      '{price} دينار، مع تفاوض معقول. {close}.',
      'يُطلب للدخول {price} دينار. {close}.',
      'القيمة المعروضة {price} دينار لمن يقدّر خبرة {exp}. {close}.',
      'المبلغ {price} دينار، وهو يعكس مشروع {jobTitle}. {close}.',
      '{close}، والمبلغ المحدد {price} دينار.',
      'العرض قائم على {price} دينار بمرحلة {condTone}. {close}.',
      'من يجد في {hook} ما يناسبه فالمبلغ {price} دينار. {close}.',
      'المبلغ {price} دينار، والتفاوض يبقى ضمن المعقول. {close}.',
      'يُطرح المشروع بمبلغ {price} دينار. {close}.',
      'المبلغ المعلن {price} دينار لمن يبحث عن {hook}. {close}.',
      '{price} دينار هو المبلغ المذكور الآن. {close}.',
    ],
  },
};
