// RULE-14-EXCEPTION: Static taxonomy
// Phase 3A — 15 additional categories (watches..projects)
// Merged into base files at runtime.

export const TONE_LIBRARY_EXTRA: Record<string, {
  readonly openings: readonly string[];
  readonly hooks: readonly string[];
  readonly closings: readonly string[];
  readonly titleHooks: readonly string[];
}> = {
  watches: {
    openings: ['للبيع', 'معروضة للبيع', 'فرصة مختارة', 'ساعة معروضة'],
    hooks: ['ساعة أنيقة تليق بالمناسبات والاستخدام اليومي', 'خيار عملي لمن يبحث عن وضوح القراءة', 'قطعة مختارة تصلح للاقتناء والإهداء', 'تصميم متوازن يناسب الاستخدام المتكرر'],
    closings: ['الساعة جاهزة للمعاينة', 'العرض متاح للجادين', 'يمكن المعاينة قبل الاتفاق'],
    titleHooks: ['أنيقة ومميزة', 'فرصة واضحة', 'عملية وأنيقة', 'مناسبة للإهداء', 'اختيار متقن'],
  },
  computers: {
    openings: ['للبيع', 'جهاز معروض للبيع', 'فرصة عملية', 'حاسوب متوفر'],
    hooks: ['جهاز مناسب للدراسة والعمل اليومي', 'خيار عملي لمن يحتاج استخداما مستقرا', 'حاسوب جاهز للاستخدام المكتبي والشخصي', 'اختيار واضح لمن يبحث عن جهاز للاستخدام المتكرر'],
    closings: ['الجهاز جاهز للمعاينة والتشغيل', 'العرض للجادين', 'يمكن تجربة الجهاز قبل الاتفاق'],
    titleHooks: ['عملي للدراسة', 'فرصة واضحة', 'جاهز للاستخدام', 'مناسب للعمل', 'اختيار متزن'],
  },
  electronics: {
    openings: ['للبيع', 'معروض للبيع', 'فرصة منزلية', 'جهاز متوفر'],
    hooks: ['جهاز منزلي عملي للاستخدام اليومي', 'خيار مناسب للبيت والمكتب', 'قطعة واضحة الوظيفة وسهلة الاستخدام', 'اختيار مفيد لمن يبحث عن جهاز جاهز'],
    closings: ['الجهاز جاهز للمعاينة', 'العرض متاح للجادين', 'يمكن الفحص قبل الاتفاق'],
    titleHooks: ['عملي للبيت', 'فرصة واضحة', 'سهل الاستخدام', 'جاهز للعمل', 'اختيار مفيد'],
  },
  fashion: {
    openings: ['للبيع', 'معروضة للبيع', 'قطعة مختارة', 'قطعة متوفرة'],
    hooks: ['قطعة أنيقة تناسب الإطلالة اليومية', 'خيار مريح للاستخدام المتكرر', 'تصميم واضح يليق بالخروج والمناسبات', 'اختيار عملي لمن يبحث عن مظهر مرتب'],
    closings: ['القطعة جاهزة للمعاينة', 'العرض للجادين', 'يمكن قياس القطعة قبل الاتفاق'],
    titleHooks: ['أنيقة ومرتبة', 'مريحة يوميا', 'فرصة واضحة', 'مناسبة للخروج', 'اختيار عملي'],
  },
  beauty: {
    openings: ['للبيع', 'معروض للبيع', 'خيار عناية', 'منتج متوفر'],
    hooks: ['منتج عناية مناسب للاستخدام المنزلي', 'خيار عملي لروتين العناية اليومي', 'قطعة مختارة للاستخدام الشخصي', 'اختيار واضح لمن يرتب عنايته في البيت'],
    closings: ['المنتج جاهز للمعاينة', 'العرض للجادين', 'يمكن الاطلاع قبل الاتفاق'],
    titleHooks: ['عناية منزلية', 'استخدام شخصي', 'فرصة واضحة', 'عملي يوميا', 'اختيار مرتب'],
  },
  kids: {
    openings: ['للبيع', 'معروض للبيع', 'مستلزم أسري', 'قطعة متوفرة'],
    hooks: ['قطعة مناسبة لاستخدام الأطفال في البيت', 'خيار عملي للأسرة', 'اختيار واضح لمن يجهز مستلزمات الطفل', 'قطعة مريحة للاستخدام اليومي مع الأطفال'],
    closings: ['القطعة جاهزة للمعاينة', 'العرض للجادين', 'يمكن الفحص قبل الاتفاق'],
    titleHooks: ['مناسبة للبيت', 'عملية للأسرة', 'فرصة واضحة', 'استخدام يومي', 'اختيار مرتب'],
  },
  pets: {
    openings: ['متاح للانتقال', 'معروض للجادين', 'متوفر للرعاية', 'فرصة لمن يعتني'],
    hooks: ['أليف متاح للانتقال إلى بيت مناسب', 'خيار لمن يبحث عن رفيق منزلي', 'متاح للجادين الراغبين بالرعاية', 'يحتاج بيتا مستقرا ومتابعة منتظمة'],
    closings: ['المعاينة متاحة للجادين', 'الانتقال بعد الاتفاق الواضح', 'يمكن الزيارة قبل الاتفاق'],
    titleHooks: ['رعاية منزلية', 'للجادين', 'فرصة واضحة', 'بيت مستقر', 'معاينة أولا'],
  },
  sports: {
    openings: ['للبيع', 'معروضة للبيع', 'معدة رياضية', 'قطعة متوفرة'],
    hooks: ['معدة رياضية مناسبة للتدريب المنتظم', 'خيار عملي للنشاط المنزلي والنادي', 'قطعة جاهزة للاستخدام الرياضي', 'اختيار واضح لمن يبدأ أو يواصل التدريب'],
    closings: ['المعدة جاهزة للمعاينة', 'العرض للجادين', 'يمكن الفحص قبل الاتفاق'],
    titleHooks: ['للتدريب المنتظم', 'عملية وواضحة', 'فرصة رياضية', 'جاهزة للاستخدام', 'اختيار متزن'],
  },
  books: {
    openings: ['للبيع', 'نسخة معروضة للبيع', 'إضافة للمكتبة', 'نسخة متوفرة'],
    hooks: ['كتاب متاح للقراءة والاقتناء', 'خيار مناسب للمكتبة المنزلية', 'نسخة واضحة لمن يبحث عن هذا العنوان', 'اختيار مفيد للقراءة الهادئة'],
    closings: ['النسخة جاهزة للمعاينة', 'العرض للجادين', 'يمكن الاطلاع قبل الاتفاق'],
    titleHooks: ['للقراءة والاقتناء', 'نسخة واضحة', 'فرصة مكتبية', 'عنوان متاح', 'اختيار هادئ'],
  },
  'home-garden': {
    openings: ['للبيع', 'معروض للبيع', 'مستلزم بيت وحديقة', 'قطعة متوفرة'],
    hooks: ['مستلزم عملي للعناية بالبيت أو الحديقة', 'خيار مناسب لترتيب المساحة الخارجية', 'قطعة مفيدة للاستخدام المنزلي الظاهر', 'اختيار واضح لمن يجهز الحديقة أو الفناء'],
    closings: ['القطعة جاهزة للمعاينة', 'العرض للجادين', 'يمكن الفحص قبل الاتفاق'],
    titleHooks: ['للبيت والحديقة', 'عملي وواضح', 'فرصة منزلية', 'جاهز للاستخدام', 'اختيار مفيد'],
  },
  krakeeb: {
    openings: ['للبيع', 'أغراض معروضة للبيع', 'كراكيب متنوعة', 'أغراض متوفرة'],
    hooks: ['أغراض متنوعة متاحة بحالتها الظاهرة', 'قطع لمن يبحث عن استخدام عملي', 'مجموعة معروضة كما هي للجادين', 'فرصة لمن يحتاج هذه الأغراض بعد المعاينة'],
    closings: ['الأغراض جاهزة للمعاينة', 'العرض للجادين', 'الحالة كما تظهر عند الفحص'],
    titleHooks: ['أغراض متنوعة', 'بحالتها الظاهرة', 'فرصة واضحة', 'معاينة أولا', 'استخدام عملي'],
  },
  services: {
    openings: ['خدمة متاحة', 'عرض خدمة', 'متوفر حسب الطلب', 'خدمة للجادين'],
    hooks: ['خدمة واضحة لمن يحتاج إنجاز العمل', 'خيار عملي حسب طبيعة الطلب', 'تنفيذ متاح ضمن النطاق المذكور', 'خدمة مناسبة لمن يبحث عن إنجاز مباشر'],
    closings: ['الخدمة متاحة للاتفاق بعد توضيح الطلب', 'العرض للجادين', 'نطاق العمل يتحدد قبل البدء'],
    titleHooks: ['خدمة واضحة', 'حسب الطلب', 'إنجاز مباشر', 'للجادين', 'نطاق محدد'],
  },
  cleaning: {
    openings: ['خدمة تنظيف', 'تنظيف متاح', 'عرض تنظيف', 'خدمة منزلية'],
    hooks: ['تنظيف منزلي حسب الاتفاق والمساحة', 'خيار عملي لترتيب البيت', 'خدمة واضحة للمنازل والمكاتب', 'مناسبة لمن يحتاج تنظيفا دوريا أو شاملا'],
    closings: ['الموعد يتحدد بعد الاتفاق', 'العرض للجادين', 'نطاق التنظيف يوضح قبل الحضور'],
    titleHooks: ['تنظيف منزلي', 'حسب الاتفاق', 'للبيت والمكتب', 'خدمة واضحة', 'ترتيب عملي'],
  },
  handymen: {
    openings: ['خدمة صيانة', 'فني متاح', 'إصلاح منزلي', 'صيانة حسب الطلب'],
    hooks: ['صيانة منزلية حسب نوع العمل الظاهر', 'خيار عملي للإصلاحات البسيطة والمتوسطة', 'فني متاح لمعاينة العمل قبل التنفيذ', 'خدمة واضحة لمن يحتاج إصلاحا منزليا'],
    closings: ['المعاينة تسبق التنفيذ', 'العرض للجادين', 'نطاق الإصلاح يتحدد بعد الكشف'],
    titleHooks: ['صيانة منزلية', 'كشف أولا', 'إصلاح واضح', 'حسب العطل', 'للجادين'],
  },
  projects: {
    openings: ['مشروع معروض', 'فرصة مشروع', 'متاح للجادين', 'نشاط قائم'],
    hooks: ['مشروع متاح للجادين حسب التفاصيل المعروضة', 'فرصة لمن يبحث عن نشاط قائم', 'مشروع واضح ضمن المعطيات المذكورة', 'خيار لمن يدرس الدخول في نشاط جاهز'],
    closings: ['التفاصيل للجادين بعد المعاينة', 'العرض كما هو دون وعود إضافية', 'الدراسة تسبق أي اتفاق'],
    titleHooks: ['نشاط قائم', 'للجادين', 'فرصة واضحة', 'حسب المعروض', 'معاينة أولا'],
  },
};

export const CATEGORY_TEMPLATES_EXTRA: Record<string, {
  readonly titleTemplates: readonly string[];
  readonly paragraph1: readonly string[];
  readonly paragraph2: readonly string[];
  readonly paragraph3: readonly string[];
}> = {
  watches: {
    titleTemplates: [
      '{make} {model} {year} — {hook}',
      '{make} {model} — {hook}',
      '{make} {model} {color} — {hook}',
      '{make} {year} — {hook}',
      '{model} {color} — {hook}',
      '{make} {model} — {condTone}',
    ],
    paragraph1: [
      '{open} {make} {model} {year}، {hook}.',
      '{open} {make} {model}، {hook}.',
      '{open} {make} {model} {color}، {hook}.',
      '{open} ساعة {make} {model}، {hook}.',
      '{open} {model} من {make}، {hook}.',
      '{open} {make} {year}، {hook}.',
    ],
    paragraph2: [
      'الساعة بلون {color}، {colorTone}. {condTone}. التفاصيل الظاهرة تتضح عند المعاينة.',
      'الموديل {model} من {make}، {yearTone}. {condTone}. القطعة معروضة كما هي دون إضافات.',
      'اللون المذكور {color}. {colorTone}. {yearTone}. القطعة تراجع عند المعاينة.',
      '{condTone}. {colorTone}. الحالة النهائية تثبت بالمعاينة قبل الاتفاق.',
      '{yearTone}. {condTone}. الاستخدام اليومي يظهر من حالة القطعة.',
      'القطعة من {make} وموديلها {model}. {colorTone}. {condTone}. الحالة الظاهرة هي المعتمدة.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة القطعة {price} دينار حسب الاتفاق بعد المعاينة. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. المعاينة متاحة قبل أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
  computers: {
    titleTemplates: [
      '{make} {model} {year} — {hook}',
      '{make} {model} {storage} — {hook}',
      '{make} {model} — {hook}',
      '{make} {model} {color} — {hook}',
      '{model} {year} — {hook}',
      '{make} {storage} — {condTone}',
    ],
    paragraph1: [
      '{open} {make} {model} {year}، {hook}.',
      '{open} {make} {model}، {hook}.',
      '{open} {make} {model} بسعة {storage}، {hook}.',
      '{open} جهاز {make} {model}، {hook}.',
      '{open} {model} {year}، {hook}.',
      '{open} {make} {color}، {hook}.',
    ],
    paragraph2: [
      'الجهاز من {make} وموديله {model}. السعة المذكورة {storage}. {condTone}.',
      '{yearTone}. {condTone}. التجربة القصيرة توضح جاهزية التشغيل قبل الاتفاق.',
      'اللون {color}، {colorTone}. {condTone}. الجهاز معروض كما هو دون قطع إضافية.',
      '{condTone}. {yearTone}. الاستخدام الدراسي والمكتبي يتضح بعد التشغيل.',
      'السعة المذكورة {storage}. {colorTone}. {condTone}. الجهاز معروض كما هو.',
      'الموديل {model} من {make}، {yearTone}. {condTone}. التفاصيل الظاهرة تثبت بالمعاينة.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة الجهاز {price} دينار حسب الاتفاق بعد التجربة. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. التجربة متاحة قبل أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
  electronics: {
    titleTemplates: [
      '{make} {model} {year} — {hook}',
      '{make} {model} — {hook}',
      '{make} {model} {color} — {hook}',
      '{make} {year} — {hook}',
      '{model} {storage} — {hook}',
      '{make} {model} — {condTone}',
    ],
    paragraph1: [
      '{open} {make} {model} {year}، {hook}.',
      '{open} {make} {model}، {hook}.',
      '{open} {make} {model} {color}، {hook}.',
      '{open} جهاز {make}، {hook}.',
      '{open} {model} من {make}، {hook}.',
      '{open} {make} {year}، {hook}.',
    ],
    paragraph2: [
      'الجهاز من {make} وموديله {model}. {colorTone}. {condTone}. الوظيفة تتضح عند الفحص.',
      '{yearTone}. {condTone}. الوظيفة الظاهرة تتضح عند الفحص قبل الاتفاق.',
      'اللون {color}، {colorTone}. {condTone}. القطعة معروضة كما هي.',
      'السعة المذكورة {storage}. {yearTone}. {condTone}. الجهاز معروض كما هو دون إضافات.',
      '{condTone}. {colorTone}. الاستخدام المنزلي يراجع عند المعاينة قبل الاتفاق.',
      'الموديل {model} من {make}، {yearTone}. {condTone}. لا توجد إضافات خارج المعروض.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة الجهاز {price} دينار حسب الاتفاق بعد الفحص. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. الفحص متاح قبل أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
  fashion: {
    titleTemplates: [
      '{make} {model} — {hook}',
      '{make} {color} — {hook}',
      '{model} {color} — {hook}',
      '{make} {model} {color} — {hook}',
      '{make} — {condTone}',
      '{color} {model} — {hook}',
    ],
    paragraph1: [
      '{open} {make} {model}، {hook}.',
      '{open} {make} {color}، {hook}.',
      '{open} قطعة {make}، {hook}.',
      '{open} {model} بلون {color}، {hook}.',
      '{open} {make} {model} {color}، {hook}.',
      '{open} {model} من {make}، {hook}.',
    ],
    paragraph2: [
      'القطعة بلون {color}، {colorTone}. {condTone}. المقاس كما هو معروض.',
      'الموديل {model} من {make}. {colorTone}. {condTone}. المقاس كما هو معروض.',
      '{condTone}. {colorTone}. الإطلالة النهائية تتضح عند القياس قبل الاتفاق.',
      'اللون المذكور {color}. {condTone}. القطعة معروضة كما هي دون تعديل.',
      '{colorTone}. {condTone}. الاستخدام اليومي يراجع بالمعاينة قبل الاتفاق.',
      'قطعة {make} وموديلها {model}. {colorTone}. {condTone}. القطعة معروضة كما هي.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة القطعة {price} دينار حسب الاتفاق بعد القياس. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. القياس متاح قبل أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
  beauty: {
    titleTemplates: [
      '{make} {model} — {hook}',
      '{make} {model} {year} — {hook}',
      '{make} {color} — {hook}',
      '{model} — {hook}',
      '{make} — {condTone}',
      '{make} {model} — {condTone}',
    ],
    paragraph1: [
      '{open} {make} {model}، {hook}.',
      '{open} {make} {model} {year}، {hook}.',
      '{open} منتج {make}، {hook}.',
      '{open} {model} من {make}، {hook}.',
      '{open} {make} {color}، {hook}.',
      '{open} {model}، {hook}.',
    ],
    paragraph2: [
      'المنتج من {make} وموديله {model}. {condTone}. الاستخدام شخصي ومنزلي.',
      '{yearTone}. {condTone}. التغليف الظاهر يراجع عند الاطلاع قبل الاتفاق.',
      'اللون {color}، {colorTone}. {condTone}. المنتج معروض كما هو.',
      '{condTone}. {yearTone}. لا توجد وعود خارج الوصف الظاهر.',
      '{colorTone}. {condTone}. الروتين المنزلي يتحدد حسب الاستخدام الشخصي.',
      'منتج {make}، {yearTone}. {condTone}. المعاينة توضح الحالة الظاهرة.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة المنتج {price} دينار حسب الاتفاق بعد الاطلاع. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. الاطلاع متاح قبل أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
  kids: {
    titleTemplates: [
      '{make} {model} — {hook}',
      '{make} {model} {color} — {hook}',
      '{make} {year} — {hook}',
      '{model} {color} — {hook}',
      '{make} — {condTone}',
      '{make} {model} — {condTone}',
    ],
    paragraph1: [
      '{open} {make} {model}، {hook}.',
      '{open} {make} {model} {color}، {hook}.',
      '{open} {make} {year}، {hook}.',
      '{open} قطعة {make}، {hook}.',
      '{open} {model} بلون {color}، {hook}.',
      '{open} {model} من {make}، {hook}.',
    ],
    paragraph2: [
      'القطعة من {make} وموديلها {model}. {colorTone}. {condTone}. الاستخدام المنزلي مع الأطفال.',
      'اللون {color}، {colorTone}. {condTone}. الاستخدام المنزلي مع الأطفال.',
      '{yearTone}. {condTone}. الحالة الظاهرة تتضح عند الفحص قبل الاتفاق.',
      '{condTone}. {colorTone}. القطعة معروضة كما هي دون إضافات.',
      'الموديل {model} من {make}. {yearTone}. {condTone}. القطعة معروضة كما هي.',
      '{colorTone}. {condTone}. المعاينة تحدد ملاءمة الاستخدام اليومي قبل الاتفاق.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة القطعة {price} دينار حسب الاتفاق بعد الفحص. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. الفحص متاح قبل أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
  pets: {
    titleTemplates: [
      '{make} {model} — {hook}',
      '{make} {color} — {hook}',
      '{model} {color} — {hook}',
      '{make} {year} — {hook}',
      '{color} — {hook}',
      '{make} — {condTone}',
    ],
    paragraph1: [
      '{open} {make} {model}، {hook}.',
      '{open} {make} {color}، {hook}.',
      '{open} {model}، {hook}.',
      '{open} {make} {year}، {hook}.',
      '{open} {color}، {hook}.',
      '{open} {model} من {make}، {hook}.',
    ],
    paragraph2: [
      'النوع {make} والوصف {model}. {colorTone}. {yearTone}. الرعاية تنتقل مع الاتفاق.',
      'اللون {color}، {colorTone}. {condTone}. الرعاية تنتقل مع الاتفاق.',
      '{yearTone}. {condTone}. الزيارة توضح الحالة الظاهرة فقط قبل الانتقال.',
      '{colorTone}. {yearTone}. الانتقال يكون إلى بيت مستقر بعد الزيارة.',
      'الوصف {model} من {make}. {condTone}. لا توجد تفاصيل غير المعروضة.',
      '{condTone}. {colorTone}. المعاينة للجادين قبل أي انتقال إلى البيت.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة العرض {price} دينار حسب الاتفاق بعد الزيارة. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. الزيارة متاحة قبل أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
  sports: {
    titleTemplates: [
      '{make} {model} — {hook}',
      '{make} {model} {year} — {hook}',
      '{make} {color} — {hook}',
      '{model} {color} — {hook}',
      '{make} {year} — {hook}',
      '{make} {model} — {condTone}',
    ],
    paragraph1: [
      '{open} {make} {model}، {hook}.',
      '{open} {make} {model} {year}، {hook}.',
      '{open} {make} {color}، {hook}.',
      '{open} معدة {make}، {hook}.',
      '{open} {model} من {make}، {hook}.',
      '{open} {model} {color}، {hook}.',
    ],
    paragraph2: [
      'المعدة من {make} وموديلها {model}. {condTone}. {yearTone}. الاستخدام يراجع عند الفحص.',
      'اللون {color}، {colorTone}. {condTone}. الاستخدام الرياضي يراجع عند الفحص.',
      '{yearTone}. {condTone}. القطعة معروضة كما هي دون ملحقات غير مذكورة.',
      '{colorTone}. {condTone}. التدريب المنزلي أو في النادي حسب طبيعة المعدة.',
      'موديل {model} من {make}. {yearTone}. {condTone}. المعدة معروضة كما هي.',
      '{condTone}. {colorTone}. الحالة الظاهرة تتضح بالمعاينة قبل الاتفاق.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة المعدة {price} دينار حسب الاتفاق بعد الفحص. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. الفحص متاح قبل أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
  books: {
    titleTemplates: [
      '{make} {model} — {hook}',
      '{model} — {hook}',
      '{make} {year} — {hook}',
      '{model} {year} — {hook}',
      '{make} {model} {year} — {hook}',
      '{model} — {condTone}',
    ],
    paragraph1: [
      '{open} {make} {model}، {hook}.',
      '{open} {model}، {hook}.',
      '{open} {make} {year}، {hook}.',
      '{open} كتاب {model}، {hook}.',
      '{open} {model} {year}، {hook}.',
      '{open} {make} {model} {year}، {hook}.',
    ],
    paragraph2: [
      'العنوان {model} من {make}. {yearTone}. {condTone}. النسخة معروضة كما هي.',
      '{condTone}. {yearTone}. النسخة معروضة كما هي للقراءة والاقتناء.',
      'الكتاب بعنوان {model}. {condTone}. المحتوى حسب العنوان الظاهر فقط.',
      '{yearTone}. {condTone}. الاطلاع يراجع حالة النسخة الظاهرة قبل الاتفاق.',
      'نسخة {model} من {make}. {yearTone}. {condTone}. المحتوى حسب العنوان الظاهر.',
      '{condTone}. النسخة جاهزة للمعاينة. لا توجد صفحات مضافة خارج المعروض.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة النسخة {price} دينار حسب الاتفاق بعد الاطلاع. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. الاطلاع متاح قبل أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
  'home-garden': {
    titleTemplates: [
      '{make} {model} — {hook}',
      '{make} {model} {color} — {hook}',
      '{make} {year} — {hook}',
      '{model} {color} — {hook}',
      '{make} {area} — {hook}',
      '{make} {model} — {condTone}',
    ],
    paragraph1: [
      '{open} {make} {model}، {hook}.',
      '{open} {make} {model} {color}، {hook}.',
      '{open} {make} {year}، {hook}.',
      '{open} مستلزم {make}، {hook}.',
      '{open} {model} في {area}، {hook}.',
      '{open} {model} من {make}، {hook}.',
    ],
    paragraph2: [
      'المستلزم من {make} وموديله {model}. {colorTone}. {condTone}. الاستخدام حسب طبيعة القطعة.',
      'اللون {color}، {colorTone}. {yearTone}. {condTone}. القطعة معروضة كما هي.',
      '{condTone}. {yearTone}. الاستخدام في البيت أو الحديقة حسب طبيعة القطعة.',
      'المساحة المذكورة {area}. {condTone}. القطعة معروضة كما هي.',
      '{colorTone}. {condTone}. الفحص يوضح الحالة الظاهرة قبل الاتفاق.',
      'موديل {model} من {make}. {yearTone}. {condTone}. الفحص يوضح الحالة الظاهرة.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة القطعة {price} دينار حسب الاتفاق بعد الفحص. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. الفحص متاح قبل أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
  krakeeb: {
    titleTemplates: [
      '{make} {model} — {hook}',
      '{model} {color} — {hook}',
      '{make} {color} — {hook}',
      '{model} — {hook}',
      '{make} {year} — {hook}',
      '{model} — {condTone}',
    ],
    paragraph1: [
      '{open} {make} {model}، {hook}.',
      '{open} {model}، {hook}.',
      '{open} {make} {color}، {hook}.',
      '{open} {model} {color}، {hook}.',
      '{open} {make} {year}، {hook}.',
      '{open} أغراض {model}، {hook}.',
    ],
    paragraph2: [
      'الأغراض بعنوان {model} من {make}. {condTone}. {colorTone}. المجموعة معروضة كما هي.',
      'اللون {color}، {colorTone}. {condTone}. المجموعة معروضة كما هي.',
      '{yearTone}. {condTone}. لا توجد قطع غير الظاهرة في العرض.',
      '{condTone}. {colorTone}. المعاينة تحدد ما يمكن الاستفادة منه.',
      'وصف الأغراض {model}. {yearTone}. {condTone}. المعاينة تحدد الاستفادة الظاهرة.',
      '{colorTone}. {condTone}. الحالة الظاهرة هي المعتمدة دون إضافات.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة الأغراض {price} دينار حسب الاتفاق بعد المعاينة. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. المعاينة متاحة قبل أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
  services: {
    titleTemplates: [
      '{jobTitle} — {hook}',
      '{jobTitle} {area} — {hook}',
      '{jobTitle} {exp} — {hook}',
      '{area} — {hook}',
      '{jobTitle} {exp} {area} — {hook}',
      '{exp} {area} — {hook}',
    ],
    paragraph1: [
      '{open} {jobTitle}، {hook}.',
      '{open} {jobTitle} في {area}، {hook}.',
      '{open} {jobTitle} بخبرة {exp}، {hook}.',
      '{open} خدمة في {area}، {hook}.',
      '{open} {jobTitle} {exp}، {hook}.',
      '{open} {area}، {hook}.',
    ],
    paragraph2: [
      'الخدمة بعنوان {jobTitle} ضمن {area}. التنفيذ حسب الطلب الظاهر. النطاق يتحدد قبل البدء.',
      'الخبرة المذكورة {exp}. التغطية في {area}. العمل للجادين بعد توضيح الطلب.',
      'العنوان {jobTitle} والخبرة {exp}. التفاصيل تثبت قبل التنفيذ. لا يبدأ العمل قبل الاتفاق.',
      'التغطية المذكورة {area}. الخدمة واضحة في نطاقها. أي إضافة خارج الطلب لا تحتسب.',
      '{jobTitle} متاح في {area}. الخبرة الظاهرة {exp}. الاتفاق يسبق الحضور.',
      'نطاق العمل في {area}. {jobTitle} حسب طبيعة الطلب. المعطيات الظاهرة هي المعتمدة.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة الخدمة {price} دينار حسب الاتفاق قبل البدء. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. الطلب يوضح قبل أي تنفيذ.',
      '{hook}. {close}.',
    ],
  },
  cleaning: {
    titleTemplates: [
      '{jobTitle} — {hook}',
      '{jobTitle} {area} — {hook}',
      '{area} — {hook}',
      '{jobTitle} {exp} — {hook}',
      'تنظيف {area} — {hook}',
      '{exp} — {hook}',
    ],
    paragraph1: [
      '{open} {jobTitle}، {hook}.',
      '{open} {jobTitle} في {area}، {hook}.',
      '{open} تنظيف في {area}، {hook}.',
      '{open} {jobTitle} بخبرة {exp}، {hook}.',
      '{open} {area}، {hook}.',
      '{open} خدمة {jobTitle}، {hook}.',
    ],
    paragraph2: [
      'التنظيف بعنوان {jobTitle} ضمن {area}. النطاق يتفق عليه قبل الحضور. الخدمة للمنازل أو المكاتب حسب الطلب.',
      'الخبرة المذكورة {exp}. التغطية في {area}. الموعد يثبت بعد وضوح المساحة.',
      'المساحة المذكورة {area}. العمل حسب الاتفاق الظاهر. لا يشمل التنظيف ما لم يذكر.',
      '{jobTitle} متاح في {area}. الخبرة الظاهرة {exp}. الترتيب النهائي يراجع بعد التنفيذ.',
      'خدمة في {area} بخبرة {exp}. النطاق المنزلي أو المكتبي يوضح أولا. المواد حسب الاتفاق.',
      'العنوان {jobTitle} والتغطية {area}. التنفيذ بعد تحديد المساحة. المعطيات الظاهرة هي المعتمدة.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة التنظيف {price} دينار حسب الاتفاق قبل الحضور. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. المساحة توضح قبل أي موعد.',
      '{hook}. {close}.',
    ],
  },
  handymen: {
    titleTemplates: [
      '{jobTitle} — {hook}',
      '{jobTitle} {area} — {hook}',
      '{jobTitle} {exp} — {hook}',
      '{area} — {hook}',
      'صيانة {area} — {hook}',
      '{exp} {jobTitle} — {hook}',
    ],
    paragraph1: [
      '{open} {jobTitle}، {hook}.',
      '{open} {jobTitle} في {area}، {hook}.',
      '{open} {jobTitle} بخبرة {exp}، {hook}.',
      '{open} إصلاح في {area}، {hook}.',
      '{open} {area}، {hook}.',
      '{open} فني {jobTitle}، {hook}.',
    ],
    paragraph2: [
      'الصيانة بعنوان {jobTitle} ضمن {area}. الكشف يسبق التنفيذ. النطاق يتحدد بعد المعاينة.',
      'الخبرة المذكورة {exp}. التغطية في {area}. السعر لا يثبت قبل وضوح العمل.',
      'الإصلاح في {area} بخبرة {exp}. العمل حسب ما يظهر في الكشف. لا توجد إضافات خارج الاتفاق.',
      '{jobTitle} متاح في {area}. المعاينة تحدد نوع الإصلاح. التنفيذ بعد الاتفاق على النطاق.',
      'العنوان {jobTitle} والخبرة {exp}. التغطية الظاهرة {area}. الكشف للجادين قبل البدء.',
      'نطاق الصيانة في {area}. {jobTitle} حسب العطل الظاهر. المعطيات بعد الكشف هي المعتمدة.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة العمل {price} دينار بعد الكشف والاتفاق. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. الكشف يسبق أي تنفيذ.',
      '{hook}. {close}.',
    ],
  },
  projects: {
    titleTemplates: [
      '{jobTitle} — {hook}',
      '{jobTitle} {area} — {hook}',
      '{make} {model} — {hook}',
      '{area} — {hook}',
      '{jobTitle} {area} — {condTone}',
      '{make} {area} — {hook}',
    ],
    paragraph1: [
      '{open} {jobTitle}، {hook}.',
      '{open} {jobTitle} في {area}، {hook}.',
      '{open} {make} {model}، {hook}.',
      '{open} مشروع في {area}، {hook}.',
      '{open} {jobTitle} ضمن {area}، {hook}.',
      '{open} {make} في {area}، {hook}.',
    ],
    paragraph2: [
      'المشروع بعنوان {jobTitle} في {area}. المعطيات الظاهرة فقط دون إضافات. الدراسة تسبق أي اتفاق.',
      'النشاط {make} ووصفه {model}. الموقع المذكور {area}. لا توجد وعود خارج المعروض.',
      '{condTone}. التغطية في {area}. التفاصيل للجادين بعد المعاينة.',
      'العنوان {jobTitle} والموقع {area}. الحالة الظاهرة حسب البيان. أي اتفاق بعد مراجعة المعطيات.',
      'وصف {model} من {make}. {condTone}. الدراسة تحدد ملاءمة الدخول.',
      'النشاط في {area}. {jobTitle} حسب المعروض. المعاينة تسبق القرار.',
    ],
    paragraph3: [
      'السعر {price} دينار قابل للتفاوض المعقول. {close}.',
      'السعر المعروض {price} دينار. {close}.',
      'قيمة المشروع {price} دينار حسب المعروض بعد الدراسة. {close}.',
      'السعر {price} دينار للجادين. {close}.',
      '{close}. الدراسة تسبق أي اتفاق.',
      '{hook}. {close}.',
    ],
  },
};

export const ENRICHMENT_RULES_EXTRA: ReadonlyArray<{
  readonly key: string;
  readonly value: string;
  readonly phrase: string;
}> = [
  { key: 'color', value: 'كحلي', phrase: 'لون كحلي رسمي وأنيق' },
  { key: 'color', value: 'زيتي', phrase: 'لون زيتي عملي وهادئ' },
  { key: 'color', value: 'خمري', phrase: 'لون خمري أنيق للمناسبات' },
  { key: 'color', value: 'عاجي', phrase: 'لون عاجي ناعم ومشرق' },
  { key: 'color', value: 'سماوي', phrase: 'لون سماوي خفيف ومريح' },
  { key: 'color', value: 'تركواز', phrase: 'لون تركواز واضح ومميز' },
  { key: 'color', value: 'نحاسي', phrase: 'لون نحاسي دافئ وواضح' },
  { key: 'color', value: 'رملي', phrase: 'لون رملي هادئ وسهل التنسيق' },
  { key: 'color', value: 'عنابي', phrase: 'لون عنابي عميق ومناسب للمظهر المرتب' },
  { key: 'color', value: 'لؤلؤي', phrase: 'لون لؤلؤي ناعم ومشرق' },
  { key: 'color', value: 'فحمي', phrase: 'لون فحمي عملي وقريب من الداكن' },
  { key: 'color', value: 'كريمي', phrase: 'لون كريمي ناعم وسهل الدمج' },
  { key: 'color', value: 'مشمشي', phrase: 'لون مشمشي دافئ وواضح' },
  { key: 'color', value: 'موف', phrase: 'لون موف هادئ ومميز' },
  { key: 'color', value: 'نيلي', phrase: 'لون نيلي عميق ومريح للنظر' },
  { key: 'color', value: 'برونزي', phrase: 'لون برونزي دافئ وواضح' },
  { key: 'condition', value: 'مستعمل', phrase: 'مستعمل بحالة ظاهرة يمكن معاينتها' },
  { key: 'condition', value: 'ممتاز', phrase: 'حالة ظاهرة ممتازة عند المعاينة' },
  { key: 'condition', value: 'جيد', phrase: 'حالة جيدة وصالحة للاستخدام' },
  { key: 'condition', value: 'جيد جدا', phrase: 'حالة جيدة جدا حسب الظاهر' },
  { key: 'condition', value: 'كالجديد', phrase: 'استخدام خفيف ومظهر قريب من الجديد' },
  { key: 'condition', value: 'نظيف', phrase: 'نظافة ظاهرة ومرتبة' },
  { key: 'condition', value: 'استعمال خفيف', phrase: 'استخدام محدود وحالة محفوظة' },
  { key: 'condition', value: 'مغلف', phrase: 'محفوظ بتغليفه حتى المعاينة' },
  { key: 'condition', value: 'شبه جديد', phrase: 'مظهر قريب من الجديد حسب الظاهر' },
  { key: 'condition', value: 'بدون علبة', phrase: 'معروض بدون علبته الأصلية' },
  { key: 'material', value: 'قماش', phrase: 'خامة قماش مريحة للاستخدام اليومي' },
  { key: 'material', value: 'جلد', phrase: 'خامة جلد تمنح ملمسا متينا' },
  { key: 'material', value: 'خشب', phrase: 'خامة خشب طبيعية ومتينة' },
  { key: 'material', value: 'معدن', phrase: 'هيكل معدني عملي ومتحمل' },
  { key: 'material', value: 'بلاستيك', phrase: 'خامة بلاستيك خفيفة وسهلة العناية' },
  { key: 'material', value: 'قطن', phrase: 'خامة قطن مريحة وناعمة' },
  { key: 'material', value: 'حرير', phrase: 'خامة حرير ناعمة للمناسبات' },
  { key: 'material', value: 'ستانلس', phrase: 'خامة ستانلس مقاومة وسهلة التنظيف' },
  { key: 'material', value: 'زجاج', phrase: 'سطح زجاجي واضح وسهل المسح' },
  { key: 'material', value: 'سيراميك', phrase: 'سطح سيراميك عملي للاستخدام المنزلي' },
  { key: 'material', value: 'صوف', phrase: 'خامة صوف دافئة للاستخدام البارد' },
  { key: 'material', value: 'كتان', phrase: 'خامة كتان خفيفة ومريحة' },
  { key: 'material', value: 'مخمل', phrase: 'خامة مخمل ناعمة الملمس' },
  { key: 'material', value: 'جلد صناعي', phrase: 'خامة جلد صناعي عملية وسهلة العناية' },
  { key: 'gender', value: 'رجالي', phrase: 'مصمم للأناقة الرجالية' },
  { key: 'gender', value: 'نسائي', phrase: 'مصمم للإطلالة النسائية' },
  { key: 'gender', value: 'أطفال', phrase: 'مخصص لاستخدام الأطفال' },
  { key: 'gender', value: 'للجنسين', phrase: 'مناسب للجنسين' },
  { key: 'style', value: 'كلاسيك', phrase: 'طابع كلاسيكي هادئ' },
  { key: 'style', value: 'عصري', phrase: 'طابع عصري بسيط' },
  { key: 'style', value: 'رياضي', phrase: 'طابع رياضي عملي' },
  { key: 'style', value: 'رسمي', phrase: 'طابع رسمي مرتب' },
  { key: 'style', value: 'فاخر', phrase: 'طابع فاخر في التفاصيل الظاهرة' },
  { key: 'size', value: 'صغير', phrase: 'حجم صغير وسهل التخزين' },
  { key: 'size', value: 'متوسط', phrase: 'حجم متوسط مناسب للاستخدام المعتاد' },
  { key: 'size', value: 'كبير', phrase: 'حجم كبير لمن يحتاج سعة أوضح' },
  { key: 'size', value: 'واسع', phrase: 'حجم واسع للاستخدام العائلي' },
  { key: 'size', value: 'مدمج', phrase: 'حجم مدمج لا يأخذ حيزا كبيرا' },
  { key: 'storage', value: 'كبير', phrase: 'سعة تخزين مريحة للملفات والاستخدام' },
  { key: 'storage', value: 'متوسط', phrase: 'سعة كافية للاستخدام اليومي' },
  { key: 'storage', value: 'صغير', phrase: 'سعة محدودة وخفيفة الاستخدام' },
  { key: 'storage', value: 'واسع', phrase: 'سعة واسعة لمن يكثر من الحفظ' },
  { key: 'target', value: 'عائلي', phrase: 'مناسب للاستخدام العائلي' },
  { key: 'target', value: 'طلاب', phrase: 'خيار عملي للطلاب والدراسة' },
  { key: 'target', value: 'محترفين', phrase: 'مناسب للاستخدام المهني' },
  { key: 'target', value: 'منزلي', phrase: 'مخصص للاستخدام المنزلي' },
  { key: 'target', value: 'مبتدئين', phrase: 'مناسب لمن يبدأ في هذا المجال' },
  { key: 'target', value: 'مكتبي', phrase: 'عملي للاستخدام المكتبي' },
  { key: 'warranty', value: 'ساري', phrase: 'الضمان ساري حسب المتبقي المذكور' },
  { key: 'warranty', value: 'بدون ضمان', phrase: 'معروض بدون ضمان' },
  { key: 'warranty', value: 'وكيل', phrase: 'ضمان الوكيل حسب الشروط الظاهرة' },
  { key: 'warranty', value: 'محدود', phrase: 'ضمان محدود حسب الاتفاق' },
  { key: 'age', value: 'صغير', phrase: 'عمر صغير ويحتاج رعاية مناسبة' },
  { key: 'age', value: 'بالغ', phrase: 'عمر بالغ ومستقر للرعاية المنزلية' },
  { key: 'age', value: 'جرو', phrase: 'جرو يحتاج متابعة وعناية' },
  { key: 'age', value: 'يافع', phrase: 'عمر يافع وقادر على التأقلم' },
  { key: 'power', value: 'قوي', phrase: 'أداء قوي للاستخدام المطلوب' },
  { key: 'power', value: 'اقتصادي', phrase: 'تشغيل اقتصادي في الاستهلاك' },
  { key: 'power', value: 'هادئ', phrase: 'تشغيل هادئ ومناسب للبيت' },
  { key: 'seats', value: 'فردي', phrase: 'استخدام فردي مريح' },
  { key: 'seats', value: 'مزدوج', phrase: 'يتسع لاستخدام شخصين' },
  { key: 'seats', value: 'عائلي', phrase: 'جلوس عائلي مريح' },
  { key: 'seats', value: 'طويل', phrase: 'وضعية جلوس طويلة مريحة' },
  { key: 'area', value: 'واسع', phrase: 'مساحة واسعة ومرتبة' },
  { key: 'area', value: 'متوسط', phrase: 'مساحة متوسطة عملية' },
  { key: 'area', value: 'صغير', phrase: 'مساحة صغيرة وسهلة العناية' },
  { key: 'area', value: 'تجاري', phrase: 'مساحة ذات طابع تجاري' },
  { key: 'area', value: 'سكني', phrase: 'مساحة سكنية واضحة' },
  { key: 'rooms', value: 'استوديو', phrase: 'توزيع استوديو عملي' },
  { key: 'rooms', value: 'مجلس', phrase: 'يحتوي مجلسا مناسبا للجلوس' },
  { key: 'rooms', value: 'مفتوح', phrase: 'توزيع مفتوح وسهل الحركة' },
  { key: 'bedrooms', value: 'ماستر', phrase: 'غرفة نوم رئيسية واسعة' },
  { key: 'bedrooms', value: 'ضيف', phrase: 'غرفة مناسبة للضيوف' },
  { key: 'bedrooms', value: 'أطفال', phrase: 'غرفة مناسبة للأطفال' },
  { key: 'bathrooms', value: 'مشترك', phrase: 'دورة مياه مشتركة' },
  { key: 'bathrooms', value: 'ملحق', phrase: 'دورة مياه ملحقة' },
  { key: 'bathrooms', value: 'رئيسي', phrase: 'دورة مياه رئيسية واضحة' },
  { key: 'brand', value: 'أصلي', phrase: 'منتج أصلي حسب الظاهر' },
  { key: 'brand', value: 'وكالة', phrase: 'وارد الوكالة حسب البيان' },
  { key: 'year', value: '2012', phrase: 'سنة إصدار قديمة ومتداولة في السوق' },
  { key: 'year', value: '2013', phrase: 'سنة إصدار مستقرة ومعروفة' },
  { key: 'year', value: '2014', phrase: 'سنة إصدار مجربة وواضحة' },
  { key: 'year', value: '2015', phrase: 'سنة إصدار مستقرة ومعروفة في السوق' },
  { key: 'year', value: '2016', phrase: 'سنة إصدار مجربة ومتداولة' },
  { key: 'year', value: '2017', phrase: 'سنة إصدار واضحة ومناسبة للاستعمال' },
  { key: 'year', value: '2018', phrase: 'سنة إصدار متداولة وسهلة المعاينة' },
  { key: 'year', value: '2019', phrase: 'سنة إصدار قريبة من الأجيال الأحدث' },
  { key: 'year', value: '2025', phrase: 'سنة إصدار حديثة جدا' },
  { key: 'year', value: '2026', phrase: 'سنة إصدار حديثة ومعروضة حاليا' },
];
