// RULE-14-EXCEPTION: Static taxonomy
import type { PremiumCategory } from './types';

export const MOBILES_PREMIUM: PremiumCategory = {
  titleTemplates: [],
  paragraph1: [],
  paragraph2: [],
  paragraph3: [],
  structured: {
    titleFormat: [
      { template: "رقم مميز للبيع بسعر {price}", subcategories: ["numbers"] },
      { template: "رقم جوال مقابل {price} مع نقل ملكية", subcategories: ["numbers"] },
      { template: "بيع رقم بسعر {price} وتوثيق النقل", subcategories: ["numbers"] },
      { template: "رقم معروض بـ{price} بلا وسيط", subcategories: ["numbers"] },
      { template: "نقل رقم بسعر {price} بعد التوثيق", subcategories: ["numbers"] },
      { template: "{make} {model} بسعر {price}", subcategories: [] },
      { template: "{make} {model} — {price}", subcategories: [] },
      { template: "بيع {make} {model} مقابل {price}", subcategories: [] },
      { template: "{make} {model} للبيع بسعر {price}", subcategories: [] },
      { template: "جهاز {make} {model} بسعر {price}", subcategories: [] },
      { template: "{make} {model} متاح بسعر {price}", subcategories: [] },
      { template: "{make} {model} معروض بسعر {price}", subcategories: [] },
      { template: "{make} {model} جاهز بسعر {price}", subcategories: [] },
      { template: "عرض {make} {model} بسعر {price}", subcategories: [] },
      { template: "{make} {model} بسعر {price} للتسليم", subcategories: [] },
      { template: "{make} {model} بلون {color} بسعر {price}", subcategories: [] },
      { template: "{make} {model} لون {color} — {price}", subcategories: [] },
      { template: "{make} {model} بلون {color} مقابل {price}", subcategories: [] },
      { template: "{make} {model} بحالة {condition} بسعر {price}", subcategories: [] },
      { template: "{make} {model} بحالة {condition} — {price}", subcategories: [] },
      { template: "{make} {model} — {condition} بسعر {price}", subcategories: [] },
      { template: "{make} {model} ذاكرة {storage} بسعر {price}", subcategories: [] },
      { template: "{make} {model} بسعة {storage} — {price}", subcategories: [] },
      { template: "{make} {model} بذاكرة {storage} مقابل {price}", subcategories: [] },
      { template: "{make} {model} سعة {storage} بسعر {price}", subcategories: [] },
    ],
    hooks: [
      { template: "الرقم معروض بسعر {price} والنقل بعد التوثيق.", subcategories: ["numbers"] },
      { template: "سعر الرقم {price}، والإجراء يتم باسم المشتري.", subcategories: ["numbers"] },
      { template: "الرقم متاح مقابل {price} من غير وسيط.", subcategories: ["numbers"] },
      { template: "{make} {model} بسعر {price}.", subcategories: [] },
      { template: "{make} {model} بحالة {condition}.", subcategories: [] },
      { template: "{make} {model} بلون {color}.", subcategories: [] },
      { template: "{make} {model} بذاكرة {storage}.", subcategories: [] },
      { template: "{make} {model} جاهز للمعاينة.", subcategories: [] },
      { template: "جهاز مفحوص بسعر {price}.", subcategories: [] },
      { template: "{make} {model} ببطارية {battery}.", subcategories: [] },
      { template: "{make} {model} بضمان {warranty}.", subcategories: [] },
      { template: "{make} {model} من سنة {year}.", subcategories: [] },
      { template: "{make} {model} بشاشة {screen}.", subcategories: [] },
      { template: "{make} {model} بكاميرا {camera}.", subcategories: [] },
      { template: "السعر {price} بعد الفحص.", subcategories: [] },
    ],
    introParagraphs: [
      { template: "رقم جوال معروض بسعر {price}. النقل يتم بعد التوثيق وباسم المشتري.", subcategories: ["numbers"] },
      { template: "السعر المحدد للرقم {price}. الإجراء يُشرح قبل الاتفاق.", subcategories: ["numbers"] },
      { template: "{make} {model} متاح للمعاينة قبل الشراء.", subcategories: [] },
      { template: "{make} {model} بلون {color}.", subcategories: [] },
      { template: "{make} {model} بحالة {condition}.", subcategories: [] },
      { template: "{make} {model} بذاكرة {storage}.", subcategories: [] },
      { template: "{make} {model} من سنة {year}.", subcategories: [] },
      { template: "{make} {model} بضمان {warranty}.", subcategories: [] },
      { template: "الجهاز {model} معروض بسعر {price}.", subcategories: [] },
      { template: "{make} بسعر {price} للمعاينة.", subcategories: [] },
      { template: "{model} بسعر {price}.", subcategories: [] },
      { template: "{make} {model} مع {box}.", subcategories: [] },
      { template: "{make} {model} مع {charger}.", subcategories: [] },
      { template: "{make} {model} بشاشة {screen}.", subcategories: [] },
      { template: "{make} {model} بكاميرا {camera}.", subcategories: [] },
      { template: "{make} {model} ببطارية {battery}.", subcategories: [] },
      { template: "{make} {model} نسخة {region}.", subcategories: [] },
      { template: "{model} بلون {color} وجاهز للتجربة.", subcategories: [] },
      { template: "{model} بحالة {condition} وجاهز للتسليم.", subcategories: [] },
      { template: "{make} {model} مفحوص قبل العرض.", subcategories: [] },
    ],
    detailsGroups: [
      { fact: "make", variants: [
        { template: "• الشركة: {make}.", subcategories: [] },
        { template: "• الجهاز من صنع {make}.", subcategories: [] },
        { template: "• العلامة التجارية {make}.", subcategories: [] },
        { template: "• الصانع المسجّل {make}.", subcategories: [] },
        { template: "• الماركة الظاهرة على الجهاز {make}.", subcategories: [] },
      ]},
      { fact: "model", variants: [
        { template: "• الموديل: {model}.", subcategories: [] },
        { template: "• اسم الطراز {model}.", subcategories: [] },
        { template: "• الجهاز طراز {model}.", subcategories: [] },
        { template: "• الموديل المكتوب على الجهاز {model}.", subcategories: [] },
        { template: "• الطراز المعروض {model}.", subcategories: [] },
      ]},
      { fact: "color", variants: [
        { template: "• اللون: {color}.", subcategories: [] },
        { template: "• لون الهيكل {color}.", subcategories: [] },
        { template: "• اللون الظاهر في الصور {color}.", subcategories: [] },
        { template: "• الجهاز باللون {color}.", subcategories: [] },
        { template: "• تشطيب اللون {color}.", subcategories: [] },
      ]},
      { fact: "storage", variants: [
        { template: "• الذاكرة: {storage}.", subcategories: [] },
        { template: "• سعة التخزين {storage}.", subcategories: [] },
        { template: "• المساحة الداخلية {storage}.", subcategories: [] },
        { template: "• التخزين حسب المواصفة {storage}.", subcategories: [] },
        { template: "• سعة الجهاز {storage}.", subcategories: [] },
      ]},
      { fact: "condition", variants: [
        { template: "• الجهاز بحالة {condition}.", subcategories: [] },
        { template: "• وصف حالة الجهاز {condition}.", subcategories: [] },
        { template: "• حالة الجهاز عند المعاينة {condition}.", subcategories: [] },
        { template: "• الاستخدام الظاهر {condition}.", subcategories: [] },
        { template: "• الجهاز موصوف بأنه {condition}.", subcategories: [] },
      ]},
      { fact: "battery", variants: [
        { template: "• البطارية: {battery}.", subcategories: [] },
        { template: "• صحة البطارية {battery}.", subcategories: [] },
        { template: "• قراءة البطارية {battery}.", subcategories: [] },
        { template: "• نسبة البطارية المذكورة {battery}.", subcategories: [] },
        { template: "• البطارية حسب الفحص {battery}.", subcategories: [] },
      ]},
      { fact: "warranty", variants: [
        { template: "• الضمان: {warranty}.", subcategories: [] },
        { template: "• مدة الضمان {warranty}.", subcategories: [] },
        { template: "• الضمان المذكور {warranty}.", subcategories: [] },
        { template: "• تغطية الضمان {warranty}.", subcategories: [] },
        { template: "• وضع الضمان {warranty}.", subcategories: [] },
      ]},
      { fact: "region", variants: [
        { template: "• النسخة: {region}.", subcategories: [] },
        { template: "• إصدار المنطقة {region}.", subcategories: [] },
        { template: "• النسخة الإقليمية {region}.", subcategories: [] },
        { template: "• الجهاز نسخة {region}.", subcategories: [] },
        { template: "• السوق الأصلي للجهاز {region}.", subcategories: [] },
      ]},
      { fact: "year", variants: [
        { template: "• السنة: {year}.", subcategories: [] },
        { template: "• سنة الإصدار {year}.", subcategories: [] },
        { template: "• الجهاز من عام {year}.", subcategories: [] },
        { template: "• تاريخ الطرح {year}.", subcategories: [] },
        { template: "• سنة الصنع المذكورة {year}.", subcategories: [] },
      ]},
      { fact: "price", variants: [
        { template: "• السعر: {price}.", subcategories: [] },
        { template: "• السعر المطلوب {price}.", subcategories: [] },
        { template: "• القيمة المعروضة {price}.", subcategories: [] },
        { template: "• المبلغ المذكور {price}.", subcategories: [] },
        { template: "• سعر البيع {price}.", subcategories: [] },
      ]},
      { fact: "box", variants: [
        { template: "• العلبة: {box}.", subcategories: [] },
        { template: "• وضع العلبة {box}.", subcategories: [] },
        { template: "• الجهاز مع {box}.", subcategories: [] },
        { template: "• العلبة المرافقة {box}.", subcategories: [] },
        { template: "• حالة العلبة {box}.", subcategories: [] },
      ]},
      { fact: "charger", variants: [
        { template: "• الشاحن: {charger}.", subcategories: [] },
        { template: "• الشاحن المرافق {charger}.", subcategories: [] },
        { template: "• الجهاز يأتي مع {charger}.", subcategories: [] },
        { template: "• وضع الشاحن {charger}.", subcategories: [] },
        { template: "• الشاحن حسب الوصف {charger}.", subcategories: [] },
      ]},
    ],
    featuresBullets: [
      { template: "• السعر {price} محدد قبل نقل الرقم.", subcategories: ["numbers"] },
      { template: "• النقل يتم بعد التوثيق مقابل {price}.", subcategories: ["numbers"] },
      { template: "• لا وسيط في البيع والسعر {price}.", subcategories: ["numbers"] },
      { template: "• الرقم يُسجّل باسم المشتري بسعر {price}.", subcategories: ["numbers"] },
      { template: "• الإجراء يُشرح قبل الاتفاق على {price}.", subcategories: ["numbers"] },
      { template: "• البطارية مفحوصة قبل العرض.", subcategories: [] },
      { template: "• قراءة البطارية ظاهرة في الإعدادات.", subcategories: [] },
      { template: "• البطارية على {battery}.", subcategories: [] },
      { template: "• الشاشة بلا خط ظاهر عند الفحص.", subcategories: [] },
      { template: "• الشاشة بمقاس {screen}.", subcategories: [] },
      { template: "• اللمس يعمل على كامل الشاشة.", subcategories: [] },
      { template: "• الكاميرا تعمل في الوضعين.", subcategories: [] },
      { template: "• دقة الكاميرا {camera}.", subcategories: [] },
      { template: "• العدسة بلا كسر ظاهر.", subcategories: [] },
      { template: "• الأداء مستقر أثناء التجربة.", subcategories: [] },
      { template: "• الجهاز يفتح التطبيقات بلا تعليق ملحوظ.", subcategories: [] },
      { template: "• التشغيل سليم بعد الفحص.", subcategories: [] },
      { template: "• الهيكل بلا كسر ظاهر.", subcategories: [] },
      { template: "• الجهاز بلون {color} سليم في الأطراف.", subcategories: [] },
      { template: "• الأطراف والظهر سليمة.", subcategories: [] },
      { template: "• الضمان مذكور في الإعلان.", subcategories: [] },
      { template: "• مدة الضمان {warranty}.", subcategories: [] },
      { template: "• الجهاز أصلي وغير مجدّد.", subcategories: [] },
      { template: "• الفحص شمل الشاشة والبطارية.", subcategories: [] },
      { template: "• تم فحص الجهاز قبل العرض.", subcategories: [] },
      { template: "• العلبة مرافقة للجهاز.", subcategories: [] },
      { template: "• الشاحن ضمن الملحقات.", subcategories: [] },
      { template: "• الذاكرة {storage}.", subcategories: [] },
      { template: "• الجهاز بحالة {condition}.", subcategories: [] },
      { template: "• النسخة {region}.", subcategories: [] },
    ],
    ctas: [
      { template: "للتنسيق على نقل الرقم راسل صاحب الإعلان.", subcategories: ["numbers"] },
      { template: "للمعاينة والتوثيق تواصل عبر الرسائل.", subcategories: ["numbers"] },
      { template: "للمعاينة تواصل عبر رسائل الإعلان.", subcategories: [] },
      { template: "راسل البائع لتحديد موعد تجربة الجهاز.", subcategories: [] },
      { template: "اتصل بصاحب الإعلان قبل الحضور.", subcategories: [] },
      { template: "للتنسيق على السعر راسل الآن.", subcategories: [] },
      { template: "للاستفسار عن الضمان تواصل برسالة.", subcategories: [] },
      { template: "للمعاينة في مكان متفق عليه راسل المعلن.", subcategories: [] },
      { template: "اتصل لتأكيد التوفر قبل الزيارة.", subcategories: [] },
      { template: "للتنسيق على التسليم تواصل عبر الإعلان.", subcategories: [] },
      { template: "للمعاينة والفحص تواصل مع البائع.", subcategories: [] },
      { template: "اتصل للاستفسار عن النسخة {region}.", subcategories: [] },
      { template: "تواصل لتحديد موعد الاستلام.", subcategories: [] },
      { template: "راسل لتأكيد اللون {color}.", subcategories: [] },
      { template: "للتنسيق على السعة {storage} تواصل برسالة.", subcategories: [] },
    ],
    detailsLabel: "🔹 المواصفات:",
    featuresLabel: "🔹 أبرز المميزات:",
    featuresCount: 4,
    introCount: 2,
    minDetails: 1,
    subTitleFormat: {
      phones: [
        { template: "{make} {model} للاتصال بسعر {price}", subcategories: ["phones"] },
        { template: "{make} {model} للتصوير بسعر {price}", subcategories: ["phones"] },
        { template: "{make} {model} شاشة سليمة — {price}", subcategories: ["phones"] },
        { template: "{make} {model} كاميرا سليمة بسعر {price}", subcategories: ["phones"] },
        { template: "{make} {model} أصلي بسعر {price}", subcategories: ["phones"] },
        { template: "{make} {model} بضمان الوكيل — {price}", subcategories: ["phones"] },
        { template: "{make} {model} بذاكرة {storage} — {price}", subcategories: ["phones"] },
        { template: "{make} {model} لون {color} — {price}", subcategories: ["phones"] },
        { template: "{make} {model} بحالة {condition} — {price}", subcategories: ["phones"] },
        { template: "{make} {model} نسخة الوكيل بسعر {price}", subcategories: ["phones"] },
      ],
      tablets: [
        { template: "{make} {model} لوحي بسعر {price}", subcategories: ["tablets"] },
        { template: "{make} {model} بشاشة واسعة — {price}", subcategories: ["tablets"] },
        { template: "{make} {model} للدراسة بسعر {price}", subcategories: ["tablets"] },
        { template: "{make} {model} يدعم القلم — {price}", subcategories: ["tablets"] },
        { template: "{make} {model} واي فاي بسعر {price}", subcategories: ["tablets"] },
        { template: "{make} {model} للرسم بسعر {price}", subcategories: ["tablets"] },
        { template: "{make} {model} سعة {storage} — {price}", subcategories: ["tablets"] },
        { template: "{make} {model} لون {color} — {price}", subcategories: ["tablets"] },
        { template: "{make} {model} بحالة {condition} — {price}", subcategories: ["tablets"] },
        { template: "{make} {model} للتصفح بسعر {price}", subcategories: ["tablets"] },
      ],
      "smart-watches": [
        { template: "{make} {model} ساعة ذكية — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} بسوار رياضي — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} لتتبع النوم بسعر {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} لقياس النبض — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} للرياضة بسعر {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} شاشة معصم — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} لون {color} — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} بحالة {condition} — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} سوار قابل للتبديل — {price}", subcategories: ["smart-watches"] },
        { template: "{make} {model} للمعصم بسعر {price}", subcategories: ["smart-watches"] },
      ],
      accessories: [
        { template: "ملحق {make} {model} بسعر {price}", subcategories: ["accessories"] },
        { template: "إكسسوار {make} {model} — {price}", subcategories: ["accessories"] },
        { template: "قطعة {make} {model} بسعر {price}", subcategories: ["accessories"] },
        { template: "{make} {model} مع التغليف — {price}", subcategories: ["accessories"] },
        { template: "{make} {model} أصلي ملحق — {price}", subcategories: ["accessories"] },
        { template: "{make} {model} لون {color} — {price}", subcategories: ["accessories"] },
        { template: "{make} {model} بحالة {condition} — {price}", subcategories: ["accessories"] },
        { template: "قطعة {make} {model} متوافقة — {price}", subcategories: ["accessories"] },
      ],
    },
    subHooks: {
      phones: [
        { template: "{make} {model} للاتصال والتصوير.", subcategories: ["phones"] },
        { template: "{make} {model} بذاكرة {storage}.", subcategories: ["phones"] },
        { template: "{make} {model} بكاميرا {camera}.", subcategories: ["phones"] },
        { template: "{make} {model} بضمان {warranty}.", subcategories: ["phones"] },
        { template: "هاتف مفحوص بسعر {price}.", subcategories: ["phones"] },
        { template: "{make} {model} نسخة {region}.", subcategories: ["phones"] },
      ],
      tablets: [
        { template: "{make} {model} للتصفح والدراسة.", subcategories: ["tablets"] },
        { template: "{make} {model} بشاشة {screen}.", subcategories: ["tablets"] },
        { template: "{make} {model} بسعة {storage}.", subcategories: ["tablets"] },
        { template: "{make} {model} يدعم القلم.", subcategories: ["tablets"] },
        { template: "جهاز لوحي بسعر {price}.", subcategories: ["tablets"] },
        { template: "{make} {model} باتصال واي فاي.", subcategories: ["tablets"] },
      ],
      "smart-watches": [
        { template: "{make} {model} للمعصم والرياضة.", subcategories: ["smart-watches"] },
        { template: "{make} {model} بسوار {color}.", subcategories: ["smart-watches"] },
        { template: "{make} {model} ببطارية {battery}.", subcategories: ["smart-watches"] },
        { template: "{make} {model} لتتبع النوم.", subcategories: ["smart-watches"] },
        { template: "ساعة مفحوصة بسعر {price}.", subcategories: ["smart-watches"] },
        { template: "{make} {model} بشاشة {screen}.", subcategories: ["smart-watches"] },
      ],
      accessories: [
        { template: "ملحق {make} {model} جاهز للتركيب.", subcategories: ["accessories"] },
        { template: "قطعة متوافقة بسعر {price}.", subcategories: ["accessories"] },
        { template: "{make} {model} مع التغليف.", subcategories: ["accessories"] },
        { template: "{make} {model} بلون {color}.", subcategories: ["accessories"] },
      ],
    },
    subIntroParagraphs: {
      phones: [
        { template: "{make} {model} مناسب للاتصال اليومي.", subcategories: ["phones"] },
        { template: "{make} {model} بذاكرة {storage}.", subcategories: ["phones"] },
        { template: "{make} {model} بكاميرا {camera}.", subcategories: ["phones"] },
        { template: "{make} {model} بضمان {warranty}.", subcategories: ["phones"] },
        { template: "{make} {model} نسخة {region}.", subcategories: ["phones"] },
        { template: "الهاتف {model} معروض بسعر {price}.", subcategories: ["phones"] },
        { template: "{make} {model} ببطارية {battery}.", subcategories: ["phones"] },
        { template: "{model} بحالة {condition} وجاهز للتجربة.", subcategories: ["phones"] },
      ],
      tablets: [
        { template: "{make} {model} مناسب للدراسة والتصفح.", subcategories: ["tablets"] },
        { template: "{make} {model} بشاشة {screen}.", subcategories: ["tablets"] },
        { template: "{make} {model} بسعة {storage}.", subcategories: ["tablets"] },
        { template: "{make} {model} يدعم القلم حسب الوصف.", subcategories: ["tablets"] },
        { template: "اللوحي {model} معروض بسعر {price}.", subcategories: ["tablets"] },
        { template: "{make} {model} باتصال واي فاي.", subcategories: ["tablets"] },
        { template: "{model} بلون {color} وجاهز للاستخدام.", subcategories: ["tablets"] },
        { template: "{make} {model} مع {charger}.", subcategories: ["tablets"] },
      ],
      "smart-watches": [
        { template: "{make} {model} مناسبة للمعصم.", subcategories: ["smart-watches"] },
        { template: "{make} {model} لتتبع النوم حسب الوصف.", subcategories: ["smart-watches"] },
        { template: "{make} {model} ببطارية {battery}.", subcategories: ["smart-watches"] },
        { template: "{make} {model} بشاشة {screen}.", subcategories: ["smart-watches"] },
        { template: "الساعة {model} معروضة بسعر {price}.", subcategories: ["smart-watches"] },
        { template: "{make} {model} بسوار {color}.", subcategories: ["smart-watches"] },
        { template: "{model} بحالة {condition} وجاهزة للتجربة.", subcategories: ["smart-watches"] },
        { template: "{make} {model} مع {box}.", subcategories: ["smart-watches"] },
      ],
      accessories: [
        { template: "ملحق {make} {model} جاهز للتركيب.", subcategories: ["accessories"] },
        { template: "القطعة {model} معروضة بسعر {price}.", subcategories: ["accessories"] },
        { template: "{make} {model} مع التغليف.", subcategories: ["accessories"] },
        { template: "{make} {model} بلون {color}.", subcategories: ["accessories"] },
        { template: "{model} بحالة {condition} وسليم للتسليم.", subcategories: ["accessories"] },
      ],
    },
    subFeaturesBullets: {
      phones: [
        { template: "• الكاميرا تعمل في الوضعين.", subcategories: ["phones"] },
        { template: "• دقة الكاميرا {camera}.", subcategories: ["phones"] },
        { template: "• البطارية مفحوصة قبل العرض.", subcategories: ["phones"] },
        { template: "• قراءة البطارية {battery}.", subcategories: ["phones"] },
        { template: "• الشاشة بلا خط ظاهر.", subcategories: ["phones"] },
        { template: "• الشاشة بمقاس {screen}.", subcategories: ["phones"] },
        { template: "• الذاكرة {storage}.", subcategories: ["phones"] },
        { template: "• النسخة {region}.", subcategories: ["phones"] },
        { template: "• الضمان {warranty}.", subcategories: ["phones"] },
        { template: "• القطع أصلية حسب الوصف.", subcategories: ["phones"] },
        { template: "• الاتصال والشبكة سليمين عند الفحص.", subcategories: ["phones"] },
        { template: "• الجهاز بحالة {condition}.", subcategories: ["phones"] },
      ],
      tablets: [
        { template: "• الشاشة واسعة للتصفح.", subcategories: ["tablets"] },
        { template: "• مقاس الشاشة {screen}.", subcategories: ["tablets"] },
        { template: "• السعة {storage}.", subcategories: ["tablets"] },
        { template: "• يدعم القلم حسب الوصف.", subcategories: ["tablets"] },
        { template: "• الاتصال عبر الواي فاي.", subcategories: ["tablets"] },
        { template: "• مناسب للدراسة والملاحظات.", subcategories: ["tablets"] },
        { template: "• الشاشة بلا خط ظاهر.", subcategories: ["tablets"] },
        { template: "• الشاحن {charger}.", subcategories: ["tablets"] },
        { template: "• الجهاز بحالة {condition}.", subcategories: ["tablets"] },
        { template: "• اللون {color}.", subcategories: ["tablets"] },
        { template: "• الهيكل بلا كسر ظاهر.", subcategories: ["tablets"] },
        { template: "• التشغيل سليم بعد الفحص.", subcategories: ["tablets"] },
      ],
      "smart-watches": [
        { template: "• السوار قابل للتبديل.", subcategories: ["smart-watches"] },
        { template: "• لون السوار {color}.", subcategories: ["smart-watches"] },
        { template: "• تتبع النبض مذكور في الوصف.", subcategories: ["smart-watches"] },
        { template: "• تتبع النوم مذكور في الوصف.", subcategories: ["smart-watches"] },
        { template: "• البطارية {battery}.", subcategories: ["smart-watches"] },
        { template: "• شاشة المعصم {screen}.", subcategories: ["smart-watches"] },
        { template: "• الساعة بحالة {condition}.", subcategories: ["smart-watches"] },
        { template: "• الشحن يتم عبر {charger}.", subcategories: ["smart-watches"] },
        { template: "• العلبة {box}.", subcategories: ["smart-watches"] },
        { template: "• المعصم يُقاس قبل الشراء.", subcategories: ["smart-watches"] },
        { template: "• الهيكل بلا خدش ظاهر.", subcategories: ["smart-watches"] },
        { template: "• الإشعارات تعمل حسب الفحص.", subcategories: ["smart-watches"] },
      ],
      accessories: [
        { template: "• القطعة متوافقة مع {make}.", subcategories: ["accessories"] },
        { template: "• التغليف {box}.", subcategories: ["accessories"] },
        { template: "• اللون {color}.", subcategories: ["accessories"] },
        { template: "• القطعة بحالة {condition}.", subcategories: ["accessories"] },
        { template: "• أصلية أو تجارية حسب الوصف.", subcategories: ["accessories"] },
        { template: "• الخامة سليمة عند المعاينة.", subcategories: ["accessories"] },
        { template: "• التركيب مباشر بلا تعديل.", subcategories: ["accessories"] },
        { template: "• السعر {price} للقطعة كما هي.", subcategories: ["accessories"] },
      ],
    },
    subCtas: {
      phones: [
        { template: "للمعاينة وتجربة الكاميرا تواصل عبر الرسائل.", subcategories: ["phones"] },
        { template: "راسل لتأكيد قراءة البطارية قبل الحضور.", subcategories: ["phones"] },
        { template: "اتصل للاستفسار عن نسخة {region}.", subcategories: ["phones"] },
        { template: "للتنسيق على سعة {storage} راسل المعلن.", subcategories: ["phones"] },
      ],
      tablets: [
        { template: "للمعاينة وتجربة الشاشة تواصل عبر الرسائل.", subcategories: ["tablets"] },
        { template: "راسل لتأكيد دعم القلم قبل الزيارة.", subcategories: ["tablets"] },
        { template: "اتصل للاستفسار عن سعة {storage}.", subcategories: ["tablets"] },
        { template: "للتنسيق على مقاس {screen} تواصل برسالة.", subcategories: ["tablets"] },
      ],
      "smart-watches": [
        { template: "للمعاينة على المعصم تواصل عبر الرسائل.", subcategories: ["smart-watches"] },
        { template: "راسل لتأكيد مقاس السوار قبل الحضور.", subcategories: ["smart-watches"] },
        { template: "اتصل للاستفسار عن بطارية {battery}.", subcategories: ["smart-watches"] },
        { template: "للتنسيق على لون {color} راسل المعلن.", subcategories: ["smart-watches"] },
      ],
      accessories: [
        { template: "للمعاينة والتوافق تواصل عبر الرسائل.", subcategories: ["accessories"] },
        { template: "راسل لتأكيد التوافق مع {make}.", subcategories: ["accessories"] },
        { template: "اتصل قبل الحضور لتأكيد توفر القطعة.", subcategories: ["accessories"] },
      ],
    },
  },
};
