import type { PremiumCategory } from './types';

export const MOBILES_PREMIUM: PremiumCategory = {
  titleTemplates: [],
  paragraph1: [],
  paragraph2: [],
  paragraph3: [],
  structured: {
    titleFormat: [
      { template: 'رقم مميز للبيع بسعر {price}', subcategories: ['numbers'] },
      { template: 'رقم جوال مقابل {price} مع نقل ملكية', subcategories: ['numbers'] },
      { template: 'بيع رقم بسعر {price} وتوثيق النقل', subcategories: ['numbers'] },
      { template: 'رقم معروض بـ{price} بلا وسيط', subcategories: ['numbers'] },
      { template: 'نقل رقم بسعر {price} بعد التوثيق', subcategories: ['numbers'] },
      { template: '{make} {model} لون {color} بسعر {price}', subcategories: [] },
      { template: '{model} بحالة {condition} — {price}', subcategories: [] },
      { template: '{storage} {model} لون {color} — {price}', subcategories: [] },
      { template: '{make} {model} — بسعر {price}', subcategories: [] },
      { template: '{make} {model} {year} لون {color} بسعر {price}', subcategories: [] },
      { template: '{model} ذاكرة {storage} بحالة {condition}', subcategories: [] },
      { template: '{make} {model} بلون {color} مقابل {price}', subcategories: [] },
      { template: '{make} {model} شاشة {screen} بسعر {price}', subcategories: [] },
      { template: '{model} كاميرا {camera} وحالة {condition}', subcategories: [] },
      { template: '{make} {model} مع {box} بسعر {price}', subcategories: [] },
      { template: '{model} ضمان {warranty} — {price}', subcategories: [] },
      { template: '{make} {model} نسخة {region} بسعر {price}', subcategories: [] },
      { template: '{storage} من {make} {model} بحالة {condition}', subcategories: [] },
      { template: '{model} بطارية {battery} ولون {color}', subcategories: [] },
      { template: '{make} {model} مع {charger} بسعر {price}', subcategories: [] },
      { template: '{model} بلون {color} وذاكرة {storage} — {price}', subcategories: [] },
      { template: '{make} {model} سنة {year} بحالة {condition}', subcategories: [] },
      { template: '{model} بسعر {price} وحالة {condition}', subcategories: [] },
      { template: '{make} {model} لون {color} وذاكرة {storage}', subcategories: [] },
      { template: '{model} نسخة {region} مع {warranty} — {price}', subcategories: [] },
    ],
    hooks: [
      { template: 'الرقم معروض بسعر {price} والنقل بعد التوثيق.', subcategories: ['numbers'] },
      { template: 'سعر الرقم {price}، والإجراء يتم باسم المشتري.', subcategories: ['numbers'] },
      { template: 'الرقم متاح مقابل {price} من غير وسيط.', subcategories: ['numbers'] },
      { template: '{make} {model} بحالة {condition}، والسعر {price}.', subcategories: [] },
      { template: 'الجهاز {model} لونه {color} وذاكرته {storage}.', subcategories: [] },
      { template: '{make} {model} من سنة {year} ومعه {box}.', subcategories: [] },
      { template: 'البطارية على {battery} في {model}.', subcategories: [] },
      { template: 'النسخة {region} من {make} {model}.', subcategories: [] },
      { template: '{model} يأتي مع {charger} و{box}.', subcategories: [] },
      { template: 'الشاشة {screen} في {make} {model}.', subcategories: [] },
      { template: 'الكاميرا {camera} على {model} بحالة {condition}.', subcategories: [] },
      { template: 'الضمان {warranty} مذكور على {make} {model}.', subcategories: [] },
      { template: '{make} {model} مفحوص، والسعر {price}.', subcategories: [] },
      { template: 'لون {color} وذاكرة {storage} في {model}.', subcategories: [] },
      { template: '{model} سنة {year} بحالة {condition}.', subcategories: [] },
    ],
    introParagraphs: [
      { template: 'رقم جوال معروض بسعر {price}. النقل يتم بعد التوثيق وباسم المشتري.', subcategories: ['numbers'] },
      { template: 'السعر المحدد للرقم {price}. لا وسيط، والإجراء يُشرح قبل الاتفاق.', subcategories: ['numbers'] },
      { template: '{make} {model} بلون {color} وذاكرة {storage}. الجهاز بحالة {condition} والسعر {price}.', subcategories: [] },
      { template: 'الجهاز {model} من {make}، سنة {year}. النسخة {region} والجهاز بحالة {condition}.', subcategories: [] },
      { template: '{make} {model} شاشته {screen} وكاميرته {camera}. السعر {price}.', subcategories: [] },
      { template: 'الاستخدام على {model} ظاهر، والجهاز بحالة {condition}. البطارية {battery}.', subcategories: [] },
      { template: 'يأتي {make} {model} مع {box} و{charger}. اللون {color}.', subcategories: [] },
      { template: 'الذاكرة {storage} في {model}، والضمان {warranty}. السعر {price}.', subcategories: [] },
      { template: '{make} {model} نسخة {region} من سنة {year}. الجهاز بحالة {condition}.', subcategories: [] },
      { template: 'لون الجهاز {color} والموديل {model}. الفحص تم والسعر {price}.', subcategories: [] },
      { template: '{model} بحالة {condition} وبطارية {battery}. الشاشة {screen}.', subcategories: [] },
      { template: 'الكاميرا {camera} على {make} {model}. التخزين {storage}.', subcategories: [] },
      { template: 'الضمان المذكور {warranty} على {model}. العلبة {box}.', subcategories: [] },
      { template: '{make} {model} من {year} بلون {color}. الشاحن {charger}.', subcategories: [] },
      { template: 'النسخة {region} لجهاز {model} بحالة {condition}. السعر {price}.', subcategories: [] },
      { template: 'ذاكرة {storage} ولون {color} في {make} {model}. البطارية {battery}.', subcategories: [] },
      { template: '{model} مفحوص قبل العرض. الجهاز بحالة {condition} والسعر {price}.', subcategories: [] },
      { template: 'الشاشة {screen} والكاميرا {camera} في {model}. سنة الصنع {year}.', subcategories: [] },
      { template: '{make} {model} مع {box}. اللون {color} والذاكرة {storage}.', subcategories: [] },
      { template: 'السعر {price} لجهاز {model} بحالة {condition}. الضمان {warranty}.', subcategories: [] },
    ],
    detailsGroups: [
      { fact: 'make', variants: [
        { template: '• الشركة: {make}.', subcategories: [] },
        { template: '• الجهاز من صنع {make}.', subcategories: [] },
        { template: '• العلامة التجارية {make}.', subcategories: [] },
        { template: '• الصانع المسجّل {make}.', subcategories: [] },
        { template: '• الماركة الظاهرة على الجهاز {make}.', subcategories: [] },
      ]},
      { fact: 'model', variants: [
        { template: '• الموديل: {model}.', subcategories: [] },
        { template: '• اسم الطراز {model}.', subcategories: [] },
        { template: '• الجهاز طراز {model}.', subcategories: [] },
        { template: '• الموديل المكتوب على العلبة {model}.', subcategories: [] },
        { template: '• الطراز المعروض {model}.', subcategories: [] },
      ]},
      { fact: 'color', variants: [
        { template: '• اللون: {color}.', subcategories: [] },
        { template: '• لون الهيكل {color}.', subcategories: [] },
        { template: '• اللون الظاهر في الصور {color}.', subcategories: [] },
        { template: '• الجهاز باللون {color}.', subcategories: [] },
        { template: '• تشطيب اللون {color}.', subcategories: [] },
      ]},
      { fact: 'storage', variants: [
        { template: '• الذاكرة: {storage}.', subcategories: [] },
        { template: '• سعة التخزين {storage}.', subcategories: [] },
        { template: '• المساحة الداخلية {storage}.', subcategories: [] },
        { template: '• التخزين المتاح حسب المواصفة {storage}.', subcategories: [] },
        { template: '• سعة الجهاز {storage}.', subcategories: [] },
      ]},
      { fact: 'condition', variants: [
        { template: '• الحالة: {condition}.', subcategories: [] },
        { template: '• وصف الحالة: {condition}.', subcategories: [] },
        { template: '• الجهاز بحالة {condition}.', subcategories: [] },
        { template: '• الحالة عند المعاينة: {condition}.', subcategories: [] },
        { template: '• حالة الاستخدام: {condition}.', subcategories: [] },
      ]},
      { fact: 'battery', variants: [
        { template: '• البطارية: {battery}.', subcategories: [] },
        { template: '• صحة البطارية {battery}.', subcategories: [] },
        { template: '• قراءة البطارية {battery}.', subcategories: [] },
        { template: '• نسبة البطارية المذكورة {battery}.', subcategories: [] },
        { template: '• البطارية حسب الفحص {battery}.', subcategories: [] },
      ]},
      { fact: 'warranty', variants: [
        { template: '• الضمان: {warranty}.', subcategories: [] },
        { template: '• مدة الضمان {warranty}.', subcategories: [] },
        { template: '• الضمان المذكور {warranty}.', subcategories: [] },
        { template: '• تغطية الضمان {warranty}.', subcategories: [] },
        { template: '• حالة الضمان {warranty}.', subcategories: [] },
      ]},
      { fact: 'region', variants: [
        { template: '• النسخة: {region}.', subcategories: [] },
        { template: '• إصدار المنطقة {region}.', subcategories: [] },
        { template: '• النسخة الإقليمية {region}.', subcategories: [] },
        { template: '• الجهاز نسخة {region}.', subcategories: [] },
        { template: '• السوق الأصلي للجهاز {region}.', subcategories: [] },
      ]},
      { fact: 'year', variants: [
        { template: '• السنة: {year}.', subcategories: [] },
        { template: '• سنة الإصدار {year}.', subcategories: [] },
        { template: '• الجهاز من عام {year}.', subcategories: [] },
        { template: '• تاريخ الطرح {year}.', subcategories: [] },
        { template: '• سنة الصنع المذكورة {year}.', subcategories: [] },
      ]},
      { fact: 'price', variants: [
        { template: '• السعر: {price}.', subcategories: [] },
        { template: '• السعر المطلوب {price}.', subcategories: [] },
        { template: '• القيمة المعروضة {price}.', subcategories: [] },
        { template: '• المبلغ المذكور {price}.', subcategories: [] },
        { template: '• سعر البيع {price}.', subcategories: [] },
      ]},
      { fact: 'box', variants: [
        { template: '• العلبة: {box}.', subcategories: [] },
        { template: '• وضع العلبة {box}.', subcategories: [] },
        { template: '• الجهاز يأتي مع {box}.', subcategories: [] },
        { template: '• العلبة المرافقة {box}.', subcategories: [] },
        { template: '• حالة العلبة {box}.', subcategories: [] },
      ]},
      { fact: 'charger', variants: [
        { template: '• الشاحن: {charger}.', subcategories: [] },
        { template: '• الشاحن المرافق {charger}.', subcategories: [] },
        { template: '• الجهاز يأتي مع {charger}.', subcategories: [] },
        { template: '• وضع الشاحن {charger}.', subcategories: [] },
        { template: '• الشاحن حسب الوصف {charger}.', subcategories: [] },
      ]},
    ],
    featuresBullets: [
      { template: '• السعر {price} محدد قبل نقل الرقم.', subcategories: ['numbers'] },
      { template: '• النقل يتم بعد التوثيق مقابل {price}.', subcategories: ['numbers'] },
      { template: '• لا وسيط في البيع والسعر {price}.', subcategories: ['numbers'] },
      { template: '• الرقم يُسجّل باسم المشتري بسعر {price}.', subcategories: ['numbers'] },
      { template: '• الإجراء يُشرح قبل الاتفاق على {price}.', subcategories: ['numbers'] },
      { template: '• البطارية على {battery} حسب آخر قراءة.', subcategories: [] },
      { template: '• صحة البطارية {battery} ظاهرة في الإعدادات.', subcategories: [] },
      { template: '• الشاشة {screen} بلا خط ظاهر عند الفحص.', subcategories: [] },
      { template: '• مقاس الشاشة {screen}.', subcategories: [] },
      { template: '• الكاميرا {camera} تعمل في الوضعين.', subcategories: [] },
      { template: '• دقة الكاميرا {camera}.', subcategories: [] },
      { template: '• الذاكرة {storage} تسع الاستخدام اليومي.', subcategories: [] },
      { template: '• التخزين {storage} كما في المواصفة.', subcategories: [] },
      { template: '• الأداء مستقر على {model} أثناء التجربة.', subcategories: [] },
      { template: '• الجهاز {model} يفتح التطبيقات بلا تعليق ملحوظ.', subcategories: [] },
      { template: '• الهيكل بلون {color} بلا كسر ظاهر.', subcategories: [] },
      { template: '• الجهاز بلون {color} سليم في الأطراف.', subcategories: [] },
      { template: '• الضمان {warranty} مذكور في الإعلان.', subcategories: [] },
      { template: '• مدة الضمان {warranty}.', subcategories: [] },
      { template: '• الجهاز أصلي من {make}.', subcategories: [] },
      { template: '• الطراز {model} أصلي وغير مجدّد حسب الوصف.', subcategories: [] },
      { template: '• الفحص شمل الشاشة والبطارية قبل العرض.', subcategories: [] },
      { template: '• تم فحص {model} والسعر {price}.', subcategories: [] },
      { template: '• النسخة {region} مطابقة لرقم الطراز.', subcategories: [] },
      { template: '• الإصدار {region} من سنة {year}.', subcategories: [] },
      { template: '• العلبة {box} مرافقة للجهاز.', subcategories: [] },
      { template: '• الشاحن {charger} ضمن الملحقات.', subcategories: [] },
      { template: '• الجهاز بحالة {condition} ثابت في الصور.', subcategories: [] },
      { template: '• سنة الجهاز {year}.', subcategories: [] },
      { template: '• السعر المطلوب {price} بعد الفحص.', subcategories: [] },
    ],
    ctas: [
      { template: 'للتنسيق على نقل الرقم راسل صاحب الإعلان.', subcategories: ['numbers'] },
      { template: 'للمعاينة والتوثيق تواصل عبر الرسائل.', subcategories: ['numbers'] },
      { template: 'للمعاينة تواصل عبر رسائل الإعلان.', subcategories: [] },
      { template: 'راسل البائع لتحديد موعد تجربة الجهاز.', subcategories: [] },
      { template: 'اتصل لصاحب الإعلان قبل الحضور.', subcategories: [] },
      { template: 'للتنسيق على السعر والفحص راسل الآن.', subcategories: [] },
      { template: 'للاستفسار عن الضمان تواصل برسالة.', subcategories: [] },
      { template: 'للمعاينة في مكان متفق عليه راسل المعلن.', subcategories: [] },
      { template: 'اتصل لتأكيد توفر {model} قبل الزيارة.', subcategories: [] },
      { template: 'للتنسيق على التسليم تواصل عبر الإعلان.', subcategories: [] },
      { template: 'راسل لمعرفة قراءة البطارية {battery}.', subcategories: [] },
      { template: 'للمعاينة والفحص تواصل مع البائع.', subcategories: [] },
      { template: 'اتصل للاستفسار عن النسخة {region}.', subcategories: [] },
      { template: 'للتنسيق على السعر {price} راسل المعلن.', subcategories: [] },
      { template: 'تواصل لتحديد موعد استلام {model}.', subcategories: [] },
    ],
    detailsLabel: '🔹 المواصفات:',
    featuresLabel: '🔹 أبرز المميزات:',
    featuresCount: 4,
    introCount: 2,
    minDetails: 1,
  },
};
