import type { PremiumCategory } from './types';

/**
 * Real-estate premium templates — 10/10/10/10, subcategory-aware.
 * Slugs must match src/data/subcategories.ts: for-sale, for-rent, lands,
 * commercial, chalets.
 */
export const REAL_ESTATE_PREMIUM: PremiumCategory = {
  titleTemplates: [
    { template: "أرض {area}م² بسعر {price} — واجهة شارع وجاهزة للبناء", subcategories: ["lands"] },
    { template: "فرصة واضحة: أرض {area}م² مقابل {price} بصك ساري", subcategories: ["lands"] },
    { template: "عرض أرض {area}م² بـ{price} ومدخل سيارة مباشر", subcategories: ["lands"] },
    { template: "عقار {area}م² بـ{rooms} غرف مقابل {price} — توزيع عملي", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "تبحث عن {rooms} غرف بمساحة {area}م² بسعر {price}؟", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "مساحة {area}م² تكفي {rooms} غرف بسعر {price} قرب الخدمات", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "شقة {area}م² بـ{rooms} غرف وطابق {floor} بسعر {price}", subcategories: ["for-sale"] },
    { template: "تمليك {area}م² و{rooms} غرف ودور {floor} بحالة {condTone}", subcategories: ["for-sale"] },
    { template: "وحدة {rooms} غرف و{bathrooms} حمامات على {area}م² بسعر {price}", subcategories: ["for-sale", "for-rent", "chalets"] },
    { template: "استلم {rooms} غرف و{bathrooms} حمامات على {area}م² بـ{price}", subcategories: ["for-sale", "for-rent", "chalets"] },
  ],
  paragraph1: [
    { template: "للبيع أرض بمساحة {area} متر مربع بسعر {price}. الواجهة على شارع والصك واضح لمن يريد البناء فورًا.", subcategories: ["lands"] },
    { template: "هذه أرض مساحتها {area} متر ومعروضة بـ{price}. الأرض مستوية والمدخل يستقبل سيارة بلا عناء.", subcategories: ["lands"] },
    { template: "نعرض أرضًا مساحتها {area} متر مقابل {price}. الموقع يصلح لفيلا والحد واضح بعد المعاينة.", subcategories: ["lands"] },
    { template: "عقار بمساحة {area} متر يضم {rooms} غرف بسعر {price}. التوزيع عملي ويناسب سكنًا أو مكتبًا قرب الخدمات.", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "المساحة {area} متر تتوزع على {rooms} غرف بسعر {price}. المكان هادئ والوصول إلى الخدمات قصير.", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "طرحنا مساحة {area} متر بعدد {rooms} غرف مقابل {price}. التقسيم مريح والمعاينة متاحة هذا الأسبوع.", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "شقة تمليك بمساحة {area} متر و{rooms} غرف على الطابق {floor}. الحالة {condTone} والسعر {price} يثبت بعد المعاينة.", subcategories: ["for-sale"] },
    { template: "سكن على الدور {floor} بمساحة {area} متر و{rooms} غرف و{bathrooms} حمامات. التشطيب {condTone} والمطلوب {price}.", subcategories: ["for-sale"] },
    { template: "الوحدة فيها {rooms} غرف و{bathrooms} حمامات على مساحة {area} متر. السعر {price} والإقامة هادئة قرب خدمات اليوم.", subcategories: ["for-sale", "for-rent", "chalets"] },
    { template: "سكن بـ{rooms} غرف و{bathrooms} حمامات ومساحة {area} متر. القيمة {price} والإضاءة طبيعية طوال النهار.", subcategories: ["for-sale", "for-rent", "chalets"] },
  ],
  paragraph2: [
    { template: "الأرض مستوية والمساحة {area} متر تسمح ببناء مريح. السعر {price} يبقى إلى حين مشاهدة الموقع.", subcategories: ["lands"] },
    { template: "شارع الأرض واضح ومساحتها {area} متر بلا عائق على المدخل. القيمة {price} تناسب من يبني قريبًا.", subcategories: ["lands"] },
    { template: "يمكن الوقوف أمام الأرض ومساحتها {area} متر بسهولة. المطلوب {price} والصك جاهز للمراجعة.", subcategories: ["lands"] },
    { template: "قرب الخدمات يختصر المشوار من هذه المساحة {area} متر. {rooms} غرف بسعر {price} تمنح جلوسًا مريحًا.", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "التهوية جيدة داخل {rooms} غرف على {area} متر. السعر {price} يشمل المساحة كما هي بلا رسوم خفية.", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "المعاينة تظهر توزيع {rooms} غرف على {area} متر. الاتفاق حول {price} يتم بعد الزيارة.", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "الإضاءة الطبيعية تملأ الطابق {floor} طوال النهار. المساحة {area} متر و{rooms} غرف بحالة {condTone} والسعر {price}.", subcategories: ["for-sale"] },
    { template: "الخصوصية أوضح على الدور {floor} مع {bathrooms} حمامات. {rooms} غرف بمساحة {area} متر وحالة {condTone} مقابل {price}.", subcategories: ["for-sale"] },
    { template: "الحمامات {bathrooms} تخدم {rooms} غرف بلا ازدحام. المساحة {area} متر والسعر {price} مناسب لإقامة هادئة.", subcategories: ["for-sale", "for-rent", "chalets"] },
    { template: "الجلسة تتسع لأهل البيت داخل {rooms} غرف. {bathrooms} حمامات على {area} متر والسعر {price} بعد الاتفاق.", subcategories: ["for-sale", "for-rent", "chalets"] },
  ],
  paragraph3: [
    { template: "السعر {price} لأرض مساحتها {area} متر. المعاينة متاحة والصك يُراجع قبل التحويل.", subcategories: ["lands"] },
    { template: "نطلب {price} مقابل أرض {area} متر. الاتفاق يتم بعد مشاهدة الواجهة.", subcategories: ["lands"] },
    { template: "القيمة {price} تشمل أرض {area} متر بصك واضح. التسليم بعد إتمام الفحص.", subcategories: ["lands"] },
    { template: "السعر المطلوب {price} لمساحة {area} متر و{rooms} غرف. المعاينة تحدد موعد الكتابة.", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "نطلب {price} مقابل {rooms} غرف على {area} متر. الزيارة متاحة قبل أي التزام.", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "العرض المالي {price} لعقار {area} متر بعدد {rooms} غرف. الإغلاق يتم بعد المعاينة.", subcategories: ["for-sale", "for-rent", "commercial", "chalets"] },
    { template: "السعر {price} لشقة {area} متر على الطابق {floor}. فيها {rooms} غرف بحالة {condTone} وجاهزة للمشاهدة.", subcategories: ["for-sale"] },
    { template: "المطلوب {price} لتمليك الدور {floor} بمساحة {area} متر. عدد الغرف {rooms} والحالة {condTone}.", subcategories: ["for-sale"] },
    { template: "القيمة {price} لـ{rooms} غرف و{bathrooms} حمامات. المساحة {area} متر والتسليم بعد الاتفاق.", subcategories: ["for-sale", "for-rent", "chalets"] },
    { template: "مقابل {price} تحصل على {area} متر و{rooms} غرف و{bathrooms} حمامات. الموعد يتحدد بعد المعاينة.", subcategories: ["for-sale", "for-rent", "chalets"] },
  ],
  structured: {
    titleFormat: [
      { template: 'شقة {rooms} نوم و{bathrooms} حمام بسعر {price}', subcategories: [] },
      { template: '{rooms} غرف نوم و{bathrooms} حمامات — بسعر {price}', subcategories: [] },
      { template: 'شقة بمساحة {area} م² — {rooms} غرف نوم', subcategories: [] },
      { template: 'للبيع: {rooms} غرف و{bathrooms} حمامات بسعر {price}', subcategories: [] },
      { template: 'شقة {rooms} غرف — تشطيب حديث بسعر {price}', subcategories: [] },
      { template: 'عقار {area} م² — {rooms} نوم، {bathrooms} حمام', subcategories: [] },
      { template: 'وحدة بمساحة {area} م² — {rooms} غرف، {bathrooms} حمامات', subcategories: [] },
      { template: 'فرصة سكن: {rooms} نوم و{bathrooms} حمام بسعر {price}', subcategories: [] },
      { template: 'شقة بمساحة {area} م² و{rooms} غرف', subcategories: [] },
      { template: '{area} م² مع {rooms} غرف — بسعر {price}', subcategories: [] },
      { template: 'شقة عصرية — {rooms} نوم، {bathrooms} حمام، بسعر {price}', subcategories: [] },
      { template: 'عقار مميز — {rooms} غرف و{bathrooms} حمامات', subcategories: [] },
      { template: 'للبيع — شقة بمساحة {area} م² بسعر {price}', subcategories: [] },
      { template: 'فرصة ذهبية: {rooms} نوم و{bathrooms} حمام', subcategories: [] },
      { template: 'شقة بتشطيب حديث — {area} م²، {rooms} غرف', subcategories: [] },
      { template: 'وحدة عائلية — {rooms} غرف بسعر {price}', subcategories: [] },
      { template: 'شقة {rooms} نوم — {area} م² بسعر {price}', subcategories: [] },
      { template: 'عرض عقاري مميز — {rooms} غرف و{bathrooms} حمامات', subcategories: [] },
      { template: 'شقة مريحة — {rooms} نوم بسعر {price}', subcategories: [] },
      { template: '{rooms} غرف مع {bathrooms} حمام — فرصة سكن', subcategories: [] },
      { template: 'شقة فسيحة — {area} م² و{rooms} غرف بسعر {price}', subcategories: [] },
      { template: 'عقار للبيع — {rooms} غرف نوم و{bathrooms} حمامات', subcategories: [] },
      { template: 'شقة بتصميم عصري — {rooms} نوم بسعر {price}', subcategories: [] },
      { template: 'وحدة بمساحة {area} م² — سعر {price}', subcategories: [] },
      { template: 'شقة — {rooms} غرف و{bathrooms} حمامات بسعر {price}', subcategories: [] },
    ],
    hooks: [
      { template: 'فرصة مميزة للسكن الراقي أو الاستثمار الناجح!', subcategories: [] },
      { template: 'عرض يستحق النظر — وحدة بمواصفات عالية.', subcategories: [] },
      { template: 'فرصة لا تفوّت لمن يبحث عن السكن المريح.', subcategories: [] },
      { template: 'للجادين — عقار يجمع الموقع المتميز والتشطيب الحديث.', subcategories: [] },
      { template: 'عقار مطروح للبيع بمواصفات تستحق المعاينة.', subcategories: [] },
      { template: 'وحدة بموقع حيوي — فرصة للسكن أو الاستثمار.', subcategories: [] },
      { template: 'عرض مدروس — الموقع والتشطيب والسعر في مكان واحد.', subcategories: [] },
      { template: 'فرصة للسكن العائلي الهادئ قرب كل الخدمات.', subcategories: [] },
      { template: 'وحدة بمواصفات مميزة تنتظر من يقدّرها.', subcategories: [] },
      { template: 'لا تفوّت هذه الفرصة العقارية.', subcategories: [] },
      { template: 'عقار بتشطيب حديث وموقع استراتيجي.', subcategories: [] },
      { template: 'فرصة سكنية بتوزيع عملي وتشطيب راقٍ.', subcategories: [] },
      { template: 'عرض عقاري يستحق الزيارة قبل القرار.', subcategories: [] },
      { template: 'وحدة سكنية بتفاصيل مدروسة وسعر منطقي.', subcategories: [] },
      { template: 'مطروح للبيع — عقار بكل مقومات السكن المريح.', subcategories: [] },
    ],
    introParagraphs: [
      { template: 'نضع بين أيديكم وحدة سكنية في منطقة حيوية وهادئة بقرب كافة الخدمات.', subcategories: [] },
      { template: 'تم تصميم هذه الوحدة بعناية لتوفر أقصى درجات الراحة والخصوصية للعائلة.', subcategories: [] },
      { template: 'تقع الوحدة في موقع استراتيجي قريب من المدارس والأسواق والمواصلات.', subcategories: [] },
      { template: 'تشطيبات حديثة وديكورات عصرية تجعلها جاهزة للسكن الفوري دون أي تعديل.', subcategories: [] },
      { template: 'الوحدة تناسب العائلات الباحثة عن الهدوء والقرب من الخدمات في آن واحد.', subcategories: [] },
      { template: 'عقار بمساحة مدروسة وتوزيع داخلي يوفر الراحة اليومية.', subcategories: [] },
      { template: 'الموقع يمنح سهولة الوصول إلى أهم المرافق في دقائق.', subcategories: [] },
      { template: 'وحدة سكنية بمواصفات حديثة تصلح للسكن المباشر أو التأجير.', subcategories: [] },
      { template: 'جو هادئ وبيئة عائلية مع قرب من الخدمات الأساسية.', subcategories: [] },
      { template: 'شقة مضيئة بتهوية ممتازة وإطلالة مريحة على المنطقة.', subcategories: [] },
      { template: 'المنطقة استراتيجية وتُعد من أبرز المواقع الحيوية القريبة من المرافق.', subcategories: [] },
      { template: 'وحدة تشطيبها حديث ويصلح معها الانتقال الفوري دون تجهيزات.', subcategories: [] },
      { template: 'تصميم داخلي يوازن بين المساحة والوظائف اليومية.', subcategories: [] },
      { template: 'مدخل مريح ومواقف متوفرة قريبة من المبنى.', subcategories: [] },
      { template: 'مستوى الصيانة في المبنى عالي والخدمات المشتركة منتظمة.', subcategories: [] },
      { template: 'لا حاجة لتعديلات — الوحدة جاهزة بكامل مواصفاتها.', subcategories: [] },
      { template: 'أسعار منطقة كهذه ترتفع مع الطلب — فرصة للاستثمار.', subcategories: [] },
      { template: 'مناسبة للعائلات الصغيرة والكبيرة على حد سواء.', subcategories: [] },
      { template: 'استُخدمت مواد بناء عالية الجودة في كل التفاصيل.', subcategories: [] },
      { template: 'الموقع مشهود له في السوق — طلب مستمر في هذه المنطقة.', subcategories: [] },
    ],
    detailsGroups: [
      { fact: 'rooms', variants: [
        { template: '• عدد غرف النوم: {rooms} غرف نوم واسعة ومضيئة.', subcategories: [] },
        { template: '• غرف النوم: {rooms} غرف بتوزيع مريح وإضاءة طبيعية.', subcategories: [] },
        { template: '• {rooms} غرف نوم بمساحات مناسبة لكل غرفة.', subcategories: [] },
        { template: '• تحتوي الوحدة على {rooms} غرف نوم مريحة.', subcategories: [] },
        { template: '• {rooms} غرف نوم — كل غرفة بحجم عملي.', subcategories: [] },
      ]},
      { fact: 'bathrooms', variants: [
        { template: '• عدد الحمامات: {bathrooms} حمامات بتشطيبات حديثة وعملية.', subcategories: [] },
        { template: '• الحمامات: {bathrooms} حمامات مجهزة بكل احتياجات اليوم.', subcategories: [] },
        { template: '• {bathrooms} حمامات بتصميم عصري.', subcategories: [] },
        { template: '• الحمامات عددها {bathrooms} وتوزيعها عملي.', subcategories: [] },
        { template: '• {bathrooms} حمامات — تشطيب كامل وتهوية جيدة.', subcategories: [] },
      ]},
      { fact: 'area', variants: [
        { template: '• المساحة الإجمالية: {area} م² موزعة بشكل مدروس.', subcategories: [] },
        { template: '• المساحة: {area} م² — توزيع داخلي يمنح إحساساً بالاتساع.', subcategories: [] },
        { template: '• {area} م² موزعة على غرف ومرافق بشكل متوازن.', subcategories: [] },
        { template: '• المساحة الكلية: {area} م².', subcategories: [] },
        { template: '• تبلغ مساحة الوحدة {area} م² — مساحة عملية للعائلة.', subcategories: [] },
      ]},
      { fact: 'floor', variants: [
        { template: '• الطابق: {floor}.', subcategories: [] },
        { template: '• تقع الوحدة في الطابق {floor}.', subcategories: [] },
        { template: '• الطابق {floor} — إطلالة وتهوية جيدة.', subcategories: [] },
        { template: '• الطابق {floor} — وصول سهل وحركة مريحة.', subcategories: [] },
        { template: '• الوحدة في الطابق {floor}.', subcategories: [] },
      ]},
      { fact: 'living', variants: [
        { template: '• المعيشة: صالون وغرفة معيشة مريحة للعائلات.', subcategories: [] },
        { template: '• صالة معيشة واسعة تتسع للعائلة والضيوف.', subcategories: [] },
        { template: '• منطقة معيشة مريحة بتهوية طبيعية ممتازة.', subcategories: [] },
        { template: '• صالة واسعة تناسب الجلسات العائلية.', subcategories: [] },
        { template: '• معيشة مريحة مع إمكانية توزيع الأثاث بمرونة.', subcategories: [] },
      ]},
      { fact: 'balcony', variants: [
        { template: '• الملحقات: بلكونة بإطلالة جميلة وتهوية ممتازة.', subcategories: [] },
        { template: '• بلكونة واسعة تصلح للجلسة العائلية.', subcategories: [] },
        { template: '• شرفة بإطلالة مريحة على المنطقة.', subcategories: [] },
        { template: '• بلكونة مميزة تسمح بالاستفادة من الجو الخارجي.', subcategories: [] },
        { template: '• ملحق خارجي بمساحة مريحة.', subcategories: [] },
      ]},
      { fact: 'price', variants: [
        { template: '• السعر: {price}.', subcategories: [] },
        { template: '• السعر المعلن: {price}.', subcategories: [] },
        { template: '• بسعر {price} — قابل للنقاش مع الجادين.', subcategories: [] },
        { template: '• القيمة: {price}.', subcategories: [] },
        { template: '• {price} — السعر المطلوب.', subcategories: [] },
      ]},
      { fact: 'condition', variants: [
        { template: '• الحالة: جاهزة للسكن الفوري بعد المعاينة.', subcategories: [] },
        { template: '• الوحدة جاهزة للانتقال الفوري دون تجهيزات.', subcategories: [] },
        { template: '• حالة العقار: ممتازة.', subcategories: [] },
        { template: '• الوحدة بحالة جيدة ومصانة.', subcategories: [] },
        { template: '• جاهزة للسكن — لا تحتاج صيانة فورية.', subcategories: [] },
      ]},
      { fact: 'parking', variants: [
        { template: '• يتوفر موقف سيارة خاص.', subcategories: [] },
        { template: '• موقف سيارة قريب من المدخل.', subcategories: [] },
        { template: '• إمكانية تأمين موقف للمالك أو المستأجر.', subcategories: [] },
        { template: '• موقف واسع ضمن المشروع.', subcategories: [] },
        { template: '• مواقف متوفرة قريبة من المبنى.', subcategories: [] },
      ]},
      { fact: 'view', variants: [
        { template: '• إطلالة مريحة على المنطقة.', subcategories: [] },
        { template: '• إطلالة مميزة من النوافذ الرئيسية.', subcategories: [] },
        { template: '• إطلالة مفتوحة ورؤية واضحة.', subcategories: [] },
        { template: '• إطلالة هادئة ومريحة للعين.', subcategories: [] },
        { template: '• إطلالة جميلة مع تهوية طبيعية ممتازة.', subcategories: [] },
      ]},
      { fact: 'year', variants: [
        { template: '• سنة البناء: {year}.', subcategories: [] },
        { template: '• المبنى من عام {year}.', subcategories: [] },
        { template: '• بُني في {year} — بحالة جيدة.', subcategories: [] },
        { template: '• العمر التقريبي: من {year}.', subcategories: [] },
        { template: '• شُيّد عام {year} — صيانة منتظمة.', subcategories: [] },
      ]},
      { fact: 'furnished', variants: [
        { template: '• الوحدة مفروشة بالكامل.', subcategories: [] },
        { template: '• مفروشة بأثاث حديث.', subcategories: [] },
        { template: '• تأتي الوحدة مع الأثاث الأساسي.', subcategories: [] },
        { template: '• مفروشة وجاهزة للانتقال المباشر.', subcategories: [] },
        { template: '• يمكن تسليم الوحدة مفروشة أو فارغة حسب الاتفاق.', subcategories: [] },
      ]},
    ],
    featuresBullets: [
      { template: '• موقع استراتيجي قريب من الشوارع الرئيسية.', subcategories: [] },
      { template: '• تشطيبات ممتازة وديكورات عصرية.', subcategories: [] },
      { template: '• توزيع داخلي ذكي يمنح شعوراً بالاتساع.', subcategories: [] },
      { template: '• إضاءة طبيعية وتهوية ممتازة.', subcategories: [] },
      { template: '• مناسب للسكن العائلي أو الاستثمار طويل الأمد.', subcategories: [] },
      { template: '• حي هادئ وآمن مع بيئة عائلية.', subcategories: [] },
      { template: '• سعر مدروس قياساً على المنطقة.', subcategories: [] },
      { template: '• بنية تحتية حديثة وخدمات متكاملة.', subcategories: [] },
      { template: '• قريب من المواصلات العامة.', subcategories: [] },
      { template: '• تصميم يوفر الخصوصية لكل أفراد العائلة.', subcategories: [] },
      { template: '• يصلح للسكن المباشر أو التأجير بعائد جيد.', subcategories: [] },
      { template: '• مواد بناء عالية الجودة.', subcategories: [] },
      { template: '• إطلالة مريحة بعيداً عن الضوضاء.', subcategories: [] },
      { template: '• مبنى بصيانة جيدة ومصعد.', subcategories: [] },
      { template: '• قريب من الحدائق والمناطق الترفيهية.', subcategories: [] },
      { template: '• تكاليف تشغيل منخفضة.', subcategories: [] },
      { template: '• فرصة استثمارية بعائد مجزٍ.', subcategories: [] },
      { template: '• سهل الوصول من الطرق الرئيسية.', subcategories: [] },
      { template: '• خدمات قريبة: مدارس، أسواق، مطاعم.', subcategories: [] },
      { template: '• مناخ داخلي مريح على مدار السنة.', subcategories: [] },
      { template: '• تصميم عصري مع لمسات أنيقة.', subcategories: [] },
      { template: '• إطلالة لا تحجبها المباني المجاورة.', subcategories: [] },
      { template: '• نظام أمان في المبنى.', subcategories: [] },
      { template: '• مصعد حديث وسريع.', subcategories: [] },
      { template: '• مدخل أنيق ومنطقة استقبال مرتبة.', subcategories: [] },
      { template: '• خدمات صيانة منتظمة في المبنى.', subcategories: [] },
      { template: '• يمكن تحويل إحدى الغرف لمكتب أو غرفة ضيوف.', subcategories: [] },
      { template: '• مناسبة للعائلات الصغيرة والكبيرة.', subcategories: [] },
      { template: '• موقع مميز يجعل الوحدة مطلوبة دائماً.', subcategories: [] },
      { template: '• مساحة عملية توظف كل متر بشكل مفيد.', subcategories: [] },
    ],
    ctas: [
      { template: 'للاستفسار والمعاينة تواصل عبر رسائل الإعلان.', subcategories: [] },
      { template: 'المعاينة متاحة بالتنسيق — راسل البائع لتحديد الموعد.', subcategories: [] },
      { template: 'لجدية الشراء: تواصل مع البائع لترتيب زيارة.', subcategories: [] },
      { template: 'للمزيد من التفاصيل راسل البائع في أي وقت.', subcategories: [] },
      { template: 'المعاينة متاحة — تواصل الآن لترتيب موعد مناسب.', subcategories: [] },
      { template: 'للاستفسار عن الوحدة راسل البائع مباشرة.', subcategories: [] },
      { template: 'اتصل بالبائع لجدولة موعد المعاينة.', subcategories: [] },
      { template: 'العرض متاح للمعاينة — تواصل عبر رسائل الإعلان.', subcategories: [] },
      { template: 'للجادين: تواصل مع البائع مباشرة.', subcategories: [] },
      { template: 'المعاينة في الموقع متاحة بترتيب مسبق.', subcategories: [] },
      { template: 'لأي استفسار إضافي راسل البائع.', subcategories: [] },
      { template: 'للتواصل المباشر ومعاينة الوحدة راسلنا.', subcategories: [] },
      { template: 'يمكن ترتيب موعد معاينة في أي وقت مناسب لك.', subcategories: [] },
      { template: 'تواصل لترتيب زيارة للوحدة على الطبيعة.', subcategories: [] },
      { template: 'لا تتردد بالتواصل لمزيد من التفاصيل.', subcategories: [] },
    ],
    detailsLabel: '🔹 تفاصيل الوحدة:',
    featuresLabel: '🔹 أبرز المميزات:',
    featuresCount: 4,
    introCount: 2,
    minDetails: 2,
  },
};
