export const SELECTORS = {
  app: {
    root: '#root',
    header: 'header',
    menuButton: 'button[title="Menu"], button[title="القائمة"]',
  },
  auth: {
    gateway: {
      createAccountBtn: 'button:has-text("Create"), button:has-text("حساب")',
      haveAccountBtn: 'button:has-text("Sign In"), button:has-text("دخول")',
      quickDemoBtn: 'button:has-text("Quick Demo")',
    },
    register: {
      firstNameInput: 'input[placeholder*="First Name"], input[placeholder*="الأول"]',
      phoneInput: 'input[placeholder="07xxxxxxxx"]',
      emailInput: 'input[type="email"]',
      passwordInput: 'input[type="password"]',
      countrySelector: 'select',
      submitButton: 'button[type="submit"]',
      errorBanner: 'div.bg-red-50',
      step2Header: 'h2:has-text("Check your Email"), h2:has-text("تحقق من بريدك")',
      activateBtn: 'button:has-text("Verify Link & Activate Account"), button:has-text("تأكيد الرابط وتفعيل الحساب الآن")',
    },
  },
  postAd: {
    fabButton: 'button[aria-label="Post ad"], button[aria-label="أضف إعلان"]',
    categoryCard: 'div.cursor-pointer',
    subcategoryCard: 'div.cursor-pointer',
    samplePhotoButton: 'button:has-text("Use sample photo"), button:has-text("استخدم صورة")',
    continueToLocationButton: 'button:has-text("Continue to Location"), button:has-text("متابعة")',
    citySelect: 'select',
    neighborhoodSelect: 'select',
    landmarkInput: 'input[placeholder*="Near"], input[placeholder*="قرب"]',
    continueToAiDrafterBtn: 'button:has-text("Continue to AI Drafter"), button:has-text("متابعة")',
    noteTextarea: 'textarea',
    generateListingBtn: 'button:has-text("Generate Listing"), button:has-text("صياغة الإعلان")',
    publishNowBtn: 'button:has-text("Publish Now"), button:has-text("نشر الإعلان الآن")',
  },
  aiSearch: {
    textarea: 'textarea[placeholder*="Type"], textarea[placeholder*="اكتب"]',
    submitButton: 'button[title="Send"], button[title="إرسال"]',
    micButton: 'button[title="Voice Input"], button[title="تحدث بصوتك"]',
    imageButton: 'button[title="Add Photos"], button[title="إضافة صور"]',
    quotaBadge: 'div:has-text("credits"), div:has-text("رصيد اليوم")',
    responseCard: 'div:has-text("نتائج التحليل"), div:has-text("Analysis Results")',
    shareDrawer: 'div:has-text("Share"), div:has-text("شارك")',
  },
  chat: {
    messagesTab: 'button:has-text("Messages"), button:has-text("الرسائل")',
    seedThread: 'div.cursor-pointer:has-text("Rolex Submariner")',
    messageInput: 'input[placeholder*="Type"], input[placeholder*="اكتب"]',
    sendButton: 'button[type="submit"]',
    paywallBanner: 'div.bg-amber-50',
    listingChatBtn: 'button:has-text("Chat"), button:has-text("دردشة")',
  },
  wishlist: {
    bookmarkHeart: 'button[id^="wishlist-toggle-"]',
    wishlistTab: 'button:has-text("Favorites"), button:has-text("المفضلة")',
    emptyState: 'div:has-text("No listings"), div:has-text("لا توجد")',
    listingCard: 'div[class*="rounded-2xl"][class*="cursor-pointer"]',
  },
} as const;
