BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER TABLE public.listings
  ADD COLUMN IF NOT EXISTS search_chars text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS search_version integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.search_keywords (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_key text NOT NULL,
  keyword text NOT NULL,
  CONSTRAINT search_keywords_group_keyword_unique UNIQUE (group_key, keyword)
);

CREATE INDEX IF NOT EXISTS search_keywords_group_idx
  ON public.search_keywords (group_key);

CREATE INDEX IF NOT EXISTS search_keywords_keyword_idx
  ON public.search_keywords (keyword);

CREATE INDEX IF NOT EXISTS listings_search_chars_gin_idx
  ON public.listings USING gin (search_chars);

CREATE OR REPLACE FUNCTION public.normalize_search_text(p_input text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $function$
  SELECT regexp_replace(
    public.normalize_arabic(
      translate(
        lower(coalesce(p_input, '')),
        '٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹',
        '01234567890123456789'
      )
    ),
    '[[:space:]]+',
    ' ',
    'g'
  );
$function$;

CREATE OR REPLACE FUNCTION public.search_json_values(p_value jsonb)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
PARALLEL SAFE
AS $function$
DECLARE
  v_result text;
BEGIN
  IF p_value IS NULL THEN
    RETURN '';
  END IF;

  CASE jsonb_typeof(p_value)
    WHEN 'object' THEN
      SELECT coalesce(string_agg(
        public.search_json_values(e.value),
        ' '
      ), '')
      INTO v_result
      FROM jsonb_each(p_value) AS e;

      RETURN v_result;

    WHEN 'array' THEN
      SELECT coalesce(string_agg(
        public.search_json_values(e.value),
        ' '
      ), '')
      INTO v_result
      FROM jsonb_array_elements(p_value) AS e(value);

      RETURN v_result;

    WHEN 'string' THEN
      RETURN p_value #>> '{}';

    WHEN 'number' THEN
      RETURN p_value #>> '{}';

    WHEN 'boolean' THEN
      RETURN p_value #>> '{}';

    ELSE
      RETURN '';
  END CASE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.expand_search_keywords(p_input text)
RETURNS text
LANGUAGE sql
STABLE
AS $function$
  WITH tokens AS (
    SELECT DISTINCT token
    FROM regexp_split_to_table(
      public.normalize_search_text(p_input),
      '[[:space:]]+'
    ) AS token
    WHERE token <> ''
  ),
  expanded AS (
    SELECT token AS term
    FROM tokens

    UNION

    SELECT aliases.keyword AS term
    FROM tokens AS t
    JOIN public.search_keywords AS matched
      ON public.normalize_search_text(matched.keyword) = t.token
    JOIN public.search_keywords AS aliases
      ON aliases.group_key = matched.group_key
  )
  SELECT coalesce(string_agg(term, ' ' ORDER BY term), '')
  FROM expanded;
$function$;

CREATE OR REPLACE FUNCTION public.search_character_array(p_input text)
RETURNS text[]
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $function$
  SELECT coalesce(
    array_agg(character_value ORDER BY character_value),
    '{}'::text[]
  )
  FROM (
    SELECT DISTINCT character_value
    FROM regexp_split_to_table(
      regexp_replace(
        public.normalize_search_text(p_input),
        '[[:space:]]+',
        '',
        'g'
      ),
      ''
    ) AS character_value
    WHERE character_value <> ''
  ) AS characters;
$function$;

CREATE OR REPLACE FUNCTION public.search_listings(
  p_query text,
  p_market text DEFAULT NULL,
  p_limit integer DEFAULT 20,
  p_offset integer DEFAULT 0
)
RETURNS SETOF public.listings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_norm text;
  v_query text;
  v_tsq tsquery;
  v_limit integer := greatest(1, least(coalesce(p_limit, 20), 100));
  v_offset integer := greatest(0, coalesce(p_offset, 0));
  v_chars text[];
BEGIN
  v_norm := btrim(public.normalize_search_text(coalesce(p_query, '')));

  IF v_norm = '' THEN
    RETURN;
  END IF;

  v_query := public.expand_search_keywords(v_norm);
  v_chars := public.search_character_array(v_norm);

  IF cardinality(v_chars) = 1 THEN
    IF EXISTS (
      SELECT 1
      FROM public.listings AS l
      WHERE l.status = 'active'
        AND (p_market IS NULL OR l.country_code = upper(p_market))
        AND l.search_chars @> v_chars
    ) THEN
      RETURN QUERY
      SELECT l.*
      FROM public.listings AS l
      WHERE l.status = 'active'
        AND (p_market IS NULL OR l.country_code = upper(p_market))
        AND l.search_chars @> v_chars
      ORDER BY l.created_at DESC
      LIMIT v_limit OFFSET v_offset;

      RETURN;
    END IF;
  END IF;

  v_tsq := public.build_prefix_tsquery(v_query);

  IF v_tsq IS NOT NULL THEN
    IF EXISTS (
      SELECT 1
      FROM public.listings AS l
      WHERE l.status = 'active'
        AND (p_market IS NULL OR l.country_code = upper(p_market))
        AND l.fts @@ v_tsq
    ) THEN
      RETURN QUERY
      SELECT l.*
      FROM public.listings AS l
      WHERE l.status = 'active'
        AND (p_market IS NULL OR l.country_code = upper(p_market))
        AND l.fts @@ v_tsq
      ORDER BY
        ts_rank_cd(l.fts, v_tsq) DESC,
        l.created_at DESC
      LIMIT v_limit OFFSET v_offset;

      RETURN;
    END IF;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.listings AS l
    WHERE l.status = 'active'
      AND (p_market IS NULL OR l.country_code = upper(p_market))
      AND word_similarity(v_norm, l.search_text) > 0.3
  ) THEN
    RETURN QUERY
    SELECT l.*
    FROM public.listings AS l
    WHERE l.status = 'active'
      AND (p_market IS NULL OR l.country_code = upper(p_market))
      AND word_similarity(v_norm, l.search_text) > 0.3
    ORDER BY
      word_similarity(v_norm, l.search_text) DESC,
      l.created_at DESC
    LIMIT v_limit OFFSET v_offset;

    RETURN;
  END IF;

  RETURN QUERY
  SELECT l.*
  FROM public.listings AS l
  WHERE l.status = 'active'
    AND (p_market IS NULL OR l.country_code = upper(p_market))
    AND public.normalize_search_text(l.search_text)
      LIKE '%' || v_norm || '%'
  ORDER BY l.created_at DESC
  LIMIT v_limit OFFSET v_offset;

  RETURN;
END;
$function$;

COMMIT;
